import {nativeResponseJson} from '@/lib/api/native-response';
import {NextRequest,NextResponse} from 'next/server';
import {getServerSession} from 'next-auth';
import {authOptions} from '@/lib/auth/config';
import {getNativeDatabase} from '@/lib/db/database';
import {recipeActor,readStaffRecipe,saveStaffRecipe} from '@/lib/db/repository/native-staff-recipes';
import {NativeStaffClientError} from '@/lib/db/repository/native-staff-client';
export const runtime='nodejs';export const maxDuration=60;
export async function PATCH(req:NextRequest){try{const session=await getServerSession(authOptions);if(!session?.user?.id)throw new NativeStaffClientError('Unauthorized',401);const db=getNativeDatabase(),actor=await recipeActor(db,session.user.id,true);if(actor.get('role')!=='admin')throw new NativeStaffClientError('Admin access required',403);const body=await req.json(),operations=Array.isArray(body)?body:[body];if(!operations.length||operations.length>500)throw new NativeStaffClientError('Supply between 1 and 500 operations');const stats={total:operations.length,updated:0,notFound:0,failed:0},errors=[];for(const op of operations){const identifier=op._id||op.name||'unknown';try{let id=op._id;if(!id&&op.name){const matches=await db.collection('recipes').where('name','==',op.name).limit(2).get();if(matches.size>1)throw new NativeStaffClientError('Ambiguous recipe name; supply _id',409);id=matches.docs[0]?.id;}if(!id){stats.notFound++;errors.push({identifier,error:'Recipe not found'});continue;}const existing=await readStaffRecipe(db,session.user.id,id),updates={...op.updates,_nativeExpectedUpdatedAt:existing.updatedAt??null};for(const field of ['ingredients','instructions','tags','dietaryRestrictions','allergens','medicalContraindications']){const v=updates[field];if(v&&!Array.isArray(v)&&typeof v==='object'){if(!['push','addToSet'].includes(v.mode))throw new NativeStaffClientError('Invalid array operation');const combined=[...(existing[field]||[]),...(Array.isArray(v.items)?v.items:[v.items])];updates[field]=v.mode==='push'?combined:[...new Map(combined.map(item=>[JSON.stringify(item),item])).values()];}}await saveStaffRecipe(db,session.user.id,updates,id);stats.updated++;}catch(e){if(e instanceof NativeStaffClientError&&e.status===404)stats.notFound++;else stats.failed++;errors.push({identifier,error:e instanceof NativeStaffClientError?e.message:'Invalid recipe update'});}}return nativeResponseJson({success:stats.failed===0&&stats.notFound===0,message:`Updated ${stats.updated} recipes`,stats,errors},{status:errors.length?207:200});}catch(e){return nativeResponseJson({success:false,error:e instanceof NativeStaffClientError?e.message:'Unable to update recipes'},{status:e instanceof NativeStaffClientError?e.status:e instanceof SyntaxError?400:500});}}
