/** Application-owned document API implemented exclusively by MongoDB. */
import type { Timestamp, WriteResult, FieldPath, Filter, AggregateField } from './mongo-values.mjs';
export {Timestamp,WriteResult,FieldPath,Filter,AggregateField,GeoPoint,FieldValue} from './mongo-values.mjs';
export type DocumentData=Record<string,any>;
export type WhereFilterOp='=='|'!='|'<'|'<='|'>'|'>='|'in'|'not-in'|'array-contains'|'array-contains-any';
export type Field=string|FieldPath;
export type SetOptions={merge?:boolean;mergeFields?:Field[]};
export type Precondition={lastUpdateTime?:Timestamp;exists?:boolean};
export interface DocumentSnapshot<T=DocumentData>{readonly id:string;readonly exists:boolean;readonly ref:DocumentReference<T>;readonly createTime?:Timestamp;readonly updateTime?:Timestamp;readonly readTime:Timestamp;data():T|undefined;get(field:Field):any;isEqual(other:DocumentSnapshot<T>):boolean;}
export interface QueryDocumentSnapshot<T=DocumentData> extends DocumentSnapshot<T>{data():T;}
export interface DocumentChange<T=DocumentData>{type:'added'|'modified'|'removed';doc:QueryDocumentSnapshot<T>;oldIndex:number;newIndex:number;}
export interface QuerySnapshot<T=DocumentData>{readonly empty:boolean;readonly size:number;readonly docs:QueryDocumentSnapshot<T>[];readonly readTime:Timestamp;forEach(callback:(doc:QueryDocumentSnapshot<T>)=>void):void;docChanges():DocumentChange<T>[];}
export interface AggregateQuery<T extends DocumentData=DocumentData>{get():Promise<{data():T}>;}
export interface Query<T=DocumentData>{readonly database:MongoDatabase;readonly path:string;where(filter:Filter):Query<T>;where(field:Field,op:WhereFilterOp,value:any):Query<T>;orderBy(field:Field,direction?:'asc'|'desc'):Query<T>;limit(n:number):Query<T>;offset(n:number):Query<T>;select(...fields:Field[]):Query<DocumentData>;startAfter(...values:any[]):Query<T>;get():Promise<QuerySnapshot<T>>;count():AggregateQuery<{count:number}>;aggregate(fields:Record<string,AggregateField>):AggregateQuery;onSnapshot(next:(snapshot:QuerySnapshot<T>)=>void,error?:(error:Error)=>void):()=>void;}
export interface DocumentReference<T=DocumentData>{readonly database:MongoDatabase;readonly path:string;readonly id:string;readonly parent:CollectionReference;collection(path:string):CollectionReference;get():Promise<DocumentSnapshot<T>>;set(data:DocumentData,options?:SetOptions):Promise<WriteResult>;create(data:DocumentData):Promise<WriteResult>;update(data:DocumentData,precondition?:Precondition):Promise<WriteResult>;delete(precondition?:Precondition):Promise<WriteResult>;isEqual(other:DocumentReference):boolean;onSnapshot(next:(snapshot:DocumentSnapshot<T>)=>void,error?:(error:Error)=>void):()=>void;}
export interface CollectionReference<T=DocumentData> extends Query<T>{readonly id:string;readonly parent:DocumentReference|null;doc(id?:string):DocumentReference<T>;add(data:DocumentData):Promise<DocumentReference<T>>;}
export interface ReadOptions{fieldMask?:Field[];}
export interface Transaction{get<T>(ref:DocumentReference<T>):Promise<DocumentSnapshot<T>>;get<T>(query:Query<T>):Promise<QuerySnapshot<T>>;getAll(...refs:(DocumentReference|ReadOptions)[]):Promise<DocumentSnapshot[]>;set(ref:DocumentReference,data:DocumentData,options?:SetOptions):this;create(ref:DocumentReference,data:DocumentData):this;update(ref:DocumentReference,data:DocumentData,options?:Precondition):this;delete(ref:DocumentReference,options?:Precondition):this;}
export interface WriteBatch{set(ref:DocumentReference,data:DocumentData,options?:SetOptions):this;create(ref:DocumentReference,data:DocumentData):this;update(ref:DocumentReference,data:DocumentData,options?:Precondition):this;delete(ref:DocumentReference,options?:Precondition):this;commit():Promise<WriteResult[]>;}
export interface MongoDatabase{readonly databaseId:string;collection(path:string):CollectionReference;doc(path:string):DocumentReference;collectionGroup(group:string):Query;getAll(...refs:(DocumentReference|ReadOptions)[]):Promise<DocumentSnapshot[]>;runTransaction<T>(work:(tx:Transaction)=>Promise<T>,options?:{maxAttempts?:number;readOnly?:boolean}):Promise<T>;batch():WriteBatch;terminate():Promise<void>;}
