import {randomBytes} from 'node:crypto';
import {MongoClient,type Db,type ClientSession} from 'mongodb';
import {Timestamp,WriteResult,type Firestore} from 'firebase-admin/firestore';
import {encodeMongoData,decodeMongoData,typeKey} from './mongo-codec.mjs';
type Row=Record<string,any>;
type Order={field:string;direction:1|-1};
const snapshotMetadataProjection=[['_id',1],['_types',1],['_createTime',1],['_updateTime',1],['_createTimestamp',1],['_updateTimestamp',1],['_sourceCreateTime',1],['_sourceUpdateTime',1]] as const;
const name=(field:any):string=>typeof field==='string'?field:Array.isArray(field?.segments)?field.segments.join('.'):(()=>{throw new Error('Unsupported field path');})();
const key=(field:any)=>name(field)==='__name__'?'_id':'data.'+name(field);
const valueAt=(input:any,path:string)=>path.split('.').reduce((v,k)=>v?.[k],input);
function scalar(value:any):any{if(value instanceof MongoDocumentReference)return value.path;return encodeMongoData({v:value}).data.v;}
export function mongoWhere(field:any,op?:string,value?:any):Row{
 if(op===undefined){if(field?.filters){const kind=field.operator==='OR'?'$or':field.operator==='AND'?'$and':null;if(!kind)throw new Error('Unsupported composite filter');return {[kind]:field.filters.map((f:any)=>mongoWhere(f))};}if(field?.operator)return mongoWhere(field.field,field.operator,field.value);throw new Error('Invalid query filter');}
 const k=key(field);if(dateOperand(value))return timestampWhere(field,op!,value);if(Array.isArray(value)&&value.some(dateOperand)){if(['array-contains-any','array-contains'].includes(op!))throw new Error('Timestamp array membership is not supported');if(op==='in')return {$or:value.map(v=>mongoWhere(field,'==',v))};if(op==='not-in')return value.includes(null)?{_id:{$exists:false}}:{$and:[{[k]:{$exists:true,$ne:null}},{$nor:value.map(v=>mongoWhere(field,'==',v))}]};}const v=scalar(value);let condition:Row;
 switch(op){case '==':condition={$eq:v};break;case '!=':condition={$ne:v,$exists:true};break;case '<':condition={$lt:v};break;case '<=':condition={$lte:v};break;case '>':condition={$gt:v};break;case '>=':condition={$gte:v};break;case 'in':condition={$in:v};break;case 'not-in':condition={$nin:v,$exists:true,$ne:null};break;case 'array-contains':condition={$elemMatch:{$eq:v}};break;case 'array-contains-any':condition={$in:v,$type:'array'};break;default:throw new Error('Unsupported query operator '+op);}
 if(op==='not-in'&&v.includes(null))return {_id:{$exists:false}};if(op==='=='&&v===null)condition.$exists=true;return {[k]:condition};
}
class MongoDocumentSnapshot{
 readonly ref:MongoDocumentReference;readonly id:string;readonly exists:boolean;readonly createTime?:Timestamp;readonly updateTime?:Timestamp;readonly readTime=Timestamp.now();private decoded:any;
 constructor(ref:MongoDocumentReference,row?:Row|null){this.ref=ref;this.id=ref.id;this.exists=Boolean(row);if(row){this.decoded=decodeMongoData(row.data,row._types,p=>ref.firestore.doc(p));this.createTime=row._createTimestamp?new Timestamp(row._createTimestamp.seconds,row._createTimestamp.nanos):sourceTimestamp(row._sourceCreateTime,row._createTime);this.updateTime=row._updateTimestamp?new Timestamp(row._updateTimestamp.seconds,row._updateTimestamp.nanos):sourceTimestamp(row._sourceUpdateTime,row._updateTime);}}
 data(){if(!this.exists)return undefined;const encoded=encodeMongoData(this.decoded);return decodeMongoData(encoded.data,encoded.types,p=>this.ref.firestore.doc(p));}get(field:any){const value=valueAt(this.decoded,name(field));if(value===undefined)return undefined;const encoded=encodeMongoData({value});return decodeMongoData(encoded.data,encoded.types,p=>this.ref.firestore.doc(p)).value;}isEqual(other:MongoDocumentSnapshot){return this.ref.path===other.ref.path&&this.updateTime?.isEqual(other.updateTime!);}
}
class MongoQuerySnapshot{
 readonly empty:boolean;readonly size:number;readonly readTime=Timestamp.now();constructor(readonly docs:MongoDocumentSnapshot[],private changes?:any[]){this.empty=!docs.length;this.size=docs.length;}
 forEach(callback:(doc:MongoDocumentSnapshot)=>void){this.docs.forEach(callback);}docChanges(){return this.changes??this.docs.map(doc=>({type:'added',doc,oldIndex:-1,newIndex:this.docs.indexOf(doc)}));}
}
export class MongoDocumentReference{
 readonly id:string;readonly parent:MongoCollectionReference;
 constructor(readonly firestore:MongoNativeDatabase,readonly path:string){const parts=path.split('/');if(parts.length%2||parts.some(p=>!p))throw new Error('Invalid document path');this.id=parts.at(-1)!;this.parent=new MongoCollectionReference(firestore,parts.slice(0,-1).join('/'));}
 collection(path:string){return this.firestore.collection(this.path+'/'+path);}get(){return this.firestore.read(this);}set(data:Row,options?:Row){return this.firestore.write('set',this,data,options);}create(data:Row){return this.firestore.write('create',this,data);}update(data:Row,options?:Row){return this.firestore.write('update',this,data,options);}delete(options?:Row){return this.firestore.write('delete',this,undefined,options);}isEqual(other:any){return other?.path===this.path;}
 onSnapshot(next:(snapshot:any)=>void,error?:(e:any)=>void){return this.firestore.listen(this,next,error);}
}
export class MongoQuery{
 protected filters:Row[]=[];protected orders:Order[]=[];protected maximum?:number;protected skip=0;protected fields?:string[];protected cursor?:any[];
 constructor(readonly firestore:MongoNativeDatabase,readonly path:string,readonly group=false){}
 protected clone(){const q=new MongoQuery(this.firestore,this.path,this.group);q.filters=[...this.filters];q.orders=[...this.orders];q.maximum=this.maximum;q.skip=this.skip;q.fields=this.fields;q.cursor=this.cursor;return q;}
 where(field:any,op?:string,value?:any){const q=this.clone();let converted=field;if(nameSafe(field)==='__name__'&&op&&typeof value==='string'&&!value.includes('/'))value=this.path+'/'+value;else if(nameSafe(field)==='__name__'&&Array.isArray(value))value=value.map(v=>typeof v==='string'&&!v.includes('/')?this.path+'/'+v:v);if(op===undefined)converted=normalizeNameFilter(converted,this.path);q.filters.push(mongoWhere(converted,op,value));return q;}
 orderBy(field:any,direction='asc'){if(!['asc','desc'].includes(direction))throw new Error('Invalid query order');const q=this.clone();q.orders.push({field:name(field),direction:direction==='asc'?1:-1});return q;}
 limit(n:number){if(!Number.isInteger(n)||n<1)throw new Error('Invalid query limit');const q=this.clone();q.maximum=n;return q;}
 offset(n:number){if(!Number.isInteger(n)||n<0)throw new Error('Invalid query offset');const q=this.clone();q.skip=n;return q;}
 select(...fields:any[]){const q=this.clone();q.fields=fields.map(name);return q;}
 startAfter(...values:any[]){const q=this.clone();if(values.length===1&&values[0] instanceof MongoDocumentSnapshot){const row=values[0];q.cursor=q.effectiveOrders().map(o=>o.field==='__name__'?row.ref.path:row.get(o.field));}else{q.cursor=values.map((v,i)=>q.effectiveOrders()[i]?.field==='__name__'&&typeof v==='string'&&!v.includes('/')?this.path+'/'+v:v);}return q;}
 physicalOrders():Order[]{return this.effectiveOrders().flatMap(order=>order.field==='__name__'?[{field:'_id',direction:order.direction}]:[{field:key(order.field),direction:order.direction},{field:'_types.'+typeKey(order.field.split('.'))+'.nanos',direction:order.direction}]);}
 effectiveOrders():Order[]{const orders=this.orders.length?[...this.orders]:[{field:'__name__',direction:1 as const}];if(!orders.some(o=>o.field==='__name__'))orders.push({field:'__name__',direction:orders.at(-1)!.direction});return orders;}
 queryFilter(){const parts:Row[]=[this.group?{_collectionGroup:this.path}:{_collectionPath:this.path},...this.filters];for(const order of this.orders)if(order.field!=='__name__')parts.push({[key(order.field)]:{$exists:true}});if(this.cursor){const orders=this.effectiveOrders();parts.push({$or:this.cursor.map((v,i)=>({$and:[...this.cursor!.slice(0,i).map((p,j)=>mongoWhere(orders[j].field,'==',p)),mongoWhere(orders[i].field,orders[i].direction===1?'>':'<',v)]}))});}return {$and:parts};}
 projection(){if(this.fields===undefined)return undefined;return Object.fromEntries([...snapshotMetadataProjection,...this.fields.filter(f=>f!=='__name__').map(f=>['data.'+f,1])]);}
 async get(session?:ClientSession){const collection=await this.firestore.collectionStore(this.path,this.group);let cursor=collection.find(this.queryFilter(),{session,projection:this.projection()}).sort(Object.fromEntries(this.physicalOrders().map(o=>[o.field,o.direction])));if(this.skip)cursor=cursor.skip(this.skip);if(this.maximum)cursor=cursor.limit(this.maximum);const rows=await cursor.toArray();return new MongoQuerySnapshot(rows.map((row:any)=>new MongoDocumentSnapshot(this.firestore.doc(row._id),row)));}
 count(){return this.aggregate({count:{aggregateType:'count'}});}
 aggregate(spec:Row){return {get:async()=>{const collection=await this.firestore.collectionStore(this.path,this.group),acc:Row={_id:null};for(const [alias,field]of Object.entries(spec)){if(field.aggregateType==='count')acc[alias]={$sum:1};else if(field.aggregateType==='sum')acc[alias]={$sum:'$'+key(field._field)};else if(field.aggregateType==='average')acc[alias]={$avg:'$'+key(field._field)};else throw new Error('Unsupported aggregation');}const pipeline:Row[]=[{$match:this.queryFilter()}];if((this.skip||this.maximum)&&this.orders.length)pipeline.push({$sort:Object.fromEntries(this.physicalOrders().map(o=>[o.field,o.direction]))});if(this.skip)pipeline.push({$skip:this.skip});if(this.maximum)pipeline.push({$limit:this.maximum});pipeline.push({$group:acc});const rows=await collection.aggregate(pipeline).toArray();const data=rows[0]||Object.fromEntries(Object.entries(spec).map(([a,f])=>[a,f.aggregateType==='average'?null:0]));delete data._id;return {data:()=>data};}};}
 onSnapshot(next:(snapshot:any)=>void,error?:(e:any)=>void){return this.firestore.listen(this,next,error);}
}
function nameSafe(field:any){try{return name(field);}catch{return undefined;}}
export class MongoCollectionReference extends MongoQuery{readonly id:string;readonly parent:MongoDocumentReference|null;constructor(db:MongoNativeDatabase,path:string){super(db,path);const p=path.split('/');if(p.length%2!==1||p.some(v=>!v))throw new Error('Invalid collection path');this.id=p.at(-1)!;this.parent=p.length>1?db.doc(p.slice(0,-1).join('/')):null;}doc(id=randomBytes(10).toString('hex')){if(id.includes('/'))throw new Error('Invalid document ID');return this.firestore.doc(this.path+'/'+id);}async add(data:Row){const ref=this.doc();await ref.create(data);return ref;}}
type Mutation={kind:'set'|'create'|'update'|'delete';ref:MongoDocumentReference;data?:Row;options?:Row};
class MongoTransaction{
 writes:Mutation[]=[];readonly reads=new Map<string,MongoDocumentSnapshot>();private pending:Promise<any>=Promise.resolve();constructor(readonly db:MongoNativeDatabase,readonly session:ClientSession){}private serialize<T>(load:()=>Promise<T>){const result=this.pending.then(load);this.pending=result.then(()=>undefined,()=>undefined);return result;}private track<T>(result:T):T{const docs=result instanceof MongoDocumentSnapshot?[result]:result instanceof MongoQuerySnapshot?result.docs:Array.isArray(result)?result:[];for(const doc of docs)this.reads.set(doc.ref.path,doc);return result;}get(ref:MongoDocumentReference):Promise<MongoDocumentSnapshot>;get(ref:MongoQuery):Promise<MongoQuerySnapshot>;get(ref:MongoDocumentReference|MongoQuery){return this.serialize(async()=>this.track(ref instanceof MongoDocumentReference?await this.db.read(ref,this.session):await ref.get(this.session)));}getAll(...refs:any[]){return this.serialize(async()=>this.track(await this.db.readAll(refs,this.session)));}set(ref:MongoDocumentReference,data:Row,options?:Row){this.writes.push({kind:'set',ref,data,options});return this;}create(ref:MongoDocumentReference,data:Row){this.writes.push({kind:'create',ref,data});return this;}update(ref:MongoDocumentReference,data:Row,options?:Row){this.writes.push({kind:'update',ref,data,options});return this;}delete(ref:MongoDocumentReference,options?:Row){this.writes.push({kind:'delete',ref,options});return this;}
}
function resolveTransform(value:any,previous:any,now:Timestamp):any{
 const kind=value?.constructor?.name;
 if(kind==='DeleteTransform')return DELETE;
 if(kind==='ServerTimestampTransform')return now;
 if(kind==='ArrayUnionTransform'){const old=Array.isArray(previous)?[...previous]:[];for(const element of value.elements)if(!old.some(v=>JSON.stringify(encodeMongoData({v}))===JSON.stringify(encodeMongoData({v:element}))))old.push(element);return old;}
 if(kind==='ArrayRemoveTransform')return (Array.isArray(previous)?previous:[]).filter(v=>!value.elements.some((e:any)=>JSON.stringify(encodeMongoData({v}))===JSON.stringify(encodeMongoData({v:e}))));
 if(kind==='NumericIncrementTransform')return (typeof previous==='number'?previous:0)+value.operand;
 if(Array.isArray(value))return value.map((v,i)=>resolveTransform(v,previous?.[i],now));
 if(value&&Object.getPrototypeOf(value)===Object.prototype)return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,resolveTransform(v,previous?.[k],now)]).filter(([,v])=>v!==DELETE));
 return value;
}
const DELETE=Symbol('delete');
function fieldSegments(field:any):string[]{const parts=typeof field==='string'?field.split('.'):Array.isArray(field?.segments)?[...field.segments]:[];if(!parts.length||parts.some(p=>typeof p!=='string'||!p))throw new Error('Invalid database field');return parts;}
function ownValue(input:any,parts:string[]):any{return parts.reduce((value,part)=>value&&Object.hasOwn(value,part)?value[part]:undefined,input);}
function assign(target:Row,path:string|string[],value:any){const parts=Array.isArray(path)?path:fieldSegments(path);let current=target;for(const part of parts.slice(0,-1)){if(!Object.hasOwn(current,part)||!current[part]||Object.getPrototypeOf(current[part])!==Object.prototype)Object.defineProperty(current,part,{value:{},enumerable:true,writable:true,configurable:true});current=current[part];}if(value===DELETE)delete current[parts.at(-1)!];else Object.defineProperty(current,parts.at(-1)!,{value,enumerable:true,writable:true,configurable:true});}
function mergeFields(base:Row,patch:Row,mask:any[],now:Timestamp){if(!Array.isArray(mask))throw new Error('mergeFields must be an array');const fields=mask.map(fieldSegments);for(let i=0;i<fields.length;i++){for(let j=0;j<i;j++)if(fields[i].slice(0,Math.min(fields[i].length,fields[j].length)).every((part,k)=>part===fields[j][k]))throw new Error('Overlapping mergeFields paths');const value=ownValue(patch,fields[i]);if(value===undefined)throw new Error('mergeFields path is missing from data');assign(base,fields[i],resolveTransform(value,ownValue(base,fields[i]),now));}return base;}
function rowUpdateTime(row:Row):Timestamp{return row._updateTimestamp?new Timestamp(row._updateTimestamp.seconds,row._updateTimestamp.nanos):sourceTimestamp(row._sourceUpdateTime,row._updateTime);}
/** One exact logical commit version, valid through nanosecond rollover and clock rollback. */
export function mongoCommitTime(now:Timestamp,previous:Timestamp[]):Timestamp{let result=now;for(const old of previous)if(old.seconds>result.seconds||(old.seconds===result.seconds&&old.nanoseconds>=result.nanoseconds)){const next=old.nanoseconds+1;result=new Timestamp(old.seconds+Math.floor(next/1_000_000_000),next%1_000_000_000);}return result;}
const writeResult=(time:Timestamp)=>Reflect.construct(WriteResult,[time]) as WriteResult;
function mergeMap(base:Row,patch:Row,now:Timestamp){for(const [k,v]of Object.entries(patch)){const previous=base[k],kind=v?.constructor?.name;if(v&&Object.getPrototypeOf(v)===Object.prototype&&Object.keys(v).length&&!kind?.endsWith('Transform')){if(!previous||Object.getPrototypeOf(previous)!==Object.prototype)base[k]={};mergeMap(base[k],v,now);}else{const resolved=resolveTransform(v,previous,now);if(resolved===DELETE)delete base[k];else base[k]=resolved;}}return base;}
export class MongoNativeDatabase{
 private client:MongoClient;private connected?:Promise<Db>;private hubs=new Map<string,{callbacks:Set<(change:any)=>void>;errors:Set<(e:any)=>void>;stream:any;ready:Promise<void>;cancelReady:()=>void}>();
 get databaseId(){return this.databaseName;}terminate(){return this.close();}
 constructor(readonly uri:string,readonly databaseName:string){if(!/^mongodb(?:\+srv)?:\/\//.test(uri)||!databaseName||/[\/\\. "$]/.test(databaseName))throw new Error('Dedicated MongoDB configuration is required');this.client=new MongoClient(uri,{maxPoolSize:10,minPoolSize:0,maxIdleTimeMS:60_000,serverSelectionTimeoutMS:10_000,retryReads:true,retryWrites:true,promoteLongs:false});}
 async database(){return this.connected??=this.client.connect().then(client=>client.db(this.databaseName)).catch(e=>{this.connected=undefined;throw e;});}
 async collectionStore(path:string,group=false){const parts=path.split('/');return (await this.database()).collection<any>(group?path:parts.at(-1)!);}
 collection(path:string){return new MongoCollectionReference(this,path);}doc(path:string){return new MongoDocumentReference(this,path);}collectionGroup(group:string){if(group.includes('/'))throw new Error('Invalid collection group');return new MongoQuery(this,group,true);}
 async read(ref:MongoDocumentReference,session?:ClientSession,fieldMask?:string[]){const store=await this.collectionStore(ref.parent.path),projection=fieldMask?Object.fromEntries([...snapshotMetadataProjection,...fieldMask.map(f=>['data.'+f,1])]):undefined;const row=await store.findOne({_id:ref.path},{session,projection});return new MongoDocumentSnapshot(ref,row);}
 async readAll(input:any[],session?:ClientSession){const options=input.at(-1) instanceof MongoDocumentReference?{}:input.pop()||{};const refs=input as MongoDocumentReference[];if(!refs.length)return [];if(refs.some(r=>!(r instanceof MongoDocumentReference)))throw new Error('Invalid document references');const groups=new Map<string,MongoDocumentReference[]>();for(const ref of refs){const group=ref.parent.id;groups.set(group,[...(groups.get(group)||[]),ref]);}const found=new Map<string,Row>();const projection=options.fieldMask?Object.fromEntries([...snapshotMetadataProjection,...options.fieldMask.map((f:string)=>['data.'+f,1])]):undefined;for(const [group,batch]of groups){const rows=await (await this.database()).collection<any>(group).find({_id:{$in:batch.map(r=>r.path)}},{session,projection}).toArray();for(const row of rows)found.set(row._id,row);}return refs.map(ref=>new MongoDocumentSnapshot(ref,found.get(ref.path)));}
 getAll(...refs:any[]){return this.readAll(refs);}
 async mutate(write:Mutation,session:ClientSession,now:Timestamp,existing:Row|null){const {kind,ref,data,options}=write,store=await this.collectionStore(ref.parent.path);
 if(options?.lastUpdateTime && (!existing || !rowUpdateTime(existing).isEqual(options.lastUpdateTime))){const error:any=new Error('Document update precondition failed');error.code=9;throw error;}
 if(options?.exists!==undefined && Boolean(existing)!==options.exists){const error:any=new Error('Document existence precondition failed');error.code=9;throw error;}
 if(kind==='delete'){await store.deleteOne({_id:ref.path},{session});return null;}
 if(kind==='create'&&existing){const e:any=new Error('Document already exists');e.code=6;throw e;}if(kind==='update'&&!existing){const e:any=new Error('Document not found');e.code=5;throw e;}
 const previous=existing?decodeMongoData(existing.data,existing._types,p=>this.doc(p)):{};let replacement:Row;
 if(kind==='update'){replacement={...previous};for(const [field,value]of Object.entries(data!))assign(replacement,field,resolveTransform(value,valueAt(previous,field),now));}
 else if(options?.mergeFields!==undefined){if(options.merge!==undefined)throw new Error('merge and mergeFields cannot both be specified');replacement=mergeFields({...previous},data!,options.mergeFields,now);}
 else if(options?.merge)replacement=mergeMap({...previous},data!,now);
 else replacement=resolveTransform(data,previous,now);
 const encoded=encodeMongoData(replacement),parts=ref.path.split('/'),time=now.toDate();const row={_id:ref.path,_collectionPath:ref.parent.path,_parentPath:parts.slice(0,-2).join('/'),_collectionGroup:ref.parent.id,data:encoded.data,_types:encoded.types,...Object.fromEntries(Object.entries(existing||{}).filter(([key])=>!['_id','data','_types','_collectionPath','_parentPath','_collectionGroup','_createTime','_updateTime','_updateTimestamp'].includes(key))),_createTime:existing?existing._createTime:time,...(!existing?{_createTimestamp:{seconds:now.seconds,nanos:now.nanoseconds}}:{}),_updateTime:time,_updateTimestamp:{seconds:now.seconds,nanos:now.nanoseconds}};
 if(kind==='create')await store.insertOne(row,{session});else await store.replaceOne({_id:ref.path},row,{session,upsert:kind==='set'});return row;
 }
 async write(kind:Mutation['kind'],ref:MongoDocumentReference,data?:Row,options?:Row){const committed=await this.commitTransaction(async tx=>{tx.writes.push({kind,ref,data,options});});return writeResult(committed.time!);}
 private async commitTransaction<T>(work:(tx:MongoTransaction)=>Promise<T>,options?:{maxAttempts?:number;readOnly?:boolean}):Promise<{output:T;time?:Timestamp}>{await this.database();const session=this.client.startSession();try{let output!:T,time:Timestamp|undefined;await session.withTransaction(async()=>{const tx=new MongoTransaction(this,session);output=await work(tx);time=undefined;if(options?.readOnly&&tx.writes.length)throw new Error('Read-only transactions cannot write');if(!tx.writes.length)return;
 const originals=new Map<string,Row|null>();for(const mutation of tx.writes){if(mutation.ref.firestore!==this)throw new Error('Document belongs to another database');if(!originals.has(mutation.ref.path)){const store=await this.collectionStore(mutation.ref.parent.path);originals.set(mutation.ref.path,await store.findOne({_id:mutation.ref.path},{session}));}}
 time=mongoCommitTime(Timestamp.now(),[...originals.values()].filter((row):row is Row=>Boolean(row)).map(rowUpdateTime));
 for(const snapshot of tx.reads.values()){if(!snapshot.exists)continue;const store=await this.collectionStore(snapshot.ref.parent.path);await store.updateOne({_id:snapshot.ref.path},{$inc:{_transactionFence:1}},{session});}
 for(const mutation of tx.writes)originals.set(mutation.ref.path,await this.mutate(mutation,session,time,originals.get(mutation.ref.path)!));
 },{readConcern:{level:'snapshot'},writeConcern:{w:'majority'},readPreference:'primary'});return {output,time};}finally{await session.endSession();}}
 async runTransaction<T>(work:(tx:MongoTransaction)=>Promise<T>,options?:{maxAttempts?:number;readOnly?:boolean}):Promise<T>{return (await this.commitTransaction(work,options)).output;}
 batch(){const writes:Mutation[]=[];let committed=false;const add=(write:Mutation)=>{if(committed)throw new Error('Cannot modify a committed WriteBatch');writes.push(write);return batch;};const batch:any={set:(ref:MongoDocumentReference,data:Row,options?:Row)=>add({kind:'set',ref,data,options}),create:(ref:MongoDocumentReference,data:Row)=>add({kind:'create',ref,data}),update:(ref:MongoDocumentReference,data:Row,options?:Row)=>add({kind:'update',ref,data,options}),delete:(ref:MongoDocumentReference,options?:Row)=>add({kind:'delete',ref,options}),commit:async()=>{if(committed)throw new Error('WriteBatch was already committed');committed=true;if(!writes.length)return [];const result=await this.commitTransaction(async tx=>{tx.writes.push(...writes);});return writes.map(()=>writeResult(result.time!));}};return batch;}
 listen(source:MongoQuery|MongoDocumentReference,next:(snapshot:any)=>void,error?:(e:any)=>void):()=>void{
 const group=source instanceof MongoDocumentReference?source.parent.id:source.group?source.path:source.path.split('/').at(-1)!;
 let stopped=false,loading=false,again=false,timer:ReturnType<typeof setTimeout>|undefined,previous=new Map<string,MongoDocumentSnapshot>(),initial=true,hub:any;
 const fail=(e:any)=>{if(!stopped){stop();error?.(e);}};
 const load=async()=>{if(stopped)return;if(loading){again=true;return;}loading=true;try{
  const result=await source.get();if(stopped)return;
  if(source instanceof MongoDocumentReference){const snapshot=result as MongoDocumentSnapshot,prior=previous.get(source.path);if(initial||!prior||prior.exists!==snapshot.exists||!prior.updateTime?.isEqual(snapshot.updateTime!)){next(snapshot);previous.set(source.path,snapshot);}}
  else{const rows=(result as MongoQuerySnapshot).docs,current=new Map(rows.map(d=>[d.ref.path,d])),changes:any[]=[];for(const [path,row]of current){const prior=previous.get(path);if(!prior)changes.push({type:'added',doc:row,oldIndex:-1,newIndex:rows.indexOf(row)});else if(!prior.updateTime?.isEqual(row.updateTime!))changes.push({type:'modified',doc:row,oldIndex:[...previous.keys()].indexOf(path),newIndex:rows.indexOf(row)});}for(const [path,row]of previous)if(!current.has(path))changes.push({type:'removed',doc:row,oldIndex:[...previous.keys()].indexOf(path),newIndex:-1});if(initial||changes.length)next(new MongoQuerySnapshot(rows,changes));previous=current;}
  initial=false;
 }catch(e){fail(e);}finally{loading=false;if(again&&!stopped){again=false;void load();}}};
 const change=(event:any)=>{const path=event.documentKey?._id;if(typeof path!=='string')return;let relevant=false;
  if(source instanceof MongoDocumentReference)relevant=source.path===path;
  else{const parent=path.split('/').slice(0,-1).join('/');if(source.group||parent===source.path)relevant=previous.has(path)||!event.fullDocument||mongoEventMatches(event.fullDocument,source.queryFilter());}
  if(relevant&&!timer)timer=setTimeout(()=>{timer=undefined;void load();},75);
 };
 const stop=()=>{stopped=true;if(timer)clearTimeout(timer);if(hub){hub.callbacks.delete(change);hub.errors.delete(fail);if(!hub.callbacks.size){this.hubs.delete(group);hub.cancelReady();void hub.stream.close().catch(()=>{});}}};
 void (async()=>{try{const db=await this.database();if(stopped)return;hub=this.hubs.get(group);if(!hub){const stream=db.collection(group).watch([{$match:{operationType:{$in:['insert','replace','update','delete']},$nor:[{operationType:'update','updateDescription.updatedFields._transactionFence':{$exists:true}}]}}],{fullDocument:'updateLookup',maxAwaitTimeMS:10_000});let resolveReady!:()=>void,rejectReady!:(e:any)=>void;const ready=new Promise<void>((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});const readyTimer=setTimeout(()=>rejectReady(new Error('Mongo realtime initialization timed out')),10_000);void ready.catch(()=>{}).finally(()=>clearTimeout(readyTimer));hub={callbacks:new Set(),errors:new Set(),stream,ready,cancelReady:()=>rejectReady(new Error('Mongo realtime subscription closed'))};this.hubs.set(group,hub);stream.once('resumeTokenChanged',resolveReady);stream.on('change',(event:any)=>{resolveReady();for(const callback of hub.callbacks)callback(event);});stream.on('error',(e:any)=>{rejectReady(e);for(const callback of [...hub.errors])callback(e);});}hub.callbacks.add(change);hub.errors.add(fail);await hub.ready;await load();}catch(e){fail(e);}})();
 return stop;
 }
 async close(){for(const hub of this.hubs.values()){hub.cancelReady();await hub.stream.close();}this.hubs.clear();await this.client.close();this.connected=undefined;}
 asFirestore(){return this as unknown as Firestore;}
}
const instances=new Map<string,MongoNativeDatabase>();
export function getMongoNativeDatabase(){const uri=process.env.MONGODB_URI,database=process.env.MONGODB_DATABASE;if(!uri||!database)throw new Error('Dedicated MongoDB configuration is required');const key=uri+'\0'+database;let instance=instances.get(key);if(!instance){instance=new MongoNativeDatabase(uri,database);instances.set(key,instance);}return instance.asFirestore();}
export async function getMongoDatabase(){const facade=getMongoNativeDatabase() as unknown as MongoNativeDatabase;return facade.database();}

function mongoEventMatches(row:Row,filter:Row):boolean{
 const same=(a:any,b:any):boolean=>a instanceof Date&&b instanceof Date?a.getTime()===b.getTime():JSON.stringify(a)===JSON.stringify(b);
 return Object.entries(filter).every(([field,condition])=>{if(field==='$and')return condition.every((part:Row)=>mongoEventMatches(row,part));if(field==='$or')return condition.some((part:Row)=>mongoEventMatches(row,part));if(field==='$nor')return condition.every((part:Row)=>!mongoEventMatches(row,part));const value=valueAt(row,field);if(!condition||typeof condition!=='object'||condition instanceof Date)return same(value,condition);return Object.entries(condition).every(([op,expected]:[string,any])=>{switch(op){case '$type':return expected==='array'?Array.isArray(value):true;case '$exists':return (value!==undefined)===expected;case '$eq':return same(value,expected);case '$ne':return !same(value,expected);case '$in':return expected.some((v:any)=>Array.isArray(value)?value.some(a=>same(a,v)):same(value,v));case '$nin':return !expected.some((v:any)=>same(value,v));case '$gt':return value>expected;case '$gte':return value>=expected;case '$lt':return value<expected;case '$lte':return value<=expected;case '$elemMatch':return Array.isArray(value)&&value.some(v=>same(v,expected.$eq));default:return true;}});});
}

function normalizeNameFilter(filter:any,path:string):any{if(filter?.filters)return {operator:filter.operator,filters:filter.filters.map((child:any)=>normalizeNameFilter(child,path))};if(nameSafe(filter?.field)!=='__name__')return filter;const normalize=(v:any)=>typeof v==='string'&&!v.includes('/')?path+'/'+v:v;return {field:filter.field,operator:filter.operator,value:Array.isArray(filter.value)?filter.value.map(normalize):normalize(filter.value)};}

function sourceTimestamp(exact:unknown,fallback:unknown):Timestamp{if(typeof exact==='string'){const parsed=new Date(exact);if(Number.isFinite(parsed.getTime())){const fraction=/\.(\d{1,9})Z$/.exec(exact)?.[1]||'';return new Timestamp(Math.floor(parsed.getTime()/1000),Number(fraction.padEnd(9,'0')));}}return Timestamp.fromDate(Object.prototype.toString.call(fallback)==='[object Date]'?fallback as Date:new Date(0));}

function dateOperand(value:any):{date:Date;nanos:number}|null{if(Object.prototype.toString.call(value)==='[object Date]'){const stamp=Timestamp.fromDate(value);return {date:stamp.toDate(),nanos:stamp.nanoseconds};}if(value instanceof Timestamp)return {date:value.toDate(),nanos:value.nanoseconds};return null;}
function timestampWhere(field:any,op:string,value:any):Row{
 const stamp=dateOperand(value)!;if(['array-contains','array-contains-any'].includes(op))throw new Error('Timestamp array membership is not supported');const data=key(field),nano='_types.'+typeKey(name(field).split('.'))+'.nanos',fallback=((stamp.date.getTime()%1000+1000)%1000)*1_000_000;
 const compare=(operator:string,n:number):boolean=>operator==='$eq'?fallback===n:operator==='$gt'?fallback>n:operator==='$gte'?fallback>=n:operator==='$lt'?fallback<n:fallback<=n;
 const nanoCondition=(operator:string)=>compare(operator,stamp.nanos)?{$or:[{[nano]:{[operator]:stamp.nanos}},{[nano]:{$exists:false}}]}:{[nano]:{[operator]:stamp.nanos}};
 const equal={$and:[{[data]:{$eq:stamp.date}},nanoCondition('$eq')]};if(op==='==')return equal;if(op==='!=')return {$and:[{[data]:{$exists:true}},{$nor:[equal]}]};
 const operator=({'>':'$gt','>=':'$gte','<':'$lt','<=':'$lte'} as Record<string,string>)[op];if(!operator)throw new Error('Unsupported timestamp query operator '+op);const strict=operator.startsWith('$g')?'$gt':'$lt';return {$or:[{[data]:{[strict]:stamp.date}},{$and:[{[data]:{$eq:stamp.date}},nanoCondition(operator)]}]};
}
