import fs from 'node:fs';
import dotenv from 'dotenv';
import {spawn} from 'node:child_process';
if(process.env.VERCEL||process.env.NODE_ENV==='production')throw new Error('MongoDB preview is local only');
const read=file=>fs.existsSync(file)?dotenv.parse(fs.readFileSync(file)):{};
const source={...read('.env'),...read('.env.local'),...read('.migration-backups/firebase/native/blob-config.env'),...read('.env.mongodb-migration.local'),...process.env};
if(!source.MONGODB_URI||!source.MONGODB_DATABASE)throw new Error('Set dedicated MONGODB_URI and MONGODB_DATABASE in .env.mongodb-migration.local');
const args=process.argv.slice(2),i=args.findIndex(arg=>arg==='--port'||arg==='-p'),port=(i>=0?args[i+1]:process.env.NATIVE_PREVIEW_PORT)||'3002';
if(!/^\d+$/.test(port)||Number(port)<1||Number(port)>65535)throw new Error('Invalid port');
const origin='http://localhost:'+port;
const env={...source,NODE_ENV:'development',DTPS_NATIVE_PREVIEW:'true',DATABASE_PROVIDER:'mongodb',REDIS_CACHE_ENABLED:'false',REDIS_URL:'',NEXTAUTH_URL:origin,NEXT_PUBLIC_APP_URL:origin,NEXT_PUBLIC_BASE_URL:origin,SMTP_HOST:'',SMTP_USER:'',SMTP_PASS:'',AISENSY_API_KEY:''};
for(const key of Object.keys(env))if(key.startsWith('FIRESTORE_'))delete env[key];
for(const key of ['NEXT_PUBLIC_SOCKET_URL','SOCKET_BROADCAST_URL','SOCKET_INTERNAL_SECRET'])delete env[key];
const child=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--port',port],{env,stdio:'inherit'});
for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>child.kill(signal));
child.on('exit',code=>{process.exitCode=code??1;});
