import test from 'node:test';
import assert from 'node:assert/strict';
import {BSON} from 'mongodb';
import {mongoRecord,sha256,canonical} from './archive.mjs';
import {rowHash,recordMatches,quietHandoff,batchRecords,RECEIPTS} from './journal-target-guard.mjs';
import {applyJournalBatch,targetQuietCheck,verifyJournalBatch} from './journal-apply-core.mjs';
const source={project:'fixture',database:'db'},baselineTime='2026-10-10T10:01:00.000Z',finalTime='2026-10-10T10:05:00.000Z';
const doc=(id,updated=baselineTime)=>({name:`projects/fixture/databases/db/documents/${id}`,createTime:'2026-10-10T10:00:00.123456789Z',updateTime:updated,fields:{stamp:{timestampValue:'2026-10-10T10:00:00.123456789Z'},int:{integerValue:'9223372036854775807'},zero:{doubleValue:'-0'},bytes:{bytesValue:'AQID'},ref:{referenceValue:'projects/fixture/databases/db/documents/users/one'}}});
const round=row=>BSON.deserialize(BSON.serialize(row),{promoteBuffers:true});
function fixture(){const sourceId='fixture/db',baselineRun=sourceId+'@'+baselineTime,run=sourceId+'@'+finalTime+':journal:fixture_epoch:1234';const initial=mongoRecord(doc('users/one'),source,baselineRun),changed=mongoRecord(doc('users/one','2026-10-10T10:03:00.000000001Z'),source,run),orphan=mongoRecord(doc('missing/parent/messages/orphan',finalTime),source,run),removed=mongoRecord(doc('users/deleted'),source,baselineRun),context={source:sourceId,database:'dtps',run,baselineRun,baselineRuns:[baselineRun],runs:[baselineRun,run],baselineReadTime:baselineTime,baselineGroups:{users:2},allowedExtras:[],archiveHash:'a'.repeat(64)},batch={index:0,hash:'b'.repeat(64)},records={changed:[changed,orphan],deleted:[{path:removed._id}]};return {initial,changed,orphan,removed,context,batch,records};}
function matches(row,query){return Object.entries(query).every(([k,v])=>{const value=k.split('.').reduce((r,p)=>r?.[p],row);if(v&&typeof v==='object'&&!(v instanceof Date)){if('$in'in v)return v.$in.includes(value);if('$nin'in v)return !v.$nin.includes(value);if('$ne'in v)return value!==v.$ne;if('$gt'in v)return value>v.$gt;}return value instanceof Date&&v instanceof Date?value.getTime()===v.getTime():value===v;});}
function fakeMongo(rows){let data=new Map(),failAfterOps=false;for(const r of rows){const coll=r._collectionGroup||RECEIPTS;const bank=data.get(coll)||new Map();bank.set(r._id,round(r));data.set(coll,bank);}const get=name=>{if(!data.has(name))data.set(name,new Map());return data.get(name);};const db={collection(name){return {aggregate(){const grouped=new Map();for(const r of get(name).values()){const key=JSON.stringify([r._migrationSource,r._migrationRun]),old=grouped.get(key)||{_id:{source:r._migrationSource,run:r._migrationRun},count:0,maxUpdate:null};old.count++;if(r._updateTime>old.maxUpdate)old.maxUpdate=r._updateTime;grouped.set(key,old);}return {toArray:async()=>[...grouped.values()]};},find(q={}){const found=()=>[...get(name).values()].filter(r=>matches(r,q)).map(round);return {toArray:async()=>found(),async *[Symbol.asyncIterator](){yield*found();}};},findOne:async q=>roundOrNull([...get(name).values()].find(r=>matches(r,q))),countDocuments:async q=>[...get(name).values()].filter(r=>matches(r,q)).length,insertOne:async row=>{if(get(name).has(row._id))throw new Error('duplicate');get(name).set(row._id,round(row));return {insertedId:row._id};},bulkWrite:async ops=>{let matchedCount=0,deletedCount=0,insertedCount=0;for(const op of ops){if(op.insertOne){insertedCount++;const r=op.insertOne.document;if(get(name).has(r._id))throw new Error('duplicate');get(name).set(r._id,round(r));}else{const item=op.replaceOne||op.deleteOne,previous=[...get(name).values()].find(r=>matches(r,item.filter));if(previous){if(op.replaceOne){matchedCount++;get(name).set(previous._id,round(item.replacement));}else{deletedCount++;get(name).delete(previous._id);}}}}if(failAfterOps)throw new Error('injected transaction failure');return {matchedCount,deletedCount,insertedCount};}};},listCollections(){return {toArray:async()=>[...data.keys()].map(name=>({name}))};}};function roundOrNull(r){return r?round(r):null;}const client={startSession(){return {async withTransaction(fn){const snapshot=new Map([...data].map(([k,m])=>[k,new Map([...m].map(([id,r])=>[id,round(r)]))]));try{await fn();}catch(e){data=snapshot;throw e;}},async endSession(){}};}};return {db,client,fail(value){failAfterOps=value;}};}
test('typed journal replacement preserves BSON int64, bytes, reference, exact nanos and orphan path',()=>{const {changed,orphan,context}=fixture(),actual=round(changed);assert(recordMatches(actual,changed,[context.run]));assert.equal(rowHash(actual),rowHash(changed));assert(Object.is(actual.data.zero,-0));assert.equal(actual.data.int.toString(),'9223372036854775807');assert.equal(actual._updateTimestamp.nanos,1);assert.equal(orphan._parentPath,'missing/parent');actual._updateTimestamp.nanos=2;assert(!recordMatches(actual,changed,[context.run]));});
test('atomic apply receipts resume without duplicating inserts/deletes and extend complete baseline counts',async()=>{const {initial,removed,context,batch,records}=fixture(),fake=fakeMongo([initial,removed]),hashes=new Map(records.changed.map(r=>[r._id,rowHash(r)]));await targetQuietCheck(fake.db,context,[batch],hashes);const first=await applyJournalBatch(fake.client,fake.db,batch,records,context);assert.deepEqual(first.inserted,{messages:1});assert.deepEqual(first.deleted,{users:1});assert.deepEqual(first.updated,{users:1});assert.deepEqual(await applyJournalBatch(fake.client,fake.db,batch,records,context),first);assert.deepEqual(await verifyJournalBatch(fake.db,records,context),{verified:2,tombstones:1});assert.deepEqual(await targetQuietCheck(fake.db,context,[batch],hashes),{receipts:1,counts:{users:1,messages:1}});});
test('failed transaction leaves no partial business change or receipt; resumed attempt succeeds',async()=>{const {initial,removed,context,batch,records}=fixture(),fake=fakeMongo([initial,removed]);fake.fail(true);await assert.rejects(applyJournalBatch(fake.client,fake.db,batch,records,context),/injected/);assert.equal(await fake.db.collection(RECEIPTS).countDocuments({}),0);assert.equal(rowHash(await fake.db.collection('users').findOne({_id:initial._id})),rowHash(initial));assert(await fake.db.collection('users').findOne({_id:removed._id}));fake.fail(false);await applyJournalBatch(fake.client,fake.db,batch,records,context);assert.equal((await verifyJournalBatch(fake.db,records,context)).verified,2);});
test('preview drift, modified hashes and unrelated target collisions fail without deletion',async()=>{const {initial,removed,context,batch,records}=fixture(),drift=round(initial);drift._updateTime=new Date(finalTime);const fake=fakeMongo([drift,removed]);await assert.rejects(targetQuietCheck(fake.db,context,[batch],new Map()),/preview/);const corrupt=round(initial);corrupt.data.changed=true;const other=fakeMongo([corrupt,removed]);await assert.rejects(applyJournalBatch(other.client,other.db,batch,records,context),/unchanged/);assert.equal(await other.db.collection(RECEIPTS).countDocuments({}),0);const unrelated={_id:records.changed[0]._id,_collectionGroup:'users',data:{unrelated:true}},collision=fakeMongo([unrelated,removed]);await assert.rejects(applyJournalBatch(collision.client,collision.db,batch,records,context),/collision/);assert.deepEqual((await collision.db.collection('users').findOne({_id:unrelated._id})).data,{unrelated:true});});
test('exact approved nonimported operational registration survives matching source tombstone',async()=>{const {initial,removed,context,batch,records}=fixture(),extra={_id:'_nativeFcmTokens/retained',_collectionGroup:'_nativeFcmTokens',data:{registration:'private-fixture'}},ctx={...context,allowedExtras:[{collection:extra._collectionGroup,id:extra._id,hash:rowHash(extra)}]},fake=fakeMongo([initial,removed,extra]),states={...records,deleted:[...records.deleted,{path:extra._id}]};await targetQuietCheck(fake.db,ctx,[batch],new Map());const receipt=await applyJournalBatch(fake.client,fake.db,batch,states,ctx);assert.equal(receipt.retainedOperational,1);assert.equal(rowHash(await fake.db.collection(extra._collectionGroup).findOne({_id:extra._id})),rowHash(extra));await targetQuietCheck(fake.db,ctx,[batch],new Map(records.changed.map(r=>[r._id,rowHash(r)])));});
function handoffFixture(){const sourceId='fixture/db',files=[{file:'full.gz',sha256:'a'.repeat(64),records:2}],run=sourceId+'@'+baselineTime;const archive={sha256:'c'.repeat(64),baselineProofSha256:'d'.repeat(64),manifest:{completedAt:'2026-10-10T10:06:00Z',identity:{source,epoch:'fixture_epoch',baselineReadTime:baselineTime,readTime:finalTime,final:true,writeGateTime:'2026-10-10T10:04:59Z',baselineFiles:files}}},proof={complete:true,database:'dtps',source:sourceId,run,acceptedRuns:[run],readTime:baselineTime,startedAt:'2026-10-10T10:02:00Z',completedAt:'2026-10-10T10:03:00Z',verified:2,groups:{users:2},archiveFiles:files,excludeMigrationArchives:false},quiet={complete:true,database:'dtps',source:sourceId,epoch:'fixture_epoch',baselineRun:run,baselineVerificationSha256:archive.baselineProofSha256,targetWritersGated:true,deviationAuditComplete:true,deviations:0,untrackedWrites:0,quietSince:'2026-10-10T10:01:01Z',checkedAt:'2026-10-10T10:07:00Z',allowedNonImported:[]};return {archive,proof,quiet};}
test('target handoff rejects stale initial proof, nonfinal source, ungated/late quiet interval, deviation and wrong database',()=>{const {archive,proof,quiet}=handoffFixture();assert.equal(quietHandoff(archive,proof,quiet,'dtps',false).baselineRun,proof.run);for(const dirty of [{...quiet,targetWritersGated:false},{...quiet,untrackedWrites:1},{...quiet,quietSince:'2026-10-10T10:02:01Z'},{...quiet,checkedAt:'2026-10-10T10:05:59Z'}])assert.throws(()=>quietHandoff(archive,proof,dirty,'dtps',false),/quiet/);assert.throws(()=>quietHandoff(archive,{...proof,startedAt:undefined},quiet,'dtps',false),/New complete/);assert.throws(()=>quietHandoff(archive,{...proof,startedAt:'invalid'},quiet,'dtps',false),/time/);assert.throws(()=>quietHandoff(archive,proof,quiet,'dtps_website',false),/New complete/);assert.throws(()=>quietHandoff({...archive,manifest:{...archive.manifest,identity:{...archive.manifest.identity,final:false}}},proof,quiet,'dtps',false),/New complete/);});
test('archive-only exact root exclusion preserves similarly named nested business states',()=>{const {context}=fixture(),typed={changed:[doc('_nativeMigrationJournal/a'),doc('users/a/_nativeMigrationJournalNotes/child'),doc('_nativeMigrationJournalNotes/root')],deleted:[{path:'_nativeMigrationJournalCounters/a'},{path:'users/a/_nativeMigrationJournalCounters/child'}]},result=batchRecords(typed,{...context,exclude:true},source);assert.equal(result.changed.length,2);assert.equal(result.deleted.length,1);});
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {gzipSync} from 'node:zlib';
import {execFileSync} from 'node:child_process';
import {fileHash} from './archive.mjs';
import {journalArchive} from './journal-target-guard.mjs';
import {resource,eventId,counterId,SHARDS,JOURNAL,COUNTERS} from './journal-guard.mjs';
test('complete journal local-only apply/verify previews recheck typed chunks, counter atomicity and proof hashes without credentials',async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dtps-journal-target-'));try{
  const {archive,proof,quiet}=handoffFixture(),epoch='fixture_epoch',activatedAt='2026-10-10T10:00:00Z',commit='2026-10-10T10:03:00.123456789Z',paths=['missing/parent/messages/orphan','users/deleted'],activation={...source,complete:true,epoch,coverageConfirmed:true,activatedAt,readTime:activatedAt,vector:Array(SHARDS).fill(0),missingCounterShards:[]},end={...source,complete:true,epoch,readTime:finalTime,vector:Array(SHARDS).fill(0),writersGated:true,writeGateTime:archive.manifest.identity.writeGateTime};end.vector[3]=1;
  const fields=(s,seq)=>({epoch:{stringValue:epoch},shard:{integerValue:String(s)},seq:{integerValue:String(seq)},sourceProject:{stringValue:source.project},sourceDatabase:{stringValue:source.database}}),events=[{name:resource(source,`${JOURNAL}/${eventId(epoch,3,1)}`),createTime:commit,updateTime:commit,fields:{...fields(3,1),paths:{arrayValue:{values:paths.map(stringValue=>({stringValue}))}},committedAt:{timestampValue:'2026-10-10T10:03:00.123Z'}}}],counters=p=>Array.from({length:SHARDS},(_,s)=>({found:{name:resource(source,`${COUNTERS}/${counterId(epoch,s)}`),createTime:activatedAt,updateTime:p.vector[s]?commit:activatedAt,fields:fields(s,p.vector[s])}}));
  async function gz(name,rows){const buffer=gzipSync(rows.map(r=>JSON.stringify(r)).join('\n')+(rows.length?'\n':''));await fs.writeFile(path.join(dir,name),buffer);return {file:name,sha256:sha256(buffer),records:rows.length};}
  async function json(name,obj){const file=path.join(dir,name);await fs.writeFile(file,JSON.stringify(obj));return file;}
  const a=await json('activation.json',activation),e=await json('end.json',end),b=await json('baseline-verification.json',proof);quiet.baselineVerificationSha256=await fileHash(b);const q=await json('target-quiet.json',quiet),changed=[doc(paths[0],commit)],deleted=[{path:paths[1]}],eventChunk={...await gz('events-3.gz',events),shard:3,start:1,stop:1},stateChunk={pathsSha256:sha256(JSON.stringify(paths)),changed:await gz('state.changed.gz',changed),deleted:await gz('state.deleted.gz',deleted)},manifest={...archive.manifest,format:'DTPS journal typed delta v1',complete:true,events:1,paths:2,changed:1,deleted:1,counters:{start:await gz('counters-start.gz',counters(activation)),end:await gz('counters-end.gz',counters(end))},eventChunks:[eventChunk],stateChunks:[stateChunk],files:[await gz('changed.jsonl.gz',changed),await gz('deleted.jsonl.gz',deleted),await gz('journal-events.jsonl.gz',events)]};Object.assign(manifest.identity,{activationSha256:await fileHash(a),endSha256:await fileHash(e),vectorStart:activation.vector,vectorEnd:end.vector});await json('journal-manifest.json',manifest);
  assert.equal((await journalArchive(dir,a,e)).batches.length,1);const args=['--archive',dir,'--activation-proof',a,'--end-vector',e,'--baseline-verification',b,'--target-quiet-proof',q],env={...process.env};delete env.MONGODB_URI;delete env.MONGODB_DATABASE;
  for(const cli of ['apply-journal.mjs','verify-journal.mjs']){const result=JSON.parse(execFileSync(process.execPath,[path.resolve('tools/mongodb-migration',cli),...args],{encoding:'utf8',env}));assert(result.dryRun);assert.equal(result.changed,1);assert.equal(result.deleted,1);}
  assert.throws(()=>execFileSync(process.execPath,[path.resolve('tools/mongodb-migration/apply-journal.mjs'),...args,'--execute','--writers-gated','--parent-approved-handoff'],{stdio:'pipe',env}),/Command failed/);await assert.rejects(fs.stat(path.join(dir,'mongo-journal-apply-dtps.json')));
  const badCounters=counters(end);badCounters[3].found.updateTime='2026-10-10T10:03:00.123456788Z';manifest.counters.end=await gz('counters-end.gz',badCounters);await json('journal-manifest.json',manifest);await assert.rejects(journalArchive(dir,a,e),/atomic commit/);
 }finally{await fs.rm(dir,{recursive:true,force:true});}
});
import {baselineSyncArchive,baselineSyncBatches} from './baseline-sync-guard.mjs';
test('offline-target baseline path is nonfinal, covered after W0, and streams guarded typed changes/deletes while source remains live',async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dtps-offline-baseline-'));try{
  const {archive,proof,quiet}=handoffFixture(),epoch='fixture_epoch',activation={...source,complete:true,epoch,coverageConfirmed:true,activatedAt:'2026-10-10T10:02:00Z',readTime:'2026-10-10T10:02:00Z',vector:Array(SHARDS).fill(0),missingCounterShards:[]};
  async function gz(file,rows){const bytes=gzipSync(rows.map(r=>JSON.stringify(r)).join('\n')+'\n');await fs.writeFile(path.join(dir,file),bytes);return {file,records:rows.length,sha256:sha256(bytes)};}
  const updates=[doc('users/one',finalTime),doc('missing/parent/messages/orphan',finalTime)],deletes=[{path:'users/deleted'}],full=[...updates],manifest={...source,complete:true,readTime:finalTime,baselineReadTime:baselineTime,baselineFiles:proof.archiveFiles,finalCutover:false,bootstrapIncomplete:false,completedAt:'2026-10-10T10:06:00Z',documents:2,changedDocuments:2,deletedDocuments:1,files:[await gz('full.gz',full)],deltaFiles:[await gz('changed.jsonl.gz',updates),await gz('deleted.jsonl.gz',deletes),await gz('metadata.jsonl.gz',[])]},activationFile=path.join(dir,'activation.json');await fs.writeFile(activationFile,JSON.stringify(activation));await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify(manifest));const checked=await baselineSyncArchive(dir,activationFile),batches=[];for await(const batch of baselineSyncBatches(dir,checked))batches.push(batch);assert.equal(batches.length,2);assert.equal(batches[0].typed.changed.length,2);assert.equal(batches[1].typed.deleted.length,1);checked.baselineProofSha256=archive.baselineProofSha256;const context=quietHandoff(checked,proof,quiet,'dtps',false,true);assert.equal(context.run,'fixture/db@'+finalTime);assert.equal(context.receiptCollection,'_nativeMigrationJournalBaselineApply');assert.throws(()=>quietHandoff(checked,proof,quiet,'dtps',false),/New complete/);
  const baselineFile=path.join(dir,'proof.json'),quietFile=path.join(dir,'quiet.json');await fs.writeFile(baselineFile,JSON.stringify(proof));quiet.baselineVerificationSha256=await fileHash(baselineFile);await fs.writeFile(quietFile,JSON.stringify(quiet));const env={...process.env};delete env.MONGODB_URI;delete env.MONGODB_DATABASE;const result=JSON.parse(execFileSync(process.execPath,[path.resolve('tools/mongodb-migration/sync-baseline.mjs'),'--archive',dir,'--activation-proof',activationFile,'--baseline-verification',baselineFile,'--target-quiet-proof',quietFile],{env,encoding:'utf8'}));assert(result.dryRun);assert(result.sourceRemainsLive);assert.equal(result.finalCutover,false);assert.equal(result.changed,2);assert.equal(result.deleted,1);
  await fs.writeFile(activationFile,JSON.stringify({...activation,readTime:'2026-10-10T10:06:00Z'}));await assert.rejects(baselineSyncArchive(dir,activationFile),/Preactivation/);
 }finally{await fs.rm(dir,{recursive:true,force:true});}
});
test('previous baseline sync receipts are preserved only with exact explicit control hashes at final handoff',async()=>{const {initial,removed,context,batch,records}=fixture(),fake=fakeMongo([initial,removed]),baselineContext={...context,receiptCollection:'_nativeMigrationJournalBaselineApply'};const receipt=await applyJournalBatch(fake.client,fake.db,batch,records,baselineContext);const laterContext={...context,run:context.run+'-later',baselineGroups:{users:1,messages:1},baselineRuns:[context.run],runs:[context.run,context.run+'-later'],baselineReadTime:finalTime};await assert.rejects(targetQuietCheck(fake.db,laterContext,[],new Map()),/Unreviewed prior/);laterContext.controlExtras=[{collection:'_nativeMigrationJournalBaselineApply',id:receipt._id,hash:rowHash(receipt)}];assert.equal((await targetQuietCheck(fake.db,laterContext,[],new Map())).receipts,0);});
test('real local replica transactions atomically apply and concurrently resume journal batch with native BSON and read-only preflight',async()=>{
 if(process.env.VERCEL||process.env.NODE_ENV==='production')throw new Error('Local replica fixture forbidden in production');
 const {MongoMemoryReplSet}=await import('mongodb-memory-server'),{MongoClient}=await import('mongodb'),replica=await MongoMemoryReplSet.create({replSet:{count:1},instanceOpts:[{storageEngine:'wiredTiger'}]});const uri=replica.getUri('dtps_fixture');assert.equal(new URL(uri).hostname,'127.0.0.1');const client=new MongoClient(uri,{promoteBuffers:true});
 try{await client.connect();const db=client.db('dtps_fixture'),{initial,removed,context,batch,records}=fixture();await db.collection('users').insertMany([initial,removed]);const hashes=new Map(records.changed.map(r=>[r._id,rowHash(r)]));await targetQuietCheck(db,context,[batch],hashes);const receipts=await Promise.all([applyJournalBatch(client,db,batch,records,context),applyJournalBatch(client,db,batch,records,context)]);assert.equal(receipts[0]._id,receipts[1]._id);assert.equal(await db.collection(RECEIPTS).countDocuments({}),1);assert.deepEqual(await verifyJournalBatch(db,records,context),{verified:2,tombstones:1});assert.deepEqual(await targetQuietCheck(db,context,[batch],hashes),{receipts:1,counts:{users:1,messages:1}});
 }finally{await client.close();await replica.stop();}
});
test('baseline deviation audit rejects execution and unapproved host before any output or target access',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dtps-audit-guard-')),out=path.join(dir,'output');try{const cli=path.resolve('tools/mongodb-migration/audit-baseline.mjs');assert.throws(()=>execFileSync(process.execPath,[cli,'--execute','--output',out],{stdio:'pipe'}),/Command failed/);const env={...process.env,MONGODB_URI:'mongodb+srv://user:fixture@wrong.invalid/dtps'};assert.throws(()=>execFileSync(process.execPath,[cli,'--archive',dir,'--output',out],{env,stdio:'pipe'}),/Command failed/);await assert.rejects(fs.stat(out));}finally{await fs.rm(dir,{recursive:true,force:true});}});
