export type CountryCodeEntry = {
  code: string;
  flag: string;
  country: string;
};

export const COUNTRY_CODES: CountryCodeEntry[] = [
  { code: '+93', flag: '🇦🇫', country: 'Afghanistan' },
  { code: '+355', flag: '🇦🇱', country: 'Albania' },
  { code: '+213', flag: '🇩🇿', country: 'Algeria' },
  { code: '+1', flag: '🇦🇸', country: 'American Samoa' },
  { code: '+376', flag: '🇦🇩', country: 'Andorra' },
  { code: '+244', flag: '🇦🇴', country: 'Angola' },
  { code: '+1', flag: '🇦🇮', country: 'Anguilla' },
  { code: '+1', flag: '🇦🇬', country: 'Antigua and Barbuda' },
  { code: '+54', flag: '🇦🇷', country: 'Argentina' },
  { code: '+374', flag: '🇦🇲', country: 'Armenia' },
  { code: '+297', flag: '🇦🇼', country: 'Aruba' },
  { code: '+61', flag: '🇦🇺', country: 'Australia' },
  { code: '+43', flag: '🇦🇹', country: 'Austria' },
  { code: '+994', flag: '🇦🇿', country: 'Azerbaijan' },
  { code: '+1', flag: '🇧🇸', country: 'Bahamas' },
  { code: '+973', flag: '🇧🇭', country: 'Bahrain' },
  { code: '+880', flag: '🇧🇩', country: 'Bangladesh' },
  { code: '+1', flag: '🇧🇧', country: 'Barbados' },
  { code: '+375', flag: '🇧🇾', country: 'Belarus' },
  { code: '+32', flag: '🇧🇪', country: 'Belgium' },
  { code: '+501', flag: '🇧🇿', country: 'Belize' },
  { code: '+229', flag: '🇧🇯', country: 'Benin' },
  { code: '+1', flag: '🇧🇲', country: 'Bermuda' },
  { code: '+975', flag: '🇧🇹', country: 'Bhutan' },
  { code: '+591', flag: '🇧🇴', country: 'Bolivia' },

  { code: '+387', flag: '🇧🇦', country: 'Bosnia and Herzegovina' },
  { code: '+267', flag: '🇧🇼', country: 'Botswana' },
  { code: '+55', flag: '🇧🇷', country: 'Brazil' },
  { code: '+246', flag: '🇮🇴', country: 'British Indian Ocean Territory' },
  { code: '+1', flag: '🇻🇬', country: 'British Virgin Islands' },
  { code: '+673', flag: '🇧🇳', country: 'Brunei' },
  { code: '+359', flag: '🇧🇬', country: 'Bulgaria' },
  { code: '+226', flag: '🇧🇫', country: 'Burkina Faso' },
  { code: '+257', flag: '🇧🇮', country: 'Burundi' },
  { code: '+855', flag: '🇰🇭', country: 'Cambodia' },
  { code: '+237', flag: '🇨🇲', country: 'Cameroon' },
  { code: '+1', flag: '🇨🇦', country: 'Canada' },
  { code: '+238', flag: '🇨🇻', country: 'Cape Verde' },
  { code: '+1', flag: '🇰🇾', country: 'Cayman Islands' },
  { code: '+236', flag: '🇨🇫', country: 'Central African Republic' },
  { code: '+235', flag: '🇹🇩', country: 'Chad' },
  { code: '+56', flag: '🇨🇱', country: 'Chile' },
  { code: '+86', flag: '🇨🇳', country: 'China' },
  { code: '+57', flag: '🇨🇴', country: 'Colombia' },
  { code: '+269', flag: '🇰🇲', country: 'Comoros' },
  { code: '+682', flag: '🇨🇰', country: 'Cook Islands' },
  { code: '+506', flag: '🇨🇷', country: 'Costa Rica' },
  { code: '+385', flag: '🇭🇷', country: 'Croatia' },
  { code: '+53', flag: '🇨🇺', country: 'Cuba' },
  { code: '+599', flag: '🇨🇼', country: 'Curacao' },
  { code: '+357', flag: '🇨🇾', country: 'Cyprus' },
  { code: '+420', flag: '🇨🇿', country: 'Czech Republic' },
  { code: '+243', flag: '🇨🇩', country: 'Democratic Republic of the Congo' },
  { code: '+45', flag: '🇩🇰', country: 'Denmark' },
  { code: '+253', flag: '🇩🇯', country: 'Djibouti' },
  { code: '+1', flag: '🇩🇲', country: 'Dominica' },
  { code: '+1', flag: '🇩🇴', country: 'Dominican Republic' },
  { code: '+670', flag: '🇹🇱', country: 'East Timor' },
  { code: '+593', flag: '🇪🇨', country: 'Ecuador' },
  { code: '+20', flag: '🇪🇬', country: 'Egypt' },
  { code: '+503', flag: '🇸🇻', country: 'El Salvador' },
  { code: '+240', flag: '🇬🇶', country: 'Equatorial Guinea' },
  { code: '+291', flag: '🇪🇷', country: 'Eritrea' },
  { code: '+372', flag: '🇪🇪', country: 'Estonia' },
  { code: '+268', flag: '🇸🇿', country: 'Eswatini' },
  { code: '+251', flag: '🇪🇹', country: 'Ethiopia' },
  { code: '+500', flag: '🇫🇰', country: 'Falkland Islands' },
  { code: '+298', flag: '🇫🇴', country: 'Faroe Islands' },
  { code: '+679', flag: '🇫🇯', country: 'Fiji' },
  { code: '+358', flag: '🇫🇮', country: 'Finland' },
  { code: '+33', flag: '🇫🇷', country: 'France' },
  { code: '+689', flag: '🇵🇫', country: 'French Polynesia' },
  { code: '+241', flag: '🇬🇦', country: 'Gabon' },
  { code: '+220', flag: '🇬🇲', country: 'Gambia' },
  { code: '+995', flag: '🇬🇪', country: 'Georgia' },
  { code: '+49', flag: '🇩🇪', country: 'Germany' },
  { code: '+233', flag: '🇬🇭', country: 'Ghana' },
  { code: '+350', flag: '🇬🇮', country: 'Gibraltar' },
  { code: '+30', flag: '🇬🇷', country: 'Greece' },
  { code: '+299', flag: '🇬🇱', country: 'Greenland' },
  { code: '+1', flag: '🇬🇩', country: 'Grenada' },
  { code: '+1', flag: '🇬🇺', country: 'Guam' },
  { code: '+502', flag: '🇬🇹', country: 'Guatemala' },
  { code: '+44', flag: '🇬🇬', country: 'Guernsey' },
  { code: '+224', flag: '🇬🇳', country: 'Guinea' },
  { code: '+245', flag: '🇬🇼', country: 'Guinea-Bissau' },
  { code: '+592', flag: '🇬🇾', country: 'Guyana' },
  { code: '+509', flag: '🇭🇹', country: 'Haiti' },
  { code: '+504', flag: '🇭🇳', country: 'Honduras' },
  { code: '+852', flag: '🇭🇰', country: 'Hong Kong' },
  { code: '+36', flag: '🇭🇺', country: 'Hungary' },
  { code: '+354', flag: '🇮🇸', country: 'Iceland' },
  { code: '+91', flag: '🇮🇳', country: 'India' },
  { code: '+62', flag: '🇮🇩', country: 'Indonesia' },
  { code: '+98', flag: '🇮🇷', country: 'Iran' },
  { code: '+964', flag: '🇮🇶', country: 'Iraq' },
  { code: '+353', flag: '🇮🇪', country: 'Ireland' },
  { code: '+44', flag: '🇮🇲', country: 'Isle of Man' },
  { code: '+972', flag: '🇮🇱', country: 'Israel' },
  { code: '+39', flag: '🇮🇹', country: 'Italy' },
  { code: '+225', flag: '🇨🇮', country: 'Ivory Coast' },
  { code: '+1', flag: '🇯🇲', country: 'Jamaica' },
  { code: '+81', flag: '🇯🇵', country: 'Japan' },
  { code: '+44', flag: '🇯🇪', country: 'Jersey' },
  { code: '+962', flag: '🇯🇴', country: 'Jordan' },
  { code: '+7', flag: '🇰🇿', country: 'Kazakhstan' },
  { code: '+254', flag: '🇰🇪', country: 'Kenya' },
  { code: '+686', flag: '🇰🇮', country: 'Kiribati' },
  { code: '+383', flag: '🇽🇰', country: 'Kosovo' },
  { code: '+965', flag: '🇰🇼', country: 'Kuwait' },
  { code: '+996', flag: '🇰🇬', country: 'Kyrgyzstan' },
  { code: '+856', flag: '🇱🇦', country: 'Laos' },
  { code: '+371', flag: '🇱🇻', country: 'Latvia' },
  { code: '+961', flag: '🇱🇧', country: 'Lebanon' },
  { code: '+266', flag: '🇱🇸', country: 'Lesotho' },
  { code: '+231', flag: '🇱🇷', country: 'Liberia' },
  { code: '+218', flag: '🇱🇾', country: 'Libya' },
  { code: '+423', flag: '🇱🇮', country: 'Liechtenstein' },
  { code: '+370', flag: '🇱🇹', country: 'Lithuania' },
  { code: '+352', flag: '🇱🇺', country: 'Luxembourg' },
  { code: '+853', flag: '🇲🇴', country: 'Macau' },
  { code: '+389', flag: '🇲🇰', country: 'North Macedonia' },
  { code: '+261', flag: '🇲🇬', country: 'Madagascar' },
  { code: '+265', flag: '🇲🇼', country: 'Malawi' },
  { code: '+60', flag: '🇲🇾', country: 'Malaysia' },
  { code: '+960', flag: '🇲🇻', country: 'Maldives' },
  { code: '+223', flag: '🇲🇱', country: 'Mali' },
  { code: '+356', flag: '🇲🇹', country: 'Malta' },
  { code: '+692', flag: '🇲🇭', country: 'Marshall Islands' },
  { code: '+222', flag: '🇲🇷', country: 'Mauritania' },
  { code: '+230', flag: '🇲🇺', country: 'Mauritius' },
  { code: '+262', flag: '🇾🇹', country: 'Mayotte' },
  { code: '+52', flag: '🇲🇽', country: 'Mexico' },
  { code: '+691', flag: '🇫🇲', country: 'Micronesia' },
  { code: '+373', flag: '🇲🇩', country: 'Moldova' },
  { code: '+377', flag: '🇲🇨', country: 'Monaco' },
  { code: '+976', flag: '🇲🇳', country: 'Mongolia' },
  { code: '+382', flag: '🇲🇪', country: 'Montenegro' },
  { code: '+1', flag: '🇲🇸', country: 'Montserrat' },
  { code: '+212', flag: '🇲🇦', country: 'Morocco' },
  { code: '+258', flag: '🇲🇿', country: 'Mozambique' },
  { code: '+95', flag: '🇲🇲', country: 'Myanmar' },
  { code: '+264', flag: '🇳🇦', country: 'Namibia' },
  { code: '+674', flag: '🇳🇷', country: 'Nauru' },
  { code: '+977', flag: '🇳🇵', country: 'Nepal' },
  { code: '+31', flag: '🇳🇱', country: 'Netherlands' },
  { code: '+599', flag: '🇧🇶', country: 'Caribbean Netherlands' },
  { code: '+687', flag: '🇳🇨', country: 'New Caledonia' },
  { code: '+64', flag: '🇳🇿', country: 'New Zealand' },
  { code: '+505', flag: '🇳🇮', country: 'Nicaragua' },
  { code: '+227', flag: '🇳🇪', country: 'Niger' },
  { code: '+234', flag: '🇳🇬', country: 'Nigeria' },
  { code: '+683', flag: '🇳🇺', country: 'Niue' },
  { code: '+850', flag: '🇰🇵', country: 'North Korea' },
  { code: '+1', flag: '🇲🇵', country: 'Northern Mariana Islands' },
  { code: '+47', flag: '🇳🇴', country: 'Norway' },
  { code: '+968', flag: '🇴🇲', country: 'Oman' },
  { code: '+92', flag: '🇵🇰', country: 'Pakistan' },
  { code: '+680', flag: '🇵🇼', country: 'Palau' },
  { code: '+970', flag: '🇵🇸', country: 'Palestine' },
  { code: '+507', flag: '🇵🇦', country: 'Panama' },
  { code: '+675', flag: '🇵🇬', country: 'Papua New Guinea' },
  { code: '+595', flag: '🇵🇾', country: 'Paraguay' },
  { code: '+51', flag: '🇵🇪', country: 'Peru' },
  { code: '+63', flag: '🇵🇭', country: 'Philippines' },
  { code: '+48', flag: '🇵🇱', country: 'Poland' },
  { code: '+351', flag: '🇵🇹', country: 'Portugal' },
  { code: '+1', flag: '🇵🇷', country: 'Puerto Rico' },
  { code: '+974', flag: '🇶🇦', country: 'Qatar' },
  { code: '+242', flag: '🇨🇬', country: 'Republic of the Congo' },
  { code: '+262', flag: '🇷🇪', country: 'Reunion' },
  { code: '+40', flag: '🇷🇴', country: 'Romania' },
  { code: '+7', flag: '🇷🇺', country: 'Russia' },
  { code: '+250', flag: '🇷🇼', country: 'Rwanda' },
  { code: '+590', flag: '🇧🇱', country: 'Saint Barthelemy' },
  { code: '+290', flag: '🇸🇭', country: 'Saint Helena' },
  { code: '+1', flag: '🇰🇳', country: 'Saint Kitts and Nevis' },
  { code: '+1', flag: '🇱🇨', country: 'Saint Lucia' },
  { code: '+590', flag: '🇲🇫', country: 'Saint Martin' },
  { code: '+508', flag: '🇵🇲', country: 'Saint Pierre and Miquelon' },
  { code: '+1', flag: '🇻🇨', country: 'Saint Vincent and the Grenadines' },
  { code: '+685', flag: '🇼🇸', country: 'Samoa' },
  { code: '+378', flag: '🇸🇲', country: 'San Marino' },
  { code: '+239', flag: '🇸🇹', country: 'Sao Tome and Principe' },
  { code: '+966', flag: '🇸🇦', country: 'Saudi Arabia' },
  { code: '+221', flag: '🇸🇳', country: 'Senegal' },
  { code: '+381', flag: '🇷🇸', country: 'Serbia' },
  { code: '+248', flag: '🇸🇨', country: 'Seychelles' },
  { code: '+232', flag: '🇸🇱', country: 'Sierra Leone' },
  { code: '+65', flag: '🇸🇬', country: 'Singapore' },
  { code: '+1', flag: '🇸🇽', country: 'Sint Maarten' },
  { code: '+421', flag: '🇸🇰', country: 'Slovakia' },
  { code: '+386', flag: '🇸🇮', country: 'Slovenia' },
  { code: '+677', flag: '🇸🇧', country: 'Solomon Islands' },
  { code: '+252', flag: '🇸🇴', country: 'Somalia' },
  { code: '+27', flag: '🇿🇦', country: 'South Africa' },
  { code: '+82', flag: '🇰🇷', country: 'South Korea' },
  { code: '+211', flag: '🇸🇸', country: 'South Sudan' },
  { code: '+34', flag: '🇪🇸', country: 'Spain' },
  { code: '+94', flag: '🇱🇰', country: 'Sri Lanka' },
  { code: '+249', flag: '🇸🇩', country: 'Sudan' },
  { code: '+597', flag: '🇸🇷', country: 'Suriname' },
  { code: '+47', flag: '🇸🇯', country: 'Svalbard and Jan Mayen' },
  { code: '+46', flag: '🇸🇪', country: 'Sweden' },
  { code: '+41', flag: '🇨🇭', country: 'Switzerland' },
  { code: '+963', flag: '🇸🇾', country: 'Syria' },
  { code: '+886', flag: '🇹🇼', country: 'Taiwan' },
  { code: '+992', flag: '🇹🇯', country: 'Tajikistan' },
  { code: '+255', flag: '🇹🇿', country: 'Tanzania' },
  { code: '+66', flag: '🇹🇭', country: 'Thailand' },
  { code: '+228', flag: '🇹🇬', country: 'Togo' },
  { code: '+690', flag: '🇹🇰', country: 'Tokelau' },
  { code: '+676', flag: '🇹🇴', country: 'Tonga' },
  { code: '+1', flag: '🇹🇹', country: 'Trinidad and Tobago' },
  { code: '+216', flag: '🇹🇳', country: 'Tunisia' },
  { code: '+90', flag: '🇹🇷', country: 'Turkey' },
  { code: '+993', flag: '🇹🇲', country: 'Turkmenistan' },
  { code: '+1', flag: '🇹🇨', country: 'Turks and Caicos Islands' },
  { code: '+688', flag: '🇹🇻', country: 'Tuvalu' },
  { code: '+1', flag: '🇻🇮', country: 'U.S. Virgin Islands' },
  { code: '+256', flag: '🇺🇬', country: 'Uganda' },
  { code: '+380', flag: '🇺🇦', country: 'Ukraine' },
  { code: '+971', flag: '🇦🇪', country: 'United Arab Emirates' },
  { code: '+44', flag: '🇬🇧', country: 'United Kingdom' },
  { code: '+1', flag: '🇺🇸', country: 'United States' },
  { code: '+598', flag: '🇺🇾', country: 'Uruguay' },
  { code: '+998', flag: '🇺🇿', country: 'Uzbekistan' },
  { code: '+678', flag: '🇻🇺', country: 'Vanuatu' },
  { code: '+379', flag: '🇻🇦', country: 'Vatican City' },
  { code: '+58', flag: '🇻🇪', country: 'Venezuela' },
  { code: '+84', flag: '🇻🇳', country: 'Vietnam' },
  { code: '+681', flag: '🇼🇫', country: 'Wallis and Futuna' },
  { code: '+212', flag: '🇪🇭', country: 'Western Sahara' },
  { code: '+967', flag: '🇾🇪', country: 'Yemen' },
  { code: '+260', flag: '🇿🇲', country: 'Zambia' },
  { code: '+263', flag: '🇿🇼', country: 'Zimbabwe' },
];

// UI dropdown-safe list: one entry per dial code to avoid duplicate SelectItem values/keys.
// Keep the last occurrence so common modern mappings (e.g. +1 -> United States, +44 -> United Kingdom)
// win when there are shared regional codes.
const countryCodeByDialCode = COUNTRY_CODES.reduce<Record<string, CountryCodeEntry>>((acc, entry) => {
  acc[entry.code] = entry;
  return acc;
}, {});

export const COUNTRY_CODE_OPTIONS: CountryCodeEntry[] = Object.values(countryCodeByDialCode).sort((a, b) => {
  const codeA = Number(a.code.replace('+', ''));
  const codeB = Number(b.code.replace('+', ''));
  return codeA - codeB;
});
