import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {Firestore,Query,DocumentData} from 'firebase-admin/firestore';
import {taskClientAccess} from './native-staff-tasks';
import {nativeHabitDay} from './native-habits';
import {nativeTrackingDay} from './native-staff-tracking';
import {NativeStaffClientError} from './native-staff-client';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeJson} from './native-history';
import {nativeDates} from './native-plan-editor';
const id=z.string().regex(/^[a-f0-9]{24}$/),target=z.object({type:z.string().trim().min(1).max(100),duration:z.string().max(100).optional(),intensity:z.string().max(100).optional(),notes:z.string().max(2000).optional()});
const status=(targets:DocumentData[])=>targets.length&&targets.every(t=>t.isCompleted)?'completed':targets.some(t=>t.isCompleted)?'partial':'pending';
export async function readStaffActivityAssignments(db:Firestore,actorId:string,params:URLSearchParams){const clientId=params.get('clientId')||actorId;await taskClientAccess(db,actorId,clientId);let q:Query=db.collection('activityassignments').where('client','==',clientId);if(params.get('date')){const day=nativeHabitDay(params.get('date'));q=q.where('date','>=',day.start).where('date','<',day.end);}if(params.get('status')&&params.get('status')!=='all')q=q.where('status','==',params.get('status'));const docs=(await q.orderBy('date','desc').get()).docs;const assignments:DocumentData[]=await Promise.all(docs.filter(d=>!d.get('deletedAt')).map(async d=>({_id:d.id,...await hydrateNativeDocument(d.data())}))),ids=[...new Set(assignments.map(a=>a.assignedBy).filter(v=>typeof v==='string'&&/^[a-f0-9]{24}$/.test(v)))],people=new Map();for(let i=0;i<ids.length;i+=100)for(const d of await db.getAll(...ids.slice(i,i+100).map(id=>db.collection('users').doc(id)),{fieldMask:['firstName','lastName']}))if(d.exists)people.set(d.id,{_id:d.id,...d.data()});for(const a of assignments){a.assignedBy=people.get(a.assignedBy)||a.assignedBy;delete a._nativeSource;delete a._nativeExternalFields;}return {success:true,assignments:nativeJson(assignments),count:assignments.length};}
export async function mutateStaffActivityAssignment(db:Firestore,actorId:string,method:'POST'|'PUT'|'DELETE',input:unknown,key?:string|null){const create=method==='POST'?z.object({clientId:id,date:z.string().optional(),targets:z.array(target).min(1).max(100),notes:z.string().max(5000).optional()}).parse(input):null,edit=method!=='POST'?z.object({assignmentId:id,targetId:id.optional(),isCompleted:z.boolean().optional(),completedValue:z.number().finite().nonnegative().max(1000000).optional(),notes:z.string().max(2000).optional()}).parse(input):null;const operation=key&&/^[\w.:-]{8,128}$/.test(key)?key:randomBytes(16).toString('hex'),op=db.collection('_nativeActivityOperations').doc(createHash('sha256').update(actorId+'\0'+operation).digest('hex')),fingerprint=createHash('sha256').update(JSON.stringify({method,create,edit})).digest('hex');
 return db.runTransaction(async tx=>{let row:FirebaseFirestore.DocumentSnapshot|undefined,ref:FirebaseFirestore.DocumentReference,clientId:string,day:ReturnType<typeof nativeHabitDay>|undefined;if(create){clientId=create.clientId;day=nativeHabitDay(create.date);const rows=await tx.get(db.collection('activityassignments').where('client','==',clientId).where('date','>=',day.start).where('date','<',day.end));const alive=rows.docs.filter(d=>!d.get('deletedAt'));if(alive.length>1)throw new NativeStaffClientError('Duplicate assignments require reconciliation',409);row=alive[0];ref=row?.ref||db.collection('activityassignments').doc(randomBytes(12).toString('hex'));}else{ref=db.collection('activityassignments').doc(edit!.assignmentId);row=await tx.get(ref);if(!row.exists||row.get('deletedAt'))throw new NativeStaffClientError('Assignment not found',404);clientId=row.get('client');}
 const access=await taskClientAccess(db,actorId,clientId,tx),actor=await tx.get(db.collection('users').doc(actorId)),client=await tx.get(db.collection('users').doc(clientId)),role=actor.get('role');if(method!=='PUT'&&role==='client')throw new NativeStaffClientError('Staff access required',403);const prior=await tx.get(op);if(prior.exists){if(prior.get('fingerprint')!==fingerprint)throw new NativeStaffClientError('Assignment retry conflict',409);return prior.get('result');}const current=row?.exists?nativeDates(await hydrateNativeDocument(row.data()!)):{},targets:DocumentData[]=[...(current.targets||[])],now=new Date();let deleted=false;if(create){targets.push(...create.targets.map(t=>({...t,_id:randomBytes(12).toString('hex'),isCompleted:false})));}else if(method==='DELETE'){if(edit!.targetId){const index=targets.findIndex(t=>t._id===edit!.targetId);if(index<0)throw new NativeStaffClientError('Target not found',404);targets.splice(index,1);}else targets.length=0;deleted=targets.length===0;}else{if(!edit!.targetId||edit!.isCompleted===undefined)throw new NativeStaffClientError('Target ID and completion state required');const index=targets.findIndex(t=>t._id===edit!.targetId);if(index<0)throw new NativeStaffClientError('Target not found',404);if(role==='client'&&edit!.isCompleted&&new Date(current.date)>=nativeTrackingDay(client.data()!).end)throw new NativeStaffClientError('Upcoming tasks cannot be completed',403);const next:DocumentData={...targets[index],isCompleted:edit!.isCompleted};if(edit!.isCompleted){next.completedAt=next.completedAt||now;if(edit!.completedValue!==undefined)next.completedValue=edit!.completedValue;}else{delete next.completedAt;delete next.completedValue;}if(edit!.notes!==undefined)next.notes=edit!.notes;targets[index]=next;}
 const patch:DocumentData={targets,status:status(targets),updatedAt:now};if(deleted)patch.deletedAt=now;if(create?.notes!==undefined)patch.notes=create.notes;const full={...current,...patch,_id:ref.id,...(!row?.exists?{client:clientId,assignedBy:actorId,date:day!.start,createdAt:now}:{})};if(row?.exists)tx.update(ref,await prepareNativePatch(row.data()!,patch));else tx.create(ref,await prepareNativeDocument(full));const result={success:true,...(!deleted?{assignment:nativeJson(full)}:{}),message:deleted?'Assignment deleted successfully':method==='POST'?'Activity assigned successfully':method==='DELETE'?'Target deleted':edit!.isCompleted?'Target marked as completed':'Target unmarked'};tx.create(op,{fingerprint,result,createdAt:now});const auditId=randomBytes(12).toString('hex');tx.create(db.collection('activitylogs').doc(auditId),{_id:auditId,userId:actorId,targetUserId:clientId,action:result.message,actionType:method==='DELETE'?'delete':method==='POST'?'create':'update',category:'assignment',description:result.message,metadata:{assignmentId:ref.id},createdAt:now,updatedAt:now});return result;});
}
