import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
import type {Firestore,DocumentData,Transaction} from 'firebase-admin/firestore';
import {NativeCheckoutError,type CheckoutProvider} from './native-checkout';
import {nativeFinanceActor,nativeFinanceClient,nativeFinanceClientIds,nativeFinancePeople} from './native-finance-access';
import {nativeDates} from './native-plan-editor';
const clean=(row:DocumentData)=>Object.fromEntries(Object.entries(nativeDates(row)).filter(([key])=>!key.startsWith('_native')&&!/signature|secret/i.test(key)));
export function nativeSubscriptionEnd(start:Date,duration:number,kind:string){
 if(!Number.isInteger(duration)||duration<1||duration>36500||!['days','weeks','months'].includes(kind))throw new NativeCheckoutError('Plan duration invalid',409);
 const end=new Date(start);if(kind==='months'){const day=end.getUTCDate();end.setUTCDate(1);end.setUTCMonth(end.getUTCMonth()+duration);const last=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()+1,0)).getUTCDate();end.setUTCDate(Math.min(day,last));}else end.setUTCDate(end.getUTCDate()+duration*(kind==='weeks'?7:1));return end;
}
function activationWindow(row:DocumentData,now:Date){if(row.durationSnapshot)return {startDate:now,endDate:nativeSubscriptionEnd(now,row.durationSnapshot.duration,row.durationSnapshot.kind)};return {};}
async function access(tx:Transaction,db:Firestore,actorId:string,clientId:string,write=false){const [actor,client]=await tx.getAll(db.collection('users').doc(actorId),db.collection('users').doc(clientId));const role=actor.get('role');if(!actor.exists||actor.get('status')!=='active'||!client.exists||client.get('role')!=='client')throw new NativeCheckoutError('Forbidden',403);const assigned=role==='dietitian'?[client.get('assignedDietitian'),...(client.get('assignedDietitians')||[])]:role==='health_counselor'?[client.get('assignedHealthCounselor'),...(client.get('assignedHealthCounselors')||[])]:[];if(role!=='admin'&&!(role==='client'&&!write&&actorId===clientId)&&!assigned.includes(actorId))throw new NativeCheckoutError('Forbidden',403);return role;}
async function populate(db:Firestore,rows:DocumentData[]):Promise<DocumentData[]>{const plans=new Map<string,DocumentData>();for(const id of new Set<string>(rows.map(row=>row.plan).filter(Boolean))){const row=await db.collection('subscriptionplans').doc(id).get();if(row.exists)plans.set(id,{...nativeDates(row.data()!),_id:id});}return(await nativeFinancePeople(db,rows.map(clean))).map(row=>({...row,plan:plans.get(row.plan)||null}));}
export async function nativeSubscriptions(db:Firestore,actorId:string,params:URLSearchParams,id?:string){const actor=await nativeFinanceActor(db,actorId);let rows:DocumentData[];
 if(id){if(!/^[a-f0-9]{24}$/.test(id))throw new NativeCheckoutError('Invalid subscription',400);const row=await db.collection('clientsubscriptions').doc(id).get();if(!row.exists||row.get('isDeleted'))throw new NativeCheckoutError('Subscription not found',404);await nativeFinanceClient(db,actor,row.get('client'));rows=[{...row.data(),_id:row.id}];}
 else{let query:FirebaseFirestore.Query=db.collection('clientsubscriptions');const client=params.get('clientId');if(client){await nativeFinanceClient(db,actor,client);query=query.where('client','==',client);}else if(actor.role==='client')query=query.where('client','==',actor.id);if(params.get('status'))query=query.where('status','==',params.get('status'));if(params.get('paymentId'))query=query.where('razorpayPaymentId','==',params.get('paymentId'));const allowed=await nativeFinanceClientIds(db,actor),set=allowed?new Set(allowed):null;rows=(await query.get()).docs.filter(row=>!row.get('isDeleted')&&(!set||set.has(row.get('client')))).map(row=>({...row.data(),_id:row.id})).sort((a:any,b:any)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));}
 return populate(db,rows);
}
export async function createNativeSubscription(db:Firestore,actorId:string,input:DocumentData,key:string|null,provider?:{create(data:DocumentData):Promise<DocumentData>;find(reference:string):Promise<DocumentData[]>}){
 if(!/^[a-f0-9]{24}$/.test(input.clientId||'')||!/^[a-f0-9]{24}$/.test(input.planId||'')||!['razorpay','manual','cash','bank-transfer'].includes(input.paymentMethod)||typeof input.notes!=='undefined'&&(typeof input.notes!=='string'||input.notes.length>1000))throw new NativeCheckoutError('Invalid subscription details',400);
 if(!key||!/^[\w.:-]{8,128}$/.test(key))throw new NativeCheckoutError('Idempotency key required',400);
 const id=createHash('sha256').update(actorId+'\0subscription\0'+key).digest('hex').slice(0,24),ref=db.collection('clientsubscriptions').doc(id),identity=JSON.stringify([input.clientId,input.planId,input.paymentMethod,!!input.generatePaymentLink]);
 const prepared=await db.runTransaction(async tx=>{await access(tx,db,actorId,input.clientId,true);const [plan,current]=await tx.getAll(db.collection('subscriptionplans').doc(input.planId),ref);if(current.exists){if(current.get('_nativeIdentity')!==identity)throw new NativeCheckoutError('Retry conflict',409);return {created:false,data:current.data()!};}if(!plan.exists||!plan.get('isActive'))throw new NativeCheckoutError('Plan unavailable',404);const price=Number(plan.get('price')),duration=Number(plan.get('duration')),kind=plan.get('durationType');if(!Number.isFinite(price)||price<=0||Math.round(price*100)<1||Math.abs(price*100-Math.round(price*100))>1e-6||!Number.isInteger(duration)||duration<1||!['days','weeks','months'].includes(kind))throw new NativeCheckoutError('Plan configuration invalid',409);const currency=String(plan.get('currency')||'INR').toUpperCase();if(!['INR','USD','EUR','GBP','AUD','CAD','NZD','SGD','AED'].includes(currency)||!Number.isSafeInteger(Math.round(price*100)))throw new NativeCheckoutError('Plan currency or amount invalid',409);const now=new Date(),end=nativeSubscriptionEnd(now,duration,kind);const data={_id:id,client:input.clientId,dietitian:actorId,plan:input.planId,startDate:now,endDate:end,amount:price,currency,durationSnapshot:{duration,kind},paymentMethod:input.paymentMethod,notes:input.notes||'',status:'pending',paymentStatus:'pending',consultationsUsed:0,followUpsUsed:0,videoCallsUsed:0,createdAt:now,updatedAt:now,_nativeIdentity:identity};tx.create(ref,data);return {created:true,data};});
 let data:DocumentData=prepared.data;if(input.generatePaymentLink&&input.paymentMethod==='razorpay'&&!data.razorpayPaymentLinkId){if(!provider)throw new NativeCheckoutError('Payment provider unavailable',503);const reference='sub_'+id;let proof:DocumentData;if(prepared.created){try{proof=await provider.create({amount:Math.round(data.amount*100),currency:data.currency,description:'DTPS subscription',reference_id:reference,notify:{sms:false,email:false},reminder_enable:false,notes:{subscriptionId:id,clientId:data.client}});}catch{throw new NativeCheckoutError('Provider confirmation pending; retry the same subscription',503);}}else{const found=await provider.find(reference);if(found.length!==1)throw new NativeCheckoutError('Subscription awaiting provider confirmation',503);proof=found[0];}if(typeof proof.short_url!=='string'||!/^https:\/\//.test(proof.short_url)||!/^plink_\w+$/.test(proof.id)||proof.amount!==Math.round(data.amount*100)||proof.currency!==data.currency||proof.reference_id!==reference)throw new NativeCheckoutError('Payment link mismatch',502);await db.runTransaction(async tx=>{await access(tx,db,actorId,data.client,true);const current=await tx.get(ref);if(current.get('razorpayPaymentLinkId')&&current.get('razorpayPaymentLinkId')!==proof.id)throw new NativeCheckoutError('Payment link conflict',409);tx.update(ref,{razorpayPaymentLinkId:proof.id,paymentLink:proof.short_url,updatedAt:new Date()});});data={...data,razorpayPaymentLinkId:proof.id,paymentLink:proof.short_url};}return (await populate(db,[data]))[0];
}
export async function updateNativeSubscription(db:Firestore,actorId:string,id:string,input:DocumentData,remove=false){if(!/^[a-f0-9]{24}$/.test(id))throw new NativeCheckoutError('Invalid subscription',400);await db.runTransaction(async tx=>{const row=await tx.get(db.collection('clientsubscriptions').doc(id));if(!row.exists||row.get('isDeleted'))throw new NativeCheckoutError('Subscription not found',404);const role=await access(tx,db,actorId,row.get('client'),true),now=new Date(),patch:DocumentData={updatedAt:now};if(remove){if(role!=='admin')throw new NativeCheckoutError('Admin required',403);if(row.get('paymentStatus')==='paid')throw new NativeCheckoutError('Paid subscriptions require cancellation and retention',409);patch.isDeleted=true;patch.deletedAt=now;patch.deletedBy=actorId;}else if(input.action==='mark-paid'){if(role!=='admin'||row.get('paymentMethod')==='razorpay')throw new NativeCheckoutError('Admin review of an offline payment is required',403);if(typeof input.transactionId!=='string'||input.transactionId.trim().length<3)throw new NativeCheckoutError('Transaction reference required',400);const claim=db.collection('_nativeManualSubscriptionPayments').doc(createHash('sha256').update(row.get('paymentMethod')+'\0'+input.transactionId.trim()).digest('hex')),existing=await tx.get(claim);if(existing.exists&&existing.get('subscriptionId')!==id)throw new NativeCheckoutError('Transaction already used',409);if(row.get('paymentStatus')==='paid'){if(row.get('transactionId')!==input.transactionId.trim())throw new NativeCheckoutError('Paid subscription has a different transaction reference',409);return;}if(row.get('status')==='cancelled')throw new NativeCheckoutError('Cancelled subscription requires reconciliation',409);Object.assign(patch,activationWindow(row.data()!,now));patch.paymentStatus='paid';patch.status='active';patch.paidAt=now;patch.transactionId=input.transactionId.trim();tx.set(claim,{subscriptionId:id,reviewedBy:actorId,createdAt:now});}else if(input.action==='cancel'){patch.status='cancelled';}else if(typeof input.notes==='string'&&input.notes.length<=1000&&Object.keys(input).every(key=>key==='notes'))patch.notes=input.notes;else throw new NativeCheckoutError('Unsupported subscription update',400);tx.update(row.ref,patch);});return remove?null:(await nativeSubscriptions(db,actorId,new URLSearchParams(),id))[0];}
export async function verifyNativeSubscription(db:Firestore,actorId:string,input:DocumentData,secret:string,provider:CheckoutProvider,fetchLink:(id:string)=>Promise<DocumentData>){const id=input.subscriptionId;if(typeof id!=='string'||!/^[a-f0-9]{24}$/.test(id))throw new NativeCheckoutError('Invalid subscription',400);const ref=db.collection('clientsubscriptions').doc(id),before=await ref.get();if(!before.exists||before.get('isDeleted'))throw new NativeCheckoutError('Subscription not found',404);await nativeFinanceClient(db,await nativeFinanceActor(db,actorId),before.get('client'));let proof:DocumentData,claimId:string;
 if(before.get('razorpayPaymentLinkId')){proof=await fetchLink(before.get('razorpayPaymentLinkId'));if(proof.id!==before.get('razorpayPaymentLinkId')||proof.status!=='paid'||!Number.isFinite(proof.amount_paid)||proof.amount_paid<proof.amount)throw new NativeCheckoutError('Subscription payment pending',409);claimId=proof.id;}
 else{const order=input.razorpay_order_id,payment=input.razorpay_payment_id,signature=input.razorpay_signature;if(order!==before.get('razorpayOrderId')||typeof signature!=='string'||!/^[a-f0-9]{64}$/.test(signature)||!secret||typeof payment!=='string'||!/^pay_\w+$/.test(payment))throw new NativeCheckoutError('Invalid payment verification',400);if(!timingSafeEqual(createHmac('sha256',secret).update(order+'|'+payment).digest(),Buffer.from(signature,'hex')))throw new NativeCheckoutError('Invalid payment signature',400);proof=await provider.fetchPayment(payment);if(proof.id!==payment||proof.order_id!==order||proof.status!=='captured'||proof.captured!==true||Number(proof.amount_refunded||0)>0)throw new NativeCheckoutError('Payment not captured',409);claimId=payment;}
 await db.runTransaction(async tx=>{const [row,claim]=await tx.getAll(ref,db.collection('_nativeSubscriptionPayments').doc(claimId));if(!row.exists||row.get('isDeleted')||row.get('status')==='cancelled')throw new NativeCheckoutError('Subscription requires reconciliation',409);await access(tx,db,actorId,row.get('client'));if(row.get('razorpayOrderId')!==before.get('razorpayOrderId')||row.get('razorpayPaymentLinkId')!==before.get('razorpayPaymentLinkId')||proof.amount!==Math.round(row.get('amount')*100)||proof.currency!==row.get('currency')||claim.exists&&claim.get('subscriptionId')!==id)throw new NativeCheckoutError('Payment amount or identity mismatch',409);const paymentIds=claimId.startsWith('pay_')?[claimId]:[...new Set<string>((Array.isArray(proof.payments)?proof.payments:[]).filter((p:DocumentData)=>p.status==='captured'&&typeof p.payment_id==='string'&&/^pay_[a-zA-Z0-9]+$/.test(p.payment_id)).map((p:DocumentData)=>p.payment_id))];if(paymentIds.length>30)throw new NativeCheckoutError('Split payment requires reconciliation',409);const sharedRefs=[...(claimId.startsWith('plink_')?[db.collection('_nativeRazorpayLinks').doc(claimId)]:[]),...paymentIds.map(paymentId=>db.collection('_nativeRazorpayPayments').doc(paymentId))],shared=sharedRefs.length?await tx.getAll(...sharedRefs):[];if(shared.some(c=>c.exists&&c.get('subscriptionId')!==id))throw new NativeCheckoutError('Provider payment already allocated',409);if(paymentIds.length){const [unified,subscriptions]=await Promise.all([tx.get(db.collection('unifiedpayments').where('razorpayPaymentId','in',paymentIds).limit(31)),tx.get(db.collection('clientsubscriptions').where('razorpayPaymentId','in',paymentIds).limit(31))]);if(!unified.empty||subscriptions.docs.some(doc=>doc.id!==id))throw new NativeCheckoutError('Provider payment already allocated',409);}if(claimId.startsWith('plink_')){const [unified,subscriptions]=await Promise.all([tx.get(db.collection('unifiedpayments').where('razorpayPaymentLinkId','==',claimId).limit(2)),tx.get(db.collection('clientsubscriptions').where('razorpayPaymentLinkId','==',claimId).limit(2))]);if(!unified.empty||subscriptions.docs.some(doc=>doc.id!==id))throw new NativeCheckoutError('Provider link already allocated',409);}if(claimId.startsWith('pay_')&&row.get('razorpayPaymentId')&&row.get('razorpayPaymentId')!==claimId)throw new NativeCheckoutError('Subscription already has a different captured payment',409);for(const c of shared)if(!c.exists)tx.set(c.ref,{subscriptionId:id,client:row.get('client'),verifiedAt:new Date()});if(!claim.exists)tx.set(claim.ref,{subscriptionId:id,createdAt:new Date()});if(row.get('paymentStatus')==='paid')return;tx.update(ref,{...activationWindow(row.data()!,new Date()),status:'active',paymentStatus:'paid',paidAt:new Date(),updatedAt:new Date(),...(claimId.startsWith('pay_')?{razorpayPaymentId:claimId}:{})});});return(await nativeSubscriptions(db,actorId,new URLSearchParams(),id))[0];}
