import {RECIPE_ADMIN_INDEX_FIELD,RECIPE_ADMIN_INDEX_VERSION,recipeAdminOrder,recipeSourceWatermark} from './native-recipe-admin-index';
import {createHash,randomBytes} from 'node:crypto';
import type {Firestore,DocumentData} from 'firebase-admin/firestore';
import {uploadToBlob} from '@/lib/storage/blob-storage';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeRecipeSchema} from './native-staff-recipe-schema';
import {NativeStaffClientError} from './native-staff-client';
import {nativeJson} from './native-history';
import {normalizeNutritionValue,normalizeToArray,normalizeServings} from '@/lib/recipe-normalize';
import {getRecipePublicationIssues,getStrictRecipeFingerprint} from '@/lib/recipe-quality';
import {nativeMediaJson} from '@/lib/api/native-media-json';
const recipeMetadata=new WeakMap<Firestore,{expires:number;pending:Promise<FirebaseFirestore.QuerySnapshot>}>();
const recipeSummaryMetadata=new WeakMap<Firestore,{expires:number;pending:Promise<FirebaseFirestore.QuerySnapshot>}>();
const hash=(s:string)=>createHash('sha256').update(s.trim().toLowerCase()).digest('hex');
export async function recipeActor(db:Firestore,actorId:string,manage=false){const actor=await db.collection('users').doc(actorId).get();if(!actor.exists||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false))throw new NativeStaffClientError('Unauthorized',401);if(manage&&!['admin','dietitian','health_counselor'].includes(actor.get('role')))throw new NativeStaffClientError('Recipe staff access required',403);return actor;}
export async function recipeView(db:Firestore,row:FirebaseFirestore.DocumentSnapshot){const data=await hydrateNativeDocument(row.data()!),out={...data,_id:row.id} as DocumentData;delete out._nativeExternalFields;delete out._nativeSource;out.nutrition=out.flatNutrition=Object.fromEntries(['calories','protein','carbs','fat'].map(k=>[k,normalizeNutritionValue(data[k])]));for(const k of ['tags','dietaryRestrictions','medicalContraindications','allergens'])out[k]=normalizeToArray(data[k]);if(typeof data.createdBy==='string'&&/^[a-f0-9]{24}$/.test(data.createdBy)){const [creator]=await db.getAll(db.collection('users').doc(data.createdBy),{fieldMask:['firstName','lastName']});out.createdBy=creator.exists?{_id:creator.id,...creator.data()}:{firstName:'Unknown',lastName:'User'};}return nativeMediaJson(db,nativeJson(out) as DocumentData);}
export async function readStaffRecipe(db:Firestore,actorId:string,id:string){const actor=await recipeActor(db,actorId);id=id.replace(/^["']+|["']+$/g,'').trim();let row:FirebaseFirestore.DocumentSnapshot|undefined;if(/^[a-f0-9]{24}$/.test(id))row=await db.collection('recipes').doc(id).get();else{const values:any[]=[id];if(/^\d+$/.test(id)){values.push(id.replace(/^0+/,'')||'0',Number(id));}const matches=await db.collection('recipes').where('uuid','in',[...new Set(values)]).limit(2).get();if(matches.size>1)throw new NativeStaffClientError('Ambiguous recipe identifier',409);row=matches.docs[0];}if(!row?.exists||row.get('mergedInto'))throw new NativeStaffClientError('Recipe not found',404);const data=await hydrateNativeDocument(row.data()!);if(actor.get('role')==='client'&&(data.isActive===false||getRecipePublicationIssues(data).length))throw new NativeStaffClientError('Recipe not found',404);return recipeView(db,row);}
export async function saveStaffRecipe(db:Firestore,actorId:string,input:unknown,id?:string,remove=false){
 if(id&&!/^[a-f0-9]{24}$/.test(id))throw new NativeStaffClientError('Invalid recipe ID');const raw=input as DocumentData;if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new NativeStaffClientError('Invalid recipe');const parsed=remove?{}:id?nativeRecipeSchema.partial().parse(raw):nativeRecipeSchema.parse(raw),patch:DocumentData={...parsed};delete patch.forceCreate;
 if(patch.nutrition){for(const key of ['calories','protein','carbs','fat'])patch[key]=normalizeNutritionValue(patch.nutrition[key]);delete patch.nutrition;}if(patch.macros){for(const key of ['protein','carbs','fat'])if(patch.macros[key]!==undefined)patch[key]=normalizeNutritionValue(patch.macros[key]);delete patch.macros;}for(const key of ['protein','carbs','fat'])if(raw[key]!==undefined){const n=Number(raw[key]);if(!Number.isFinite(n)||n<0)throw new NativeStaffClientError('Invalid nutrition');patch[key]=n;}
 if(patch.image?.startsWith('data:')){await recipeActor(db,actorId,true);const match=/^data:(image\/(?:png|jpeg|webp|gif));base64,([A-Za-z0-9+/=\s]+)$/.exec(patch.image);if(!match)throw new NativeStaffClientError('Unsupported image');const bytes=Buffer.from(match[2],'base64');if(bytes.length>10*1024*1024)throw new NativeStaffClientError('Image exceeds 10 MB');const upload=await uploadToBlob(bytes,{type:'recipe-image',filename:`recipe-${randomBytes(8).toString('hex')}`,contentType:match[1]});if(!upload)throw new NativeStaffClientError('Image upload failed',502);patch.image=upload.url;}
 if(patch.servings!==undefined){const servings=normalizeServings(patch.servings);patch.servings=typeof servings==='number'?servings:1;patch.servingSize=typeof raw.servingSize==='string'?raw.servingSize:typeof servings==='string'?servings:'1 serving';}
 const ref=db.collection('recipes').doc(id||randomBytes(12).toString('hex'));
 await db.runTransaction(async tx=>{
  const [actor,current]=await tx.getAll(db.collection('users').doc(actorId),ref);if(!actor.exists||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false)||!['admin','dietitian','health_counselor'].includes(actor.get('role')))throw new NativeStaffClientError('Recipe staff access required',403);if(id&&!current.exists)throw new NativeStaffClientError('Recipe not found',404);if(raw._nativeExpectedUpdatedAt!==undefined&&(current.get('updatedAt')?.toDate?.().toISOString()??null)!==raw._nativeExpectedUpdatedAt)throw new NativeStaffClientError('Recipe changed while merging',409);
  const old=current.exists?await hydrateNativeDocument(current.data()!):{},next={isActive:true,...old,...patch};if(!remove&&next.isActive!==false&&getRecipePublicationIssues(next).length)throw new NativeStaffClientError('Complete the recipe before publishing');
  const nameIndex=db.collection('_nativeRecipeNames').doc(hash(next.name)),index=await tx.get(nameIndex),oldIndex=current.exists&&hash(old.name)!==hash(next.name)?db.collection('_nativeRecipeNames').doc(hash(old.name)):null,oldNames=oldIndex?await tx.get(oldIndex):null;
  const peers=(index.get('recipeIds')||[]).filter((peer:string)=>peer!==ref.id);if(!remove&&peers.length){const candidates=await tx.getAll(...peers.map((peer:string)=>db.collection('recipes').doc(peer)));for(const peer of candidates){if(!peer.exists||peer.get('mergedInto'))continue;const data=await hydrateNativeDocument(peer.data() as DocumentData);if(getStrictRecipeFingerprint(data as DocumentData)===getStrictRecipeFingerprint(next))throw new NativeStaffClientError('Duplicate recipe exists',409);}}
  let seq:number|undefined;const counter=db.collection('_nativeCounters').doc('recipeIds');if(!current.exists){const snap=await tx.get(counter);if(!Number.isSafeInteger(snap.get('seq')))throw new NativeStaffClientError('Recipe counter requires migration initialization',503);seq=snap.get('seq')+1;}
  const now=new Date();if(remove){tx.update(ref,{isActive:false,deletedAt:now,updatedAt:now,[RECIPE_ADMIN_INDEX_FIELD]:recipeAdminOrder({...next,deletedAt:now})});}else{const data={...patch,[RECIPE_ADMIN_INDEX_FIELD]:recipeAdminOrder({...next,...(!current.exists?{uuid:String(seq)}:{})}),totalTime:Number(next.prepTime||0)+Number(next.cookTime||0),updatedAt:now};if(current.exists){const {[RECIPE_ADMIN_INDEX_FIELD]:order,...content}=data;tx.update(ref,{...await prepareNativePatch(current.data()!,content),[RECIPE_ADMIN_INDEX_FIELD]:order});}else{tx.update(counter,{seq});tx.create(ref,await prepareNativeDocument({isActive:true,tags:[],dietaryRestrictions:[],medicalContraindications:[],allergens:[],views:0,...data,_id:ref.id,uuid:String(seq),createdBy:actorId,createdAt:now}));}tx.set(nameIndex,{recipeIds:[...new Set([...peers,ref.id])]});if(oldIndex)tx.set(oldIndex,{recipeIds:(oldNames?.get('recipeIds')||[]).filter((peer:string)=>peer!==ref.id)});}
  const aid=randomBytes(12).toString('hex');tx.create(db.collection('activitylogs').doc(aid),{_id:aid,userId:actorId,userRole:actor.get('role'),action:remove?'Archived Recipe':id?'Updated Recipe':'Created Recipe',actionType:remove?'delete':id?'update':'create',category:'recipe',resourceId:ref.id,createdAt:now,updatedAt:now});
 });recipeMetadata.delete(db);recipeSummaryMetadata.delete(db);return recipeView(db,await ref.get());
}
export async function listStaffRecipes(db:Firestore,actorId:string,params:URLSearchParams){
 const actor=await recipeActor(db,actorId),manage=['admin','dietitian','health_counselor'].includes(actor.get('role'));
 const summary=manage&&params.get('summary')==='true',cache=summary?recipeSummaryMetadata:recipeMetadata;
 const allowedFastParams=new Set(['summary','includeInactive','includeTotal','sortBy','page','limit']);
 const fast=summary&&params.get('includeInactive')==='true'&&params.get('sortBy')==='uuid'&&[...params.keys()].every(k=>allowedFastParams.has(k))&&Number.isFinite(Number(params.get('page')||1))&&Number.isFinite(Number(params.get('limit')||50))&&Number(params.get('limit')||50)>0;
 let indexedPage:FirebaseFirestore.QuerySnapshot|undefined,indexedTotal:number|undefined;
 if(fast){const marker=await db.collection('_nativeIndexes').doc('recipeAdmin').get();if(marker.get('ready')===true&&marker.get('version')===RECIPE_ADMIN_INDEX_VERSION&&marker.get('sourceWatermark')===recipeSourceWatermark()){const limit=Math.max(1,Math.min(1000,Math.floor(Number(params.get('limit'))||50))),page=Math.max(1,Math.floor(Number(params.get('page'))||1)),query=db.collection('recipes').orderBy(RECIPE_ADMIN_INDEX_FIELD);const [rows,total]=await Promise.all([query.offset((page-1)*limit).limit(limit).select('name','uuid','createdBy','createdAt','isActive','calories','protein','carbs','fat','prepTime','rating').get(),query.count().get()]);indexedPage=rows;indexedTotal=total.data().count;}}

 let cached=cache.get(db);if(!indexedPage&&(!cached||cached.expires<Date.now())){const pending=db.collection('recipes').select(...(summary?['name','uuid','createdBy','createdAt','isActive','mergedInto','deletedAt','calories','protein','carbs','fat','prepTime','rating','category','cuisine','difficulty','tags','dietaryRestrictions','medicalContraindications','allergens']:['name','description','uuid','isActive','mergedInto','deletedAt','tags','dietaryRestrictions','medicalContraindications','allergens','category','cuisine','difficulty','calories','protein','carbs','fat','prepTime','cookTime','rating','createdAt','ingredients','instructions','servings','servingSize'])).get();cached={expires:Infinity,pending};const entry=cached;cache.set(db,entry);pending.then(()=>{entry.expires=Date.now()+30000;},()=>{if(cache.get(db)===entry)cache.delete(db);});}const rows=indexedPage||await cached!.pending;
 const list=(key:string)=>params.get(key)?.split(',').map(v=>v.trim().toLowerCase()).filter(Boolean)||[],search=(params.get('exactName')||params.get('search')||'').trim().toLowerCase(),exact=!!params.get('exactName'),restrictions=list('dietaryRestrictions'),allergens=list('excludeAllergens'),conditions=list('excludeMedicalConditions');
 let filtered=rows.docs.filter(row=>{const d=row.data(),array=(key:string)=>normalizeToArray(d[key]).map(v=>v.toLowerCase());if(d.mergedInto||d.deletedAt||(!(manage&&params.get('includeInactive')==='true')&&d.isActive===false))return false;if(!manage&&getRecipePublicationIssues(d).length)return false;
  if(search&&!(exact?String(d.name||'').trim().toLowerCase()===search:[d.name,d.description,d.uuid,row.id,...array('tags'),...(Array.isArray(d.ingredients)?d.ingredients.map((i:any)=>i.name||i):[])].some(v=>String(v||'').toLowerCase().includes(search))))return false;
  for(const key of ['category','cuisine','difficulty']){const value=params.get(key);if(value&&value!=='all'&&d[key]!==value)return false;}if(!restrictions.every(r=>array('dietaryRestrictions').includes(r)))return false;if(allergens.some(a=>array('allergens').includes(a))||conditions.some(c=>array('medicalContraindications').includes(c)))return false;
  const exclusions=list('excludeDietaryRestrictions').map(v=>v.replace(/ /g,'-')),allergenSet=array('allergens'),name=String(d.name||'').toLowerCase();
  const blocked:Record<string,string[]>={'gluten-free':['gluten','wheat'],'dairy-free':['dairy','milk','lactose'],'egg-free':['egg','eggs'],'nut-free':['nut','nuts','peanut','almond','cashew','walnut'],'soy-free':['soy','soya']};for(const restriction of exclusions){if((blocked[restriction]||[]).some(a=>allergenSet.includes(a)))return false;}
  if(exclusions.includes('vegetarian')||exclusions.includes('vegan')){if(array('dietaryRestrictions').some(r=>r.replace(/ /g,'-')==='non-vegetarian')||allergenSet.some(a=>['egg','eggs'].includes(a))||/egg|chicken|mutton|fish|meat|prawn|shrimp|crab|lobster|lamb|pork|beef|bacon|ham|sausage/i.test(name))return false;}
  if(exclusions.includes('vegan')&&(allergenSet.some(a=>['dairy','milk','honey'].includes(a))||/milk|cheese|paneer|curd|yogurt|butter|ghee|cream|honey/i.test(name)))return false;
  if(exclusions.includes('diabetic-friendly')&&array('medicalContraindications').some(c=>['diabetes','diabetic','high sugar'].includes(c)))return false;

  for(const [param,field,minimum] of [['maxCalories','calories',false],['minProtein','protein',true],['maxPrepTime','prepTime',false]] as const){const value=params.get(param);if(value&&Number.isFinite(Number(value))&&(minimum?Number(d[field]||0)<Number(value):Number(d[field]||0)>Number(value)))return false;}return true;
 });
 const sort=params.get('sortBy')||'name';filtered.sort((a,b)=>{let result=0;if(['uuid','uuid-desc','id','numeric'].includes(sort))result=((parseInt(String(a.get('uuid')||'0'),10)||0)-(parseInt(String(b.get('uuid')||'0'),10)||0))*(sort==='uuid-desc'?-1:1);else if(sort==='newest')result=(b.get('createdAt')?.toMillis?.()||0)-(a.get('createdAt')?.toMillis?.()||0);else if(['rating','popular'].includes(sort))result=Number(b.get('rating.average')||0)-Number(a.get('rating.average')||0);else if(sort==='calories')result=Number(a.get('calories')||0)-Number(b.get('calories')||0);else if(['prepTime','prep-time'].includes(sort))result=Number(a.get('prepTime')||0)-Number(b.get('prepTime')||0);else result=String(a.get('name')||'').localeCompare(String(b.get('name')||''));return result||a.id.localeCompare(b.id);});
 const num=(s:string|null,f:number)=>s&&Number.isFinite(Number(s))?Math.floor(Number(s)):f,limit=Math.max(0,Math.min(1000,num(params.get('limit'),50))),page=Math.max(1,num(params.get('page'),1)),start=limit?(page-1)*limit:0,selected=indexedPage?filtered:filtered.slice(start,limit?start+limit:undefined),full=[] as FirebaseFirestore.DocumentSnapshot[];if(summary)full.push(...selected);else for(let i=0;i<selected.length;i+=100)full.push(...await db.getAll(...selected.slice(i,i+100).map(d=>d.ref)));
 const recipes:DocumentData[]=[];
 if(summary){const creatorIds=[...new Set(full.map(row=>row.get('createdBy')).filter(value=>typeof value==='string'&&/^[a-f0-9]{24}$/.test(value)))],creators=new Map<string,DocumentData>();for(let i=0;i<creatorIds.length;i+=100){const people=await db.getAll(...creatorIds.slice(i,i+100).map(id=>db.collection('users').doc(id)),{fieldMask:['firstName','lastName']});for(const person of people)if(person.exists)creators.set(person.id,{_id:person.id,...person.data()});}recipes.push(...full.map(row=>nativeJson({...row.data(),_id:row.id,createdBy:creators.get(row.get('createdBy'))||null}) as DocumentData));}
 else for(let i=0;i<full.length;i+=12)recipes.push(...await Promise.all(full.slice(i,i+12).map(row=>recipeView(db,row))));const includeTotal=params.get('includeTotal')==='true',tags=[...new Set(rows.docs.flatMap(r=>normalizeToArray(r.get('tags'))))];return {success:true,recipes,pagination:{page,limit,total:includeTotal?(indexedTotal??filtered.length):null,pages:includeTotal&&limit?Math.ceil((indexedTotal??filtered.length)/limit):null,hasNext:limit?start+limit<(indexedTotal??filtered.length):false},cuisines:[...new Set(rows.docs.map(r=>r.get('cuisine')).filter(Boolean))],tags,categories:tags};
}
