import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,Query,DocumentData} from '@/lib/db/mongo-types';
import {formatInTimeZone,fromZonedTime} from 'date-fns-tz';
import {isValidMealTimeZone,TASK_TIME_ZONE} from '@/lib/task-schedule';
import {hydrateNativeDocument,prepareNativePatch,prepareNativeDocument} from '@/lib/storage/native-document';
import {nativeAppointmentActor} from './native-staff-appointments';
import {NativeStaffClientError} from './native-staff-client';
import {nativeJson} from './native-history';
import {taskClientAccess} from './native-staff-tasks';
const nutrients=['calories','protein','carbs','fat','sugar','sodium'] as const,num=z.coerce.number().finite().min(0).max(100000);
function day(value:unknown,zone:string){const date=value?new Date(String(value)):new Date();if(!Number.isFinite(date.getTime()))throw new NativeStaffClientError('Invalid date');const key=typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)?value:formatInTimeZone(date,zone,'yyyy-MM-dd'),next=new Date(Date.parse(key+'T12:00:00Z')+86400000).toISOString().slice(0,10);return {key,start:fromZonedTime(key+'T00:00:00',zone),end:fromZonedTime(next+'T00:00:00',zone)};}
export async function readStaffFoodLogs(db:MongoDatabase,actorId:string,params:URLSearchParams){const actor=await nativeAppointmentActor(db,actorId),role=actor.get('role'),clientId=role==='client'?actorId:params.get('clientId');if(!clientId&&role!=='admin')throw new NativeStaffClientError('Client ID required');let client=actor;if(clientId&&clientId!==actorId){await taskClientAccess(db,actorId,clientId);client=await db.collection('users').doc(clientId).get();}const zone=isValidMealTimeZone(client.get('timezone'))?client.get('timezone'):TASK_TIME_ZONE;let q:Query=db.collection('foodlogs');if(clientId)q=q.where('client','==',clientId);const date=params.get('date');if(date){const d=day(date,zone);q=q.where('date','>=',d.start).where('date','<',d.end);}else if(params.get('startDate')&&params.get('endDate')){const start=day(params.get('startDate'),zone),end=day(params.get('endDate'),zone);if(start.start>end.start)throw new NativeStaffClientError('Invalid date range');q=q.where('date','>=',start.start).where('date','<',end.end);}
 const page=Math.max(1,Math.floor(Number(params.get('page'))||1)),limit=Math.max(1,Math.min(100,Math.floor(Number(params.get('limit'))||50))),[rows,count]=await Promise.all([q.orderBy('date','desc').offset((page-1)*limit).limit(limit).get(),q.count().get()]);const logs=await Promise.all(rows.docs.map(async d=>({_id:d.id,...await hydrateNativeDocument(d.data())}) as DocumentData));let dailyTotals={calories:0,protein:0,carbs:0,fat:0};const flattened:DocumentData[]=[];for(const log of logs){if(date)for(const k of ['calories','protein','carbs','fat'] as const)dailyTotals[k]+=Number(log.totalNutrition?.[k]||0);for(const meal of log.meals||[])for(const food of meal.foods||[])flattened.push({_id:food._id,foodName:food.name,quantity:food.quantity,unit:food.unit,calories:food.calories,macros:{protein:food.nutrition?.protein||0,carbs:food.nutrition?.carbs||0,fat:food.nutrition?.fat||0},mealType:meal.type,loggedAt:log.date});}return {foodLogs:nativeJson(flattened),dailyTotals,pagination:{page,limit,total:count.data().count,pages:Math.ceil(count.data().count/limit)}};
}
export async function createStaffFoodLog(db:MongoDatabase,actorId:string,input:unknown,operationKey?:string|null){const body=z.object({foodName:z.string().trim().min(1).max(500),quantity:z.coerce.number().positive().max(100000),unit:z.string().max(50).default('g'),calories:num.default(0),macros:z.object({protein:num.default(0),carbs:num.default(0),fat:num.default(0),sugar:num.default(0),sodium:num.default(0)}).default({protein:0,carbs:0,fat:0,sugar:0,sodium:0}),mealType:z.string().min(1).max(100),loggedAt:z.string().optional()}).parse(input),key=operationKey&&/^[\w.:-]{8,128}$/.test(operationKey)?operationKey:randomBytes(16).toString('hex'),itemId=createHash('sha256').update(actorId+'\0food\0'+key).digest('hex').slice(0,24),fingerprint=createHash('sha256').update(JSON.stringify(body)).digest('hex');
 return db.runTransaction(async tx=>{const user=await tx.get(db.collection('users').doc(actorId));if(!user.exists||(['inactive','suspended'].includes(user.get('status'))||user.get('isActive')===false))throw new NativeStaffClientError('Unauthorized',401);const zone=isValidMealTimeZone(user.get('timezone'))?user.get('timezone'):TASK_TIME_ZONE,d=day(body.loggedAt,zone);if(d.start>day(null,zone).start)throw new NativeStaffClientError('Future meals cannot be logged');const rows=await tx.get(db.collection('foodlogs').where('client','==',actorId).where('date','>=',d.start).where('date','<',d.end).limit(2));if(rows.size>1)throw new NativeStaffClientError('Duplicate food log dates require reconciliation',409);const row=rows.docs[0],ref=row?.ref||db.collection('foodlogs').doc(createHash('sha256').update(actorId+'\0foodday\0'+d.key).digest('hex').slice(0,24)),op=db.collection('_nativeFoodLogOperations').doc(itemId),[existing,claimed]=await tx.getAll(ref,op);if(claimed.exists){if(claimed.get('fingerprint')!==fingerprint)throw new NativeStaffClientError('Food log retry conflict',409);return nativeJson({_id:ref.id,...await hydrateNativeDocument(existing.data()!),client:{_id:user.id,firstName:user.get('firstName'),lastName:user.get('lastName')}});}if(!row&&existing.exists)throw new NativeStaffClientError('Food log identity conflict',409);const current=row?await hydrateNativeDocument(row.data()):{},meals=[...(current.meals||[])],food={_id:itemId,name:body.foodName,quantity:body.quantity,unit:body.unit,calories:body.calories,nutrition:body.macros},index=meals.findIndex(m=>m.type===body.mealType);if(index>=0)meals[index]={...meals[index],foods:[...(meals[index].foods||[]),food]};else meals.push({_id:randomBytes(12).toString('hex'),type:body.mealType,foods:[food]});const totalNutrition:DocumentData=Object.fromEntries(nutrients.map(k=>[k,0]));for(const meal of meals)for(const item of meal.foods||[])for(const nutrient of nutrients)totalNutrition[nutrient]+=Number(nutrient==='calories'?item.calories||0:item.nutrition?.[nutrient]||0);for(const n of nutrients)totalNutrition[n]=Math.round(totalNutrition[n]*10)/10;const patch={meals,totalNutrition,updatedAt:new Date()};if(row)tx.update(ref,await prepareNativePatch(row.data(),patch));else tx.create(ref,await prepareNativeDocument({_id:ref.id,client:actorId,date:d.start,...patch,createdAt:new Date()}));tx.create(op,{fingerprint,userId:actorId,createdAt:new Date()});return nativeJson({...current,...patch,_id:ref.id,date:d.start,client:{_id:user.id,firstName:user.get('firstName'),lastName:user.get('lastName')}});});
}
