import type * as MongoTypes from '@/lib/db/mongo-types';
import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,Query,Transaction,DocumentData} from '@/lib/db/mongo-types';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeJson} from './native-history';
import {NativeStaffClientError} from './native-staff-client';
export async function nativeCommerceAdmin(db:MongoDatabase,actorId:string,tx?:Transaction){const ref=db.collection('users').doc(actorId),row=tx?await tx.get(ref):await ref.get();if(!row.exists||row.get('role')!=='admin'||(['inactive','suspended'].includes(row.get('status'))||row.get('isActive')===false))throw new NativeStaffClientError('Admin access required',403);return row;}
type Kind='orders'|'payments';const collection=(kind:Kind)=>kind==='orders'?'ecommerceorder':'ecommercepayment',identity=(kind:Kind)=>kind==='orders'?'orderId':'paymentId';
const text=z.string().max(5000).optional(),money=z.coerce.number().finite().min(0).max(1e12).optional(),address=z.object(Object.fromEntries(['firstName','lastName','email','phone','address1','address2','city','state','postalCode','country'].map(k=>[k,text]))),common={status:text,currency:z.string().max(10).optional(),origin:text,source:text,raw:z.unknown().optional()};
const orderSchema=z.object({...common,orderId:z.string().trim().min(1).max(200).optional(),externalOrderId:text,paymentStatus:text,orderDate:z.coerce.date().nullable().optional(),updatedDate:z.coerce.date().nullable().optional(),totalAmount:money,taxAmount:money,discountAmount:money,shippingAmount:money,customer:z.object({customerId:text,firstName:text,lastName:text,email:text,phone:text}).optional(),billingAddress:address.optional(),shippingAddress:address.optional(),items:z.array(z.object({itemId:text,sku:text,name:z.string().min(1).max(1000),quantity:z.coerce.number().min(0).max(1e6).optional(),price:money,total:money})).max(10000).optional(),notes:text});
const paymentSchema=z.object({...common,paymentId:z.string().trim().min(1).max(200).optional(),transactionId:text,orderId:text,externalOrderId:text,paymentType:text,paymentMethod:text,amount:money,paymentDate:z.coerce.date().nullable().optional(),payer:z.object({name:text,email:text,phone:text}).optional()});
async function view(rows:MongoTypes.DocumentSnapshot[]){return Promise.all(rows.map(async d=>{const data:DocumentData={_id:d.id,...await hydrateNativeDocument(d.data()!)};delete data._nativeSource;delete data._nativeExternalFields;return nativeJson(data);}));}
export async function nativeCommerceRead(db:MongoDatabase,actorId:string,kind:Kind,params:URLSearchParams,id?:string){await nativeCommerceAdmin(db,actorId);let q:Query=db.collection(collection(kind));if(id){const rows=await q.where(identity(kind),'==',id).limit(2).get();if(rows.size!==1||rows.docs[0].get('deletedAt'))throw new NativeStaffClientError(rows.size>1?'Duplicate commerce identity':'Record not found',rows.size>1?409:404);return {[kind==='orders'?'order':'payment']:(await view(rows.docs))[0]};}
 for(const field of kind==='orders'?['status','paymentStatus']:['status','orderId'])if(params.get(field)&&params.get(field)!=='all')q=q.where(field,'==',params.get(field));const limit=Math.max(1,Math.min(100,Math.floor(Number(params.get('limit'))||20))),skip=params.has('skip')?Math.max(0,Math.floor(Number(params.get('skip'))||0)):Math.max(0,(Math.floor(Number(params.get('page'))||1)-1)*limit),search=params.get('search')?.trim().toLowerCase(),dateField=kind==='orders'?'orderDate':'paymentDate';
 const metadata=await q.select(identity(kind),'orderId','transactionId','customer.email','customer.phone','payer.email',dateField,'createdAt','deletedAt').get();const rows=metadata.docs.filter(d=>!d.get('deletedAt')&&(!search||[d.get(identity(kind)),d.get('orderId'),d.get('transactionId'),d.get('customer.email'),d.get('customer.phone'),d.get('payer.email')].some(v=>String(v||'').toLowerCase().includes(search)))).sort((a,b)=>(b.get(dateField)?.toMillis?.()||0)-(a.get(dateField)?.toMillis?.()||0)||(b.get('createdAt')?.toMillis?.()||0)-(a.get('createdAt')?.toMillis?.()||0)),selected=rows.slice(skip,skip+limit),full=selected.length?await db.getAll(...selected.map(d=>d.ref)):[];return {[kind]:await view(full),total:rows.length,page:Math.floor(skip/limit)+1,limit,totalPages:Math.max(1,Math.ceil(rows.length/limit))};
}
export async function nativeCommerceWrite(db:MongoDatabase,actorId:string,kind:Kind,input:unknown,mode:'create'|'update'|'upsert'|'delete',id?:string){const body=mode==='delete'?{}:(kind==='orders'?orderSchema:paymentSchema).parse(input),field=identity(kind),key=id||(body as DocumentData)[field];if(typeof key!=='string'||!key.trim()||key.length>200)throw new NativeStaffClientError('Commerce ID required');if(id&&(body as DocumentData)[field]&&id!==(body as DocumentData)[field])throw new NativeStaffClientError('Commerce ID cannot be changed');return db.runTransaction(async tx=>{await nativeCommerceAdmin(db,actorId,tx);const rows=await tx.get(db.collection(collection(kind)).where(field,'==',key).limit(2));if(rows.size>1)throw new NativeStaffClientError('Duplicate commerce identity requires reconciliation',409);const row=rows.docs[0],ref=row?.ref||db.collection(collection(kind)).doc(createHash('sha256').update(collection(kind)+'\0'+key).digest('hex').slice(0,24));if(!row&&(await tx.get(ref)).exists)throw new NativeStaffClientError('Commerce identity conflict',409);if(mode==='create'&&row)throw new NativeStaffClientError('Commerce ID already exists',409);if(['update','delete'].includes(mode)&&(!row||row.get('deletedAt')))throw new NativeStaffClientError('Record not found',404);const now=new Date(),patch:DocumentData=mode==='delete'?{deletedAt:now,updatedAt:now}:{...body,[field]:key,updatedAt:now};const full=row?{...await hydrateNativeDocument(row.data()),...patch,_id:ref.id}:{status:'pending',currency:'INR',origin:'external',...(kind==='orders'?{paymentStatus:'pending',totalAmount:0,taxAmount:0,discountAmount:0,shippingAmount:0,items:[],billingAddress:{},shippingAddress:{}}:{amount:0}),...patch,_id:ref.id,createdAt:now};if(row)tx.update(ref,await prepareNativePatch(row.data(),patch));else tx.create(ref,await prepareNativeDocument(full));const log=randomBytes(12).toString('hex');tx.create(db.collection('activitylogs').doc(log),{_id:log,userId:actorId,action:`${mode} ecommerce ${kind}`,actionType:mode==='delete'?'delete':mode==='create'?'create':'update',category:'payment',description:`${mode} ecommerce ${kind}`,metadata:{recordId:ref.id},createdAt:now,updatedAt:now});return mode==='delete'?{success:true}:{[kind==='orders'?'order':'payment']:nativeJson(full)};});}
