import type * as MongoTypes from '@/lib/db/mongo-types';
import {randomBytes,createHash} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,DocumentData,Query} from '@/lib/db/mongo-types';
import {requireNativeAuditAdmin} from './native-admin-audit';
import {NativeDirectoryError} from './native-client-directory';
import {nativeDates} from './native-plan-editor';
const schema=z.object({name:z.string().trim().max(200).optional(),email:z.union([z.string().email().max(320),z.literal('')]).optional(),phone:z.string().trim().max(30).optional(),source:z.string().trim().max(100).optional(),status:z.string().trim().max(100).optional(),message:z.string().trim().max(10000).optional(),notes:z.string().trim().max(10000).optional(),metadata:z.record(z.string(),z.unknown()).refine(v=>JSON.stringify(v).length<=10000,'Metadata too large').optional(),origin:z.string().trim().max(100).optional()});
function view(id:string,data:DocumentData){return {_id:id,...Object.fromEntries(Object.entries(nativeDates(data)).filter(([k])=>['name','email','phone','source','status','message','notes','metadata','origin','createdAt','updatedAt'].includes(k)))};}
export async function readNativeLeads(db:MongoDatabase,adminId:string,params:URLSearchParams,id?:string){await requireNativeAuditAdmin(db,adminId);if(id){if(!/^[a-f0-9]{24}$/i.test(id))throw new NativeDirectoryError('Invalid lead ID');const doc=await db.collection('lead').doc(id).get();if(!doc.exists)throw new NativeDirectoryError('Not found',404);return {lead:view(id,doc.data()!)};}const page=Math.max(1,Math.floor(Number(params.get('page'))||1)),limit=Math.min(200,Math.max(1,Math.floor(Number(params.get('limit'))||30))),search=params.get('search')?.trim().toLowerCase();let query:Query=db.collection('lead');if(params.get('status')&&params.get('status')!=='all')query=query.where('status','==',params.get('status'));let total:number,docs:MongoTypes.DocumentSnapshot[];if(search){const rows=await query.select('name','email','phone','createdAt').orderBy('createdAt','desc').get(),matches=rows.docs.filter(doc=>['name','email','phone'].some(k=>String(doc.get(k)||'').toLowerCase().includes(search)));total=matches.length;const ids=matches.slice((page-1)*limit,page*limit).map(d=>d.id);docs=ids.length?await db.getAll(...ids.map(v=>db.collection('lead').doc(v))):[];}else{const [count,rows]=await Promise.all([query.count().get(),query.orderBy('createdAt','desc').offset((page-1)*limit).limit(limit).get()]);total=count.data().count;docs=rows.docs;}return {leads:docs.map(doc=>view(doc.id,doc.data()!)),total,page,limit,totalPages:Math.max(1,Math.ceil(total/limit))};}
export async function writeNativeLead(db:MongoDatabase,input:unknown,adminId?:string,id?:string,remove=false,rateKey?:string){if(id&&!/^[a-f0-9]{24}$/i.test(id))throw new NativeDirectoryError('Invalid lead ID');const parsed=schema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid lead fields');const data:DocumentData={...parsed.data};if(data.email)data.email=data.email.toLowerCase();if(!id&&!data.name&&!data.email&&!data.phone)throw new NativeDirectoryError('Name, email, or phone is required');if(!adminId){data.status='new';delete data.notes;}const ref=db.collection('lead').doc(id||randomBytes(12).toString('hex'));return db.runTransaction(async tx=>{if(adminId){const admin=await tx.get(db.collection('users').doc(adminId));if(admin.get('role')!=='admin'||admin.get('status')!=='active')throw new NativeDirectoryError('Forbidden',403);}else if(id||remove)throw new NativeDirectoryError('Forbidden',403);const existing=await tx.get(ref);if(id&&!existing.exists)throw new NativeDirectoryError('Not found',404);let throttle:MongoTypes.DocumentReference|undefined,count=0;if(!adminId&&rateKey){throttle=db.collection('_nativeLeadRateLimits').doc(createHash('sha256').update(rateKey+'\0'+Math.floor(Date.now()/3600000)).digest('hex'));const state=await tx.get(throttle);count=Number(state.get('count')||0);if(count>=20)throw new NativeDirectoryError('Too many submissions; try later',429);}const now=new Date();if(throttle)tx.set(throttle,{count:count+1,expiresAt:new Date(now.getTime()+7200000)});if(remove){tx.delete(ref);tx.create(db.collection('adminauditlogs').doc(),{adminId,action:'lead_deleted',targetId:id,createdAt:now});return {success:true};}const next={...(!id?{source:'external',status:'new',origin:'dtps',createdAt:now}:existing.data()),...data,updatedAt:now};if(id)tx.update(ref,{...data,updatedAt:now});else tx.create(ref,{...next,_id:ref.id});return {lead:view(ref.id,next)};});}
