import type * as MongoTypes from '@/lib/db/mongo-types';
import {Filter,type MongoDatabase,type DocumentData} from '@/lib/db/mongo-types';
import {directoryFields,filterFields,nativeDirectoryProfile,populateNativeDirectory,nativeDirectoryStatuses,NativeDirectoryError} from './native-client-directory';
import {nativeDates} from './native-plan-editor';
export async function listNativeUsers(db:MongoDatabase,actorId:string,p:URLSearchParams){
 const actor=await db.collection('users').doc(actorId).get(),role=actor.get('role');if(!actor.exists||actor.get('status')!=='active')throw new NativeDirectoryError('Access denied',403);
 const page=Number(p.get('page')||1),requested=Number(p.get('limit')||50),limit=Math.min(500,requested);if(!Number.isSafeInteger(page)||page<1||!Number.isSafeInteger(requested)||requested<1||!Number.isSafeInteger((page-1)*limit))throw new NativeDirectoryError('Invalid pagination');
 let query:MongoTypes.Query=db.collection('users');const requestedRole=p.get('role');
 if(role==='admin'){if(requestedRole)query=query.where('role','==',requestedRole);}else if(role==='dietitian')query=query.where('role','==','client').where(Filter.or(Filter.where('assignedDietitian','==',actorId),Filter.where('assignedDietitians','array-contains',actorId)));else if(role==='health_counselor'){query=query.where('role','==','client');if(requestedRole!=='client')query=query.where(Filter.or(Filter.where('assignedHealthCounselor','==',actorId),Filter.where('assignedHealthCounselors','array-contains',actorId)));}else if(role==='client'){if(actor.get('assignedDietitian'))query=query.where('__name__','==',actor.get('assignedDietitian'));else query=query.where('role','in',['dietitian','health_counselor']);}else throw new NativeDirectoryError('Access denied',403);
 if(role==='admin')for(const [parameter,field] of [['dietitianId','assignedDietitian'],['healthCounselorId','assignedHealthCounselor']]){const id=p.get(parameter);if(id){if(!/^[a-f0-9]{24}$/i.test(id))throw new NativeDirectoryError('Invalid staff ID');query=query.where(field,'==',id);}}
 for(const [parameter,operator,clock] of [['dateFrom','>=','00:00:00.000'],['dateTo','<=','23:59:59.999']] as const){const date=p.get(parameter);if(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(new Date(date).getTime()))throw new NativeDirectoryError('Invalid date');query=query.where('createdAt',operator,new Date(`${date}T${clock}+05:30`));}}
 const search=(p.get('search')||'').trim().toLowerCase(),status=p.get('status');let ids:string[],total:number;let pageProfiles:DocumentData[]|undefined;let filteredStatuses:Map<string,unknown>|undefined;
 if(!search&&!status){const [count,rows]=await Promise.all([query.count().get(),query.orderBy('createdAt','desc').offset((page-1)*limit).limit(limit).select(...directoryFields).get()]);total=count.data().count;ids=rows.docs.map(d=>d.id);pageProfiles=rows.docs.map(d=>nativeDirectoryProfile(d.id,d.data()));}else{const docs=await query.select(...filterFields).get();let candidates:DocumentData[]=docs.docs.map(d=>({_id:d.id,...nativeDates(d.data())}));if(search)candidates=candidates.filter(d=>['firstName','lastName','email','phone','clientId'].some(k=>String(d[k]||'').toLowerCase().includes(search))||`${d.firstName||''} ${d.lastName||''}`.toLowerCase().includes(search)||`${d.lastName||''} ${d.firstName||''}`.toLowerCase().includes(search));if(status){candidates=await nativeDirectoryStatuses(db,candidates);filteredStatuses=new Map(candidates.map(d=>[d._id,d.clientStatus]));candidates=candidates.filter(d=>(d.role==='client'?d.clientStatus:d.status)===status);}candidates.sort((a,b)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()||a._id.localeCompare(b._id));total=candidates.length;ids=candidates.slice((page-1)*limit,page*limit).map(d=>d._id);}
 const rows=!pageProfiles&&ids.length?await db.getAll(...ids.map(id=>db.collection('users').doc(id)),{fieldMask:[...directoryFields]}):[];
 const profiles=pageProfiles||rows.filter(d=>d.exists).map(d=>nativeDirectoryProfile(d.id,d.data()!));
 let users=await populateNativeDirectory(db,filteredStatuses?profiles.map(d=>d.role==='client'?{...d,clientStatus:filteredStatuses!.get(d._id)}:d):await nativeDirectoryStatuses(db,profiles));
 if(role==='client')users=users.map(d=>Object.fromEntries(['_id','firstName','lastName','email','phone','avatar','role'].filter(k=>d[k]!==undefined).map(k=>[k,d[k]])));
 const roleCounts:Record<string,number>={};if(role==='admin'){await Promise.all([['admin','admin'],['dietitian','dietitian'],['healthCounselor','health_counselor'],['client','client']].map(async([key,r])=>{roleCounts[key]=(await db.collection('users').where('role','==',r).count().get()).data().count;}));}
 const counter=role==='admin'?await db.collection('_nativeCounters').doc('clientIds').get():null;
 return {users,pagination:{page,limit,total,pages:Math.ceil(total/limit)},roleCounts,clientStats:{latestClientIdNumber:counter?.get('seq')||0}};
}
