import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {Firestore,DocumentData} from 'firebase-admin/firestore';
import {NativePlanEditor} from './native-plan-editor';
import {nativeUserRecordAccess} from './native-user-documents';
import {NativeDirectoryError} from './native-client-directory';
import {nativeHabitDay} from './native-habits';
import {MEAL_TYPES,MEAL_TYPE_KEYS} from '@/lib/mealConfig';
const schema=z.object({mealType:z.string().max(100),hour:z.string().regex(/^(0?[1-9]|1[0-2])$/),minute:z.string().regex(/^[0-5][0-9]$/),meridian:z.enum(['AM','PM']),food:z.string().max(10000),amount:z.string().max(1000).optional(),notes:z.string().max(10000).optional()});
function meal(input:DocumentData){const config=MEAL_TYPE_KEYS.map(k=>MEAL_TYPES[k]).find(m=>m.label.toLowerCase()===String(input.mealType||'').trim().toLowerCase());if(!config)throw new NativeDirectoryError('Invalid meal type');const [hour,minute,meridian]=config.time12h.split(/[: ]/);const parsed=schema.safeParse({...input,mealType:config.label,hour:String(input.hour||Number(hour)),minute:String(input.minute||minute).padStart(2,'0'),meridian:input.meridian||meridian,food:input.food||''});if(!parsed.success)throw new NativeDirectoryError('Invalid meal data');return parsed.data;}
export async function readNativeUserRecall(db:Firestore,actorId:string,userId:string){const editor=new NativePlanEditor(db);await nativeUserRecordAccess(editor,actorId,userId);const rows=await editor.query('dietaryrecalls',[['userId','==',userId]]);rows.sort((a,b)=>new Date(b.date||b.createdAt||0).getTime()-new Date(a.date||a.createdAt||0).getTime());const recall=rows[0]?await editor.hydrate(rows[0]):null;return {success:true,meals:recall?.meals||[],entries:(recall?.meals||[]).map((m:DocumentData,i:number)=>({...m,id:m._id||`meal-${i}`})),recallId:recall?._id||null,...(recall?{date:recall.date}:{})};}
export async function writeNativeUserRecall(db:Firestore,actorId:string,userId:string,input:unknown,recallId?:string,removeMeal?:string){
 if(!input||typeof input!=='object'||Array.isArray(input))throw new NativeDirectoryError('Invalid recall');const b=input as DocumentData;const array=Array.isArray(b.meals)?b.meals:Array.isArray(b.entries)?b.entries:null;const parsed=array?array.map(meal):removeMeal?null:meal(b);if(array&&array.length>100)throw new NativeDirectoryError('Too many meals');const day=nativeHabitDay(undefined),now=new Date();
 for(let attempt=0;attempt<5;attempt++){const editor=new NativePlanEditor(db);await nativeUserRecordAccess(editor,actorId,userId);const rows=recallId?[]:await editor.query('dietaryrecalls',[['userId','==',userId],['date','>=',day.start],['date','<',day.end]]);if(rows.length>1)throw new NativeDirectoryError('Duplicate recall dates require reconciliation',409);const raw=recallId?await editor.document('dietaryrecalls',recallId):rows[0],current=raw?await editor.hydrate(raw):null;if(recallId&&(!current||current.userId!==userId))throw new NativeDirectoryError('Recall not found',404);const id=current?current._id:createHash('sha256').update('dietaryrecalls\0'+userId+'\0'+day.start.toISOString()).digest('hex').slice(0,24);
 let meals:DocumentData[]=current?.meals||[];if(removeMeal){if(!meals.some(m=>m.mealType===removeMeal))throw new NativeDirectoryError('Meal not found',404);meals=meals.filter(m=>m.mealType!==removeMeal);}else if(array)meals=(parsed as DocumentData[]).map(m=>({...m,_id:meals.find(old=>old.mealType===m.mealType)?._id||randomBytes(12).toString('hex')}));else{const next=parsed as DocumentData,index=meals.findIndex(m=>m.mealType===next.mealType),entry={...next,_id:index>=0?meals[index]._id||randomBytes(12).toString('hex'):randomBytes(12).toString('hex')};meals=index>=0?meals.map((m,i)=>i===index?entry:m):[...meals,entry];}
 const patch={meals,updatedAt:now,updatedBy:actorId},data={_id:id,userId,date:day.start,createdAt:now,...patch};if(await editor.commit(current?[{collection:'dietaryrecalls',id,patch}]:[],current?[]:[{collection:'dietaryrecalls',id,data}]))return {success:true,recall:current?{...current,...patch}:data,recallId:id,...(removeMeal?{message:'Meal entry deleted'}:{})};
 }throw new NativeDirectoryError('Recall changed while saving. Please retry.',409);
}
