import {createHash} from 'node:crypto';
import {z} from 'zod';
import {Filter,type Firestore,type DocumentData} from 'firebase-admin/firestore';
import {nativeCommerceAdmin} from './native-staff-ecommerce';
import {NativeStaffClientError} from './native-staff-client';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeJson} from './native-history';
import {nativeDates} from './native-plan-editor';
import {createNativeStaffUser} from './native-admin-create-user';
const col='woocommerceclients',fields=['name','email','phone','city','country','totalOrders','processingOrders','completedOrders','totalSpent','processingAmount','completedAmount','currency','firstOrderDate','lastOrderDate','lastSyncDate','wooCommerceCustomerId','deletedAt'];
const stats=(rows:DocumentData[])=>({totalClients:rows.length,totalOrders:rows.reduce((s,c)=>s+Number(c.totalOrders||0),0),processingOrders:rows.reduce((s,c)=>s+Number(c.processingOrders||0),0),completedOrders:rows.reduce((s,c)=>s+Number(c.completedOrders||0),0),totalRevenue:rows.reduce((s,c)=>s+Number(c.totalSpent||0),0),processingRevenue:rows.reduce((s,c)=>s+Number(c.processingAmount||0),0),completedRevenue:rows.reduce((s,c)=>s+Number(c.completedAmount||0),0),topSpender:Math.max(0,...rows.map(c=>Number(c.totalSpent||0))),lastSync:rows.reduce((latest,c)=>c.lastSyncDate&&(!latest||c.lastSyncDate>latest)?c.lastSyncDate:latest,null),currency:'INR'});
async function wooMetadata(db:Firestore){const rows=await db.collection(col).select(...fields).get();return rows.docs.filter(r=>!r.get('deletedAt')).map(d=>({_id:d.id,...nativeDates(d.data())}) as DocumentData);}
async function wooView(db:Firestore,id:string){const d=await db.collection(col).doc(id).get();if(!d.exists||d.get('deletedAt'))throw new NativeStaffClientError('Client not found',404);const data:DocumentData={id:d.id,...await hydrateNativeDocument(d.data()!)};delete data.password;delete data._nativeSource;delete data._nativeExternalFields;return data;}
export async function readWooClients(db:Firestore,actorId:string,params:URLSearchParams,detailId?:string){const actor=await db.collection('users').doc(actorId).get();if(!actor.exists||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false)||!['admin','dietitian'].includes(actor.get('role')))throw new NativeStaffClientError('Staff access required',403);let allowedEmails:Set<string>|undefined;if(actor.get('role')==='dietitian'){if(detailId)throw new NativeStaffClientError('Admin access required',403);const assigned=await db.collection('users').where('role','==','client').where(Filter.or(Filter.where('assignedDietitian','==',actorId),Filter.where('assignedDietitians','array-contains',actorId))).select('email').get();allowedEmails=new Set(assigned.docs.map(d=>String(d.get('email')||'').toLowerCase()).filter(Boolean));}if(detailId){if(!/^[a-f0-9]{24}$/.test(detailId))throw new NativeStaffClientError('Invalid client ID');return {client:nativeJson(await wooView(db,detailId))};}const search=params.get('search')?.trim().toLowerCase(),page=Math.max(1,Number(params.get('page'))||1),per_page=Math.max(1,Math.min(100,Number(params.get('per_page'))||20)),sort=fields.includes(params.get('sortBy')||'')?params.get('sortBy')!:'totalSpent',direction=params.get('sortOrder')==='asc'?1:-1;const rows=(await wooMetadata(db)).filter(c=>!allowedEmails||allowedEmails.has(String(c.email||'').toLowerCase())).filter(c=>!search||['name','email','phone','city','country'].some(f=>String(c[f]||'').toLowerCase().includes(search))).sort((a,b)=>{const av=a[sort],bv=b[sort];return (typeof av==='number'||av instanceof Date?Number(av||0)-Number(bv||0):String(av||'').localeCompare(String(bv||'')))*direction;});const summary=stats(rows),selected=rows.slice((page-1)*per_page,page*per_page),clients=await Promise.all(selected.map(async c=>{const full=await wooView(db,c._id);return {...c,id:c._id,ordersCount:full.orders?.length||0};}));return nativeJson({clients,pagination:{page,per_page,total:rows.length,total_pages:Math.ceil(rows.length/per_page),has_next:page<Math.ceil(rows.length/per_page),has_prev:page>1},summary:{...summary,avgOrderValue:rows.length?summary.totalRevenue/rows.length:0}});}
export async function deleteWooClients(db:Firestore,actorId:string,clientId?:string){await nativeCommerceAdmin(db,actorId);if(clientId&&!/^[a-f0-9]{24}$/.test(clientId))throw new NativeStaffClientError('Invalid client ID');const refs=clientId?[db.collection(col).doc(clientId)]:(await db.collection(col).select().get()).docs.map(d=>d.ref);let count=0,deletedClient:DocumentData|undefined;for(let i=0;i<refs.length;i+=300)await db.runTransaction(async tx=>{await nativeCommerceAdmin(db,actorId,tx);const rows=await tx.getAll(...refs.slice(i,i+300));for(const d of rows){if(clientId&&!d.exists)throw new NativeStaffClientError('Client not found',404);if(d.exists&&!d.get('deletedAt')){tx.update(d.ref,{deletedAt:new Date(),updatedAt:new Date()});count++;if(clientId)deletedClient={id:d.id,name:d.get('name'),email:d.get('email')};}}});return {message:clientId?'WooCommerce client deleted successfully':'WooCommerce data archived',deletedCount:count,...(deletedClient?{deletedClient}:{}),timestamp:new Date().toISOString()};}
const money=z.coerce.number().finite().nonnegative().max(1e12),short=z.string().max(1000).default(''),clientSchema=z.object({name:short,email:z.string().email().max(320).transform(v=>v.trim().toLowerCase()),phone:short,city:short,country:short,totalOrders:money.default(0),processingOrders:money.default(0),completedOrders:money.default(0),totalSpent:money.default(0),processingAmount:money.default(0),completedAmount:money.default(0),currency:z.string().max(10).default('INR'),firstOrderDate:z.coerce.date().nullable().optional(),lastOrderDate:z.coerce.date().nullable().optional()});
const orderSchema=z.object({id:z.number().int().nonnegative(),orderNumber:short,status:short,total:money,currency:z.string().max(10),dateCreated:z.coerce.date(),dateModified:z.coerce.date(),datePaid:z.coerce.date().nullable().optional(),customer:z.object({email:z.string().email()}),payment:z.object({method:short,methodTitle:short,transactionId:short}),customerId:z.number().int().nonnegative().optional()});
export async function saveWooClients(db:Firestore,actorId:string,input:unknown){await nativeCommerceAdmin(db,actorId);const body=z.object({clients:z.array(clientSchema).max(10000),orders:z.array(orderSchema).max(100000).default([])}).parse(input);let savedClientsCount=0,updatedClientsCount=0;const failures:DocumentData[]=[];for(let index=0;index<body.clients.length;index++){const client=body.clients[index],orders=body.orders.filter(o=>o.customer.email.trim().toLowerCase()===client.email).map(o=>({orderId:o.id,orderNumber:o.orderNumber,status:o.status,total:o.total,currency:o.currency,dateCreated:o.dateCreated,dateModified:o.dateModified,datePaid:o.datePaid||null,paymentMethod:o.payment.method,paymentMethodTitle:o.payment.methodTitle,transactionId:o.payment.transactionId,customerId:o.customerId||0}));try{const created=await db.runTransaction(async tx=>{await nativeCommerceAdmin(db,actorId,tx);const rows=await tx.get(db.collection(col).where('email','==',client.email).limit(2));if(rows.size>1)throw new NativeStaffClientError('Duplicate WooCommerce email',409);const row=rows.docs[0],ref=row?.ref||db.collection(col).doc(createHash('sha256').update('woo\0'+client.email).digest('hex').slice(0,24));if(!row&&(await tx.get(ref)).exists)throw new NativeStaffClientError('WooCommerce identity conflict',409);const patch={...client,orders,lastSyncDate:new Date(),updatedAt:new Date(),deletedAt:null};if(row)tx.update(ref,await prepareNativePatch(row.data(),patch));else tx.create(ref,await prepareNativeDocument({_id:ref.id,...patch,createdAt:new Date()}));return !row;});if(created)savedClientsCount++;else updatedClientsCount++;}catch{failures.push({index,error:'Client could not be saved; retry or reconcile its identity'});}}
 return {message:failures.length?'WooCommerce import completed with errors':'WooCommerce data saved successfully',savedClientsCount,updatedClientsCount,totalClientsCount:savedClientsCount+updatedClientsCount,ordersCount:body.orders.length,failures,timestamp:new Date().toISOString()};}
export async function readWooDatabase(db:Firestore,actorId:string,params:URLSearchParams){await nativeCommerceAdmin(db,actorId);const rows=await wooMetadata(db),page=Math.max(1,Number(params.get('page'))||1),per_page=Math.max(1,Math.min(100,Number(params.get('per_page'))||50)),type=params.get('type')||'all',result:DocumentData={};if(['clients','all'].includes(type)){result.clients=[...rows].sort((a,b)=>Number(b.totalSpent||0)-Number(a.totalSpent||0)).slice((page-1)*per_page,page*per_page);if(type==='clients')result.pagination={page,per_page,total:rows.length,total_pages:Math.ceil(rows.length/per_page)};}if(['summary','all'].includes(type)){const summary=stats(rows);result.summary={...summary,averageOrderValue:summary.totalOrders?summary.totalRevenue/summary.totalOrders:0};}
 if(['orders','all'].includes(type)){const all:DocumentData[]=[];for(let i=0;i<rows.length;i+=8)for(const client of await Promise.all(rows.slice(i,i+8).map(r=>wooView(db,r._id))))for(const order of client.orders||[])all.push({id:order.orderId,orderNumber:order.orderNumber,status:order.status,total:order.total,currency:order.currency,dateCreated:order.dateCreated,dateModified:order.dateModified,datePaid:order.datePaid,customer:{name:client.name,email:client.email,phone:client.phone,city:client.city,country:client.country},payment:{method:order.paymentMethod,methodTitle:order.paymentMethodTitle,transactionId:order.transactionId},customerId:order.customerId});all.sort((a,b)=>new Date(b.dateCreated).getTime()-new Date(a.dateCreated).getTime());result.orders=all.slice((page-1)*per_page,page*per_page);if(type==='orders')result.pagination={page,per_page,total:all.length,total_pages:Math.ceil(all.length/per_page)};}return nativeJson(result);}
export async function migrateWooClients(db:Firestore,actorId:string,write=false){await nativeCommerceAdmin(db,actorId);const woo=await wooMetadata(db);if(!write){const [users,clients,migrated]=await Promise.all([db.collection('users').count().get(),db.collection('users').where('role','==','client').count().get(),db.collection('users').where('wooCommerceData','!=',null).select('firstName','lastName','email','wooCommerceData.totalOrders','wooCommerceData.totalSpent').get()]);return nativeJson({totalWooClients:woo.length,totalUsers:users.data().count,clientUsers:clients.data().count,wooCommerceUsers:migrated.size,migrationComplete:migrated.size>0,sampleClients:migrated.docs.slice(0,5).map(d=>({name:[d.get('firstName'),d.get('lastName')].filter(Boolean).join(' '),email:d.get('email'),totalOrders:d.get('wooCommerceData.totalOrders')||0,totalSpent:d.get('wooCommerceData.totalSpent')||0}))});}
 let migratedCount=0,updatedCount=0,skippedCount=0;for(const record of woo){try{const source=await wooView(db,record._id),email=String(source.email||'').trim().toLowerCase();if(!email)throw new Error('Email required');let matches=await db.collection('users').where('email','==',email).limit(2).get();if(matches.size>1)throw new Error('Ambiguous identity');let userId=matches.docs[0]?.id,created=false;if(!userId){const names=String(source.name||'Client').trim().split(/\s+/),user=await createNativeStaffUser(db,actorId,{role:'client',email,phone:source.phone,firstName:names[0]||'Client',lastName:names.slice(1).join(' ')||'-'});userId=String(user._id);created=true;}
 await db.runTransaction(async tx=>{await nativeCommerceAdmin(db,actorId,tx);const [fresh,user]=await tx.getAll(db.collection(col).doc(record._id),db.collection('users').doc(userId));if(!fresh.exists||fresh.get('deletedAt')||!user.exists||user.get('role')!=='client'||String(user.get('email')||'').toLowerCase()!==email)throw new NativeStaffClientError('Migration identity changed',409);const data=await hydrateNativeDocument(fresh.data()!),wooCommerceData:DocumentData={};for(const f of ['wooCommerceCustomerId','totalOrders','totalSpent','processingOrders','completedOrders','processingAmount','completedAmount','firstOrderDate','lastOrderDate','orders','lastSyncDate'])if(data[f]!==undefined)wooCommerceData[f==='wooCommerceCustomerId'?'customerId':f]=data[f];tx.update(user.ref,await prepareNativePatch(user.data()!,{wooCommerceData,updatedAt:new Date()}));});if(created)migratedCount++;else updatedCount++;}catch{skippedCount++;}}
 return {message:skippedCount?'WooCommerce migration completed with unresolved clients':'WooCommerce clients migration completed',totalWooClients:woo.length,migratedCount,updatedCount,skippedCount,summary:{newClients:migratedCount,updatedExisting:updatedCount,errors:skippedCount}};
}
