import {createHash,randomBytes} from 'node:crypto';
import type {Firestore,DocumentData} from 'firebase-admin/firestore';
import {z} from 'zod';
import {formatInTimeZone,fromZonedTime} from 'date-fns-tz';
import {isValidMealTimeZone,TASK_TIME_ZONE} from '@/lib/task-schedule';
import {hydrateNativeDocument,prepareNativePatch,prepareNativeDocument} from '@/lib/storage/native-document';
import {nativeAppointmentActor} from './native-staff-appointments';
import {NativeStaffClientError} from './native-staff-client';
import {nativeDates} from './native-plan-editor';
import {nativeJson} from './native-history';
export function nativeTrackingDay(user:DocumentData){const zone=isValidMealTimeZone(user.timezone)?user.timezone:TASK_TIME_ZONE,key=formatInTimeZone(new Date(),zone,'yyyy-MM-dd'),next=new Date(Date.parse(key+'T12:00:00Z')+86400000).toISOString().slice(0,10);return {key,start:fromZonedTime(key+'T00:00:00',zone),end:fromZonedTime(next+'T00:00:00',zone)};}
export async function nativeDailyTracking(db:Firestore,actorId:string,kind:'water'|'steps'|'sleep'|'weight',input?:unknown,operationKey?:string|null){const actor=await nativeAppointmentActor(db,actorId),day=nativeTrackingDay(actor.data()!),defaults={water:{glasses:0,target:8},steps:{count:0,target:10000},sleep:{hours:0,target:8}},q=db.collection('dailytrackings').where('client','==',actorId).where('date','>=',day.start).where('date','<',day.end);
 if(kind==='weight'){
 if(input!==undefined){const {weight}=z.object({weight:z.number().positive().max(1000)}).parse(input),key=operationKey&&/^[\w.:-]{8,128}$/.test(operationKey)?operationKey:randomBytes(16).toString('hex'),ref=db.collection('progressentries').doc(createHash('sha256').update(actorId+'\0weight\0'+key).digest('hex').slice(0,24));await db.runTransaction(async tx=>{const [user,existing]=await tx.getAll(actor.ref,ref);if(!user.exists||(['inactive','suspended'].includes(user.get('status'))||user.get('isActive')===false))throw new NativeStaffClientError('Unauthorized',401);if(existing.exists){if(existing.get('value')!==weight)throw new NativeStaffClientError('Weight retry conflict',409);return;}const now=new Date();tx.create(ref,{_id:ref.id,user:actorId,type:'weight',value:weight,unit:'kg',notes:'Weight logged via dashboard',recordedAt:now,createdAt:now,updatedAt:now});tx.update(user.ref,{'weight':weight,'goals.currentWeight':weight,updatedAt:now});});}
 const [user,history]=await Promise.all([actor.ref.get(),db.collection('progressentries').where('user','==',actorId).where('type','==','weight').orderBy('recordedAt','desc').select('value','recordedAt','deletedAt','isDeleted').get()]);return {success:true,weight:{current:user.get('weight')||0,target:user.get('goals.targetWeight')||70,history:history.docs.filter(d=>!d.get('deletedAt')&&!d.get('isDeleted')).slice(0,input===undefined?30:7).map(d=>({_id:d.id,...nativeDates(d.data())}))}};
 }
 if(input===undefined){const rows=await q.limit(2).get();if(rows.size>1)throw new NativeStaffClientError('Duplicate tracking day requires reconciliation',409);const data=rows.empty?{}:await hydrateNativeDocument(rows.docs[0].data());return {success:true,[kind]:data[kind]||defaults[kind]};}
 const parsed=kind==='water'?z.object({glasses:z.number().finite().optional(),action:z.enum(['set','increment','decrement'])}).parse(input):kind==='steps'?z.object({steps:z.number().finite().nonnegative()}).parse(input):z.object({hours:z.number().min(0).max(24)}).parse(input);
 return db.runTransaction(async tx=>{const user=await tx.get(actor.ref);if(!user.exists||(['inactive','suspended'].includes(user.get('status'))||user.get('isActive')===false))throw new NativeStaffClientError('Unauthorized',401);const rows=await tx.get(q.limit(2));if(rows.size>1)throw new NativeStaffClientError('Duplicate tracking day requires reconciliation',409);const row=rows.docs[0],ref=row?.ref||db.collection('dailytrackings').doc(createHash('sha256').update(actorId+'\0'+day.key).digest('hex').slice(0,24));if(!row&&(await tx.get(ref)).exists)throw new NativeStaffClientError('Tracking identity conflict',409);const data=row?await hydrateNativeDocument(row.data()):{},current={...defaults[kind],...data[kind]},value=parsed as DocumentData;if(kind==='water'){if(value.action==='set'&&value.glasses===undefined)throw new NativeStaffClientError('Glasses required');current.glasses=Math.max(0,Math.min(20,value.action==='set'?value.glasses:current.glasses+(value.action==='increment'?1:-1)));}else if(kind==='steps')current.count=Math.min(100000,value.steps);else current.hours=value.hours;const patch={[kind]:current,updatedAt:new Date()};if(row)tx.update(ref,await prepareNativePatch(row.data(),patch));else tx.create(ref,await prepareNativeDocument({_id:ref.id,client:actorId,date:day.start,...defaults,...patch,createdAt:new Date()}));return {success:true,[kind]:current};});
}
export async function nativeFitness(db:Firestore,actorId:string,method:string,input?:unknown){const actor=await nativeAppointmentActor(db,actorId);if(method==='GET')return {fitnessData:(await hydrateNativeDocument(actor.data()!)).fitnessData||null};const values=method==='POST'?z.object({steps:z.number().min(0).max(1000000),calories:z.number().min(0).max(100000),distance:z.number().min(0).max(100000).default(0),heartRate:z.number().min(0).max(300).nullable().default(null),activeMinutes:z.number().min(0).max(1440).default(0),deviceType:z.string().max(100).default('unknown')}).parse(input):z.object({goals:z.record(z.string(),z.union([z.number().finite().nonnegative().max(1000000),z.boolean(),z.string().max(100)])).optional(),preferences:z.record(z.string(),z.union([z.number().finite(),z.boolean(),z.string().max(100)])).optional()}).parse(input);
 return db.runTransaction(async tx=>{const user=await tx.get(actor.ref);if(!user.exists||(['inactive','suspended'].includes(user.get('status'))||user.get('isActive')===false))throw new NativeStaffClientError('Unauthorized',401);const raw=await hydrateNativeDocument(user.data()!),fitness={...(raw.fitnessData||{})},now=new Date();let record:DocumentData|undefined;if(method==='POST'){record={...values,lastSync:now,date:nativeTrackingDay(raw).key};fitness.dailyRecords=[...(fitness.dailyRecords||[]),record];fitness.lastSync=now;fitness.connectedDevice=(values as DocumentData).deviceType;}else Object.assign(fitness,values);tx.update(user.ref,await prepareNativePatch(user.data()!,{fitnessData:fitness,updatedAt:now}));return nativeJson(method==='POST'?{success:true,fitnessData:record}:{success:true,goals:fitness.goals,preferences:fitness.preferences});});
}
