import {Filter,type Firestore,type Query,type DocumentData} from 'firebase-admin/firestore';
import {formatInTimeZone,fromZonedTime} from 'date-fns-tz';
import {NativeDirectoryError} from './native-client-directory';
import {nativeDates} from './native-plan-editor';
export async function nativeAnalyticsStats(db:Firestore,actorId:string,now=new Date()){
 const actor=await db.collection('users').doc(actorId).get(),role=actor.get('role');if(actor.get('status')!=='active'||!['admin','dietitian','health_counselor'].includes(role))throw new NativeDirectoryError('Staff access required',403);const isAdmin=role==='admin';let users:Query=db.collection('users').where('role','==','client');if(!isAdmin){const key=role==='dietitian'?'assignedDietitian':'assignedHealthCounselor';users=users.where(Filter.or(Filter.where(key,'==',actorId),Filter.where(key+'s','array-contains',actorId)));}
 const userRows=await users.select('wooCommerceData','lastLoginAt','updatedAt').get();let appointmentRows:DocumentData[]=[];const fields=['scheduledAt','status','type','duration'];if(isAdmin){appointmentRows=(await db.collection('appointments').select(...fields).get()).docs.map(d=>nativeDates(d.data()));}else if(role==='dietitian'){appointmentRows=(await db.collection('appointments').where('dietitian','==',actorId).select(...fields).get()).docs.map(d=>nativeDates(d.data()));}else{const ids=userRows.docs.map(d=>d.id);for(let i=0;i<ids.length;i+=180)await Promise.all(Array.from({length:Math.min(6,Math.ceil((ids.length-i)/30))},async(_,slot)=>{const rows=await db.collection('appointments').where('client','in',ids.slice(i+slot*30,i+(slot+1)*30)).select(...fields).get();appointmentRows.push(...rows.docs.map(d=>nativeDates(d.data())));}));}
 const zone='Asia/Kolkata',today=fromZonedTime(formatInTimeZone(now,zone,'yyyy-MM-dd')+'T00:00:00',zone),monthKey=formatInTimeZone(now,zone,'yyyy-MM'),monthBase=new Date(monthKey+'-01T00:00:00Z'),activeSince=now.getTime()-30*86400000,ms=(value:any)=>{const time=new Date(value).getTime();return Number.isFinite(time)?time:0;},month=(value:any)=>ms(value)?formatInTimeZone(value,zone,'yyyy-MM'):'';
 const clientRows=userRows.docs.map(d=>nativeDates(d.data())),totalClients=clientRows.length,totalRevenue=clientRows.reduce((sum,row)=>sum+Number(row.wooCommerceData?.totalSpent||0),0),totalOrders=clientRows.reduce((sum,row)=>sum+Number(row.wooCommerceData?.totalOrders||0),0);const months=Array.from({length:6},(_,index)=>{const date=new Date(monthBase);date.setUTCMonth(date.getUTCMonth()-(5-index));return {key:date.toISOString().slice(0,7),label:date.toLocaleDateString('en-IN',{month:'short',timeZone:'UTC'})};});const typeCounts=new Map<string,number>();appointmentRows.forEach(row=>typeCounts.set(row.type||'Consultation',(typeCounts.get(row.type||'Consultation')||0)+1));const durations=appointmentRows.map(a=>Number(a.duration)).filter(v=>Number.isFinite(v)&&v>0);
 return {isAdmin,totalClients,activeClients:clientRows.filter(row=>Number(row.wooCommerceData?.totalOrders)>0||ms(row.lastLoginAt)>=activeSince||ms(row.updatedAt)>=activeSince).length,totalAppointments:appointmentRows.length,completedAppointments:appointmentRows.filter(row=>ms(row.scheduledAt)<today.getTime()&&['confirmed','completed'].includes(row.status)).length,totalRevenue:isAdmin?totalRevenue:0,monthlyRevenue:isAdmin?clientRows.filter(row=>month(row.wooCommerceData?.lastOrderDate)===monthKey).reduce((sum,row)=>sum+Number(row.wooCommerceData?.totalSpent||0),0):0,avgSessionDuration:durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0,clientRetentionRate:totalClients?Math.round(clientRows.filter(row=>Number(row.wooCommerceData?.totalOrders)>1).length/totalClients*100):0,appointmentsByMonth:months.map(m=>({month:m.label,appointments:appointmentRows.filter(row=>month(row.scheduledAt)===m.key).length,revenue:0})),clientProgress:[],appointmentTypes:[...typeCounts].sort((a,b)=>b[1]-a[1]).map(([type,count])=>({type,count,revenue:0})),revenueByMonth:isAdmin?months.map(m=>({month:m.label,revenue:clientRows.filter(row=>month(row.wooCommerceData?.lastOrderDate)===m.key).reduce((sum,row)=>sum+Number(row.wooCommerceData?.totalSpent||0),0)})):[],wooSummary:{totalClients,processingOrders:0,completedOrders:0,totalRevenue:isAdmin?totalRevenue:0,processingRevenue:0,completedRevenue:0,averageOrderValue:isAdmin&&totalOrders?totalRevenue/totalOrders:0},unavailableMetrics:['clientProgress','appointmentRevenue','processingOrders','completedOrders','processingRevenue','completedRevenue'],revenueBasis:'Imported commerce customer totals attributed to last order month'};
}
