import type * as MongoTypes from '@/lib/db/mongo-types';
import {randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {formatInTimeZone} from 'date-fns-tz';
import {isValidMealTimeZone,scheduledTaskTime,TASK_TIME_ZONE} from '@/lib/task-schedule';
import {nativeJson} from './native-history';
import {nativeDates} from './native-plan-editor';
import {nativeAppointmentActor} from './native-staff-appointments';
import {NativeStaffClientError} from './native-staff-client';
const clock=z.string().regex(/^(?:[01]?\d|2[0-3]):[0-5]\d$/),schema=z.object({dayOfWeek:z.number().int().min(0).max(6),startTime:clock,endTime:clock,slotDuration:z.number().int().min(15).max(180).default(60),isActive:z.boolean().default(true)}),minutes=(value:string)=>Number(value.split(':')[0])*60+Number(value.split(':')[1]);
export async function nativeProviderAvailability(db:MongoDatabase,actorId:string,providerId:string){const actor=await nativeAppointmentActor(db,actorId);if(!/^[a-f0-9]{24}$/.test(providerId||''))throw new NativeStaffClientError('Valid provider ID required');const provider=await db.collection('users').doc(providerId).get();if(!provider.exists||!['dietitian','health_counselor'].includes(provider.get('role')))throw new NativeStaffClientError('Provider not found',404);
 if(actor.get('role')==='client'&&![actor.get('assignedDietitian'),...(actor.get('assignedDietitians')||[]),actor.get('assignedHealthCounselor'),...(actor.get('assignedHealthCounselors')||[])].includes(providerId))throw new NativeStaffClientError('Provider is not assigned to you',403);
 const rows=await db.collection('provideravailabilities').where('providerId','==',providerId).where('isActive','==',true).get();return {provider,availability:rows.docs.map(d=>({_id:d.id,...nativeDates(d.data())} as DocumentData)).sort((a,b)=>a.dayOfWeek-b.dayOfWeek||minutes(a.startTime)-minutes(b.startTime))};
}
export async function nativeAvailableSlots(db:MongoDatabase,actorId:string,params:URLSearchParams){const providerId=params.get('dietitianId')||params.get('providerId')||actorId,{provider,availability}=await nativeProviderAvailability(db,actorId,providerId),date=params.get('date');if(!date||!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new NativeStaffClientError('Valid date required');let duration=Number(params.get('duration')||60);if(params.get('appointmentTypeId')){const id=params.get('appointmentTypeId')!;if(!/^[a-f0-9]{24}$/.test(id))throw new NativeStaffClientError('Invalid appointment type');const type=await db.collection('appointmenttypes').doc(id).get();if(!type.exists)throw new NativeStaffClientError('Appointment type not found',404);duration=Number(type.get('duration')||duration);}if(!Number.isInteger(duration)||duration<15||duration>180)throw new NativeStaffClientError('Invalid duration');
 const timezone=isValidMealTimeZone(provider.get('timezone'))?provider.get('timezone'):TASK_TIME_ZONE,start=scheduledTaskTime(date,'00:00',timezone);if(start===null)throw new NativeStaffClientError('Invalid date');const tomorrow=new Date(Date.parse(date+'T12:00:00Z')+86400000).toISOString().slice(0,10),end=scheduledTaskTime(tomorrow,'00:00',timezone)!,day=new Date(date+'T12:00:00Z').getUTCDay(),dayName=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][day];
 const schedules=[...(provider.get('availability')||[]).filter((s:any)=>s.day===dayName&&s.isActive!==false),...availability.filter(s=>s.dayOfWeek===day)];const rows=await db.collection('appointments').where('dietitian','==',providerId).where('status','in',['scheduled','confirmed','rescheduled','in-progress']).where('scheduledAt','>=',new Date(start-180*60000)).where('scheduledAt','<',new Date(end)).select('scheduledAt','duration').get();const appointments=rows.docs.map(d=>nativeDates(d.data())),slots=new Map<string,DocumentData>();
 for(const schedule of schedules){const from=scheduledTaskTime(date,schedule.startTime,timezone),to=scheduledTaskTime(date,schedule.endTime,timezone);if(from===null||to===null||to<=from)continue;for(let when=from;when+duration*60000<=to;when+=duration*60000){const time=formatInTimeZone(when,timezone,'HH:mm'),endTime=formatInTimeZone(when+duration*60000,timezone,'HH:mm'),lunch=minutes(time)<15*60&&minutes(endTime)>14*60,conflict=appointments.some(a=>a.scheduledAt.getTime()<when+duration*60000&&a.scheduledAt.getTime()+Number(a.duration||60)*60000>when),past=when<=Date.now(),reason=past?'Time has passed':lunch?'Lunch break':conflict?'Already booked':null;slots.set(time,{time,endTime,available:!reason,...(reason?{conflictReason:reason}:{})});}}
 const sorted=[...slots.values()].sort((a,b)=>a.time.localeCompare(b.time));return {date,providerId,providerName:[provider.get('firstName'),provider.get('lastName')].filter(Boolean).join(' '),duration,lunchBreak:{start:'14:00',end:'15:00',message:'Appointments are not available during lunch break (2:00 PM - 3:00 PM)'},slots:sorted,availableSlots:sorted.filter(s=>s.available).map(s=>s.time),timezone,availability:nativeJson(availability)};
}
export async function saveProviderAvailability(db:MongoDatabase,actorId:string,input:any,remove=false){
 const slots=remove?[]:z.array(schema).min(1).max(100).parse(input?.slots);for(const s of slots)if(minutes(s.endTime)<=minutes(s.startTime))throw new NativeStaffClientError('End time must be after start time');for(let i=0;i<slots.length;i++)for(let j=i+1;j<slots.length;j++)if(slots[i].dayOfWeek===slots[j].dayOfWeek&&minutes(slots[i].startTime)<minutes(slots[j].endTime)&&minutes(slots[i].endTime)>minutes(slots[j].startTime))throw new NativeStaffClientError('Availability slots overlap');
 let count=0;await db.runTransaction(async tx=>{const actor=await tx.get(db.collection('users').doc(actorId));if(!actor.exists||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false)||!['admin','dietitian','health_counselor'].includes(actor.get('role')))throw new NativeStaffClientError('Staff access required',403);let providerId=input?.providerId||actorId,slot:MongoTypes.DocumentSnapshot|undefined;if(remove&&input?.id){if(!/^[a-f0-9]{24}$/.test(input.id))throw new NativeStaffClientError('Invalid slot ID');slot=await tx.get(db.collection('provideravailabilities').doc(input.id));if(!slot.exists)throw new NativeStaffClientError('Slot not found',404);providerId=slot.get('providerId');}if(!/^[a-f0-9]{24}$/.test(providerId))throw new NativeStaffClientError('Invalid provider');if(actor.get('role')!=='admin'&&providerId!==actorId)throw new NativeStaffClientError('You can only change your own availability',403);const provider=await tx.get(db.collection('users').doc(providerId));if(!provider.exists||!['dietitian','health_counselor'].includes(provider.get('role')))throw new NativeStaffClientError('Provider not found',404);const rows=slot?[slot]:(await tx.get(db.collection('provideravailabilities').where('providerId','==',providerId))).docs;if(rows.length+slots.length>450)throw new NativeStaffClientError('Availability requires batch reconciliation',409);for(const row of rows)tx.delete(row.ref);const now=new Date();for(const s of slots){const ref=db.collection('provideravailabilities').doc(randomBytes(12).toString('hex'));tx.create(ref,{...s,_id:ref.id,providerId,providerRole:provider.get('role'),createdAt:now,updatedAt:now});}count=slots.length;});return {message:remove?'Availability deleted successfully':'Availability updated successfully',slotsCount:count};
}
