import {Filter,type Firestore,type DocumentData} from 'firebase-admin/firestore';
import {nativeDates} from './native-plan-editor';
import {directoryFields,filterFields,nativeDirectoryProfile,populateNativeDirectory,nativeDirectoryStatuses,NativeDirectoryError} from './native-client-directory';
import {nativeHabitDay} from './native-habits';
function boundary(value:string|null,end=false){if(!value)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new NativeDirectoryError('Invalid filter date');const d=new Date(value+`T${end?'23:59:59.999':'00:00:00.000'}+05:30`);if(!Number.isFinite(d.getTime()))throw new NativeDirectoryError('Invalid filter date');return d;}
async function related(db:Firestore,collection:string,field:string,ids:string[],fields:string[],from?:Date|null,to?:Date|null){const result:DocumentData[]=[];for(let b=0;b<ids.length;b+=180)await Promise.all(Array.from({length:Math.min(6,Math.ceil((ids.length-b)/30))},async(_,slot)=>{let q:FirebaseFirestore.Query=db.collection(collection).where(field,'in',ids.slice(b+slot*30,b+slot*30+30));if(from)q=q.where('createdAt','>=',from);if(to)q=q.where('createdAt','<=',to);const docs=await q.select(...fields).get();result.push(...docs.docs.map(d=>({_id:d.id,...nativeDates(d.data())})));}));return result;}
export async function nativeUserClientList(db:Firestore,actorId:string,p:URLSearchParams){
 const actor=await db.collection('users').doc(actorId).get();if(actor.get('status')!=='active'||!['admin','dietitian','health_counselor'].includes(actor.get('role')))throw new NativeDirectoryError('Staff access required',403);let effectiveId=actorId,effectiveRole=actor.get('role');if(p.get('viewAs')){if(effectiveRole!=='admin')throw new NativeDirectoryError('Only administrators may use staff view',403);const id=p.get('viewAs')!;if(!/^[a-f0-9]{24}$/i.test(id))throw new NativeDirectoryError('Invalid staff ID');const target=await db.collection('users').doc(id).get();if(!target.exists||!['dietitian','health_counselor'].includes(target.get('role')))throw new NativeDirectoryError('Staff member not found',404);effectiveId=id;effectiveRole=target.get('role');}
 const page=Number(p.get('page')||1),limit=Math.min(100,Number(p.get('limit')||100));if(!Number.isSafeInteger(page)||page<1||!Number.isSafeInteger(limit)||limit<1)throw new NativeDirectoryError('Invalid pagination');let q:FirebaseFirestore.Query=db.collection('users').where('role','==','client');if(effectiveRole!=='admin'){const primary=effectiveRole==='dietitian'?'assignedDietitian':'assignedHealthCounselor',secondary=effectiveRole==='dietitian'?'assignedDietitians':'assignedHealthCounselors';q=q.where(Filter.or(Filter.where(primary,'==',effectiveId),Filter.where(secondary,'array-contains',effectiveId)));}
 for(const [parameter,field,op] of [['primaryDietitian','assignedDietitian','=='],['secondaryDietitian','assignedDietitians','array-contains'],['tagId','tags','array-contains']] as const){const value=p.get(parameter);if(value){if(!/^[a-f0-9]{24}$/i.test(value))throw new NativeDirectoryError('Invalid filter ID');q=q.where(field,op,value);}}
 const dates=Object.fromEntries(['dtAssignedFrom','dtAssignedTo','hcAssignedFrom','hcAssignedTo','planDurationFrom','planDurationTo','lastActivityHCFrom','lastActivityHCTo','lastActivityDTFrom','lastActivityDTTo'].map(k=>[k,boundary(p.get(k),k.endsWith('To'))]));
 const search=(p.get('search')||'').trim().toLowerCase(),status=p.get('status'),planName=(p.get('planName')||'').trim().toLowerCase(),duration=p.get('planDuration'),planStatus=p.get('planStatus'),shared=p.get('planShared');
 const needsFilter=search||status||planName||duration||planStatus||shared||Object.values(dates).some(Boolean);let rows:DocumentData[],total:number;
 if(!needsFilter){const [count,docs]=await Promise.all([q.count().get(),q.orderBy('firstName').orderBy('lastName').offset((page-1)*limit).limit(limit).select(...directoryFields).get()]);total=count.data().count;rows=docs.docs.map(d=>nativeDirectoryProfile(d.id,d.data()));}
 else{
  const candidate=await q.select(...filterFields,'tags').get();rows=candidate.docs.map(d=>({_id:d.id,...nativeDates(d.data())}));
  rows=rows.filter(d=>{for(const [prefix,field] of [['dt','assignedDietitian'],['hc','assignedHealthCounselor']]){const from=dates[prefix+'AssignedFrom'],to=dates[prefix+'AssignedTo'];if((from||to)&&(!d[field]||!d.createdAt||from&&d.createdAt<from||to&&d.createdAt>to))return false;}return true;});
  if(planName||search||duration||planStatus||shared){const ids=rows.map(d=>d._id),plans=await related(db,'clientmealplans','clientId',ids,['clientId','name','status','startDate','endDate','isDeleted']),payments=planName||search?await related(db,'unifiedpayments','client',ids,['client','planName']):[];const byClient=new Map<string,DocumentData[]>();for(const plan of plans)if(!plan.isDeleted)byClient.set(plan.clientId,[...(byClient.get(plan.clientId)||[]),plan]);const nameMatch=(id:string,name:string)=>(byClient.get(id)||[]).some(d=>String(d.name||'').toLowerCase().includes(name))||payments.some(d=>d.client===id&&String(d.planName||'').toLowerCase().includes(name));const today=nativeHabitDay(undefined).start;
   rows=rows.filter(d=>{const plans=byClient.get(d._id)||[];if(planName&&!nameMatch(d._id,planName))return false;if(search&&!['_id','firstName','lastName','email','phone','clientId'].some(k=>String(d[k]||'').toLowerCase().includes(search))&&!`${d.firstName||''} ${d.lastName||''}`.toLowerCase().includes(search)&&!nameMatch(d._id,search))return false;if(duration==='ongoing'&&!plans.some(d=>d.status==='active'&&d.endDate>=today))return false;if(duration==='dateRange'&&!plans.some(d=>(!dates.planDurationFrom||d.startDate>=dates.planDurationFrom)&&(!dates.planDurationTo||d.endDate<=dates.planDurationTo)))return false;if(planStatus&&!plans.some(d=>d.status===planStatus))return false;const hasShared=plans.some(d=>d.status!=='draft');if(shared==='yes'&&!hasShared||shared==='no'&&hasShared)return false;return true;});
  }
  for(const [prefix,staffRole] of [['HC','health_counselor'],['DT','dietitian']]){const from=dates['lastActivity'+prefix+'From'],to=dates['lastActivity'+prefix+'To'];if(from||to){const staff=await db.collection('users').where('role','==',staffRole).select().get(),staffIds=new Set(staff.docs.map(d=>d.id)),messages=await related(db,'messages','receiver',rows.map(d=>d._id),['receiver','sender','createdAt'],from,to),matches=new Set(messages.filter(d=>staffIds.has(d.sender)).map(d=>d.receiver));rows=rows.filter(d=>matches.has(d._id));}}
  if(status){rows=await nativeDirectoryStatuses(db,rows);rows=rows.filter(d=>d.clientStatus===status);}rows.sort((a,b)=>`${a.firstName||''} ${a.lastName||''}`.localeCompare(`${b.firstName||''} ${b.lastName||''}`)||a._id.localeCompare(b._id));total=rows.length;const ids=rows.slice((page-1)*limit,page*limit).map(d=>d._id);rows=ids.length?(await db.getAll(...ids.map(id=>db.collection('users').doc(id)),{fieldMask:[...directoryFields]})).filter(d=>d.exists).map(d=>nativeDirectoryProfile(d.id,d.data()!)):[];
 }
 const plans=await related(db,'clientmealplans','clientId',rows.map(d=>d._id),['clientId','name','status','startDate','endDate','updatedAt','isDeleted']);const today=nativeHabitDay(undefined).start;rows=await nativeDirectoryStatuses(db,rows);for(const row of rows){const clientPlans=plans.filter(p=>p.clientId===row._id&&!p.isDeleted).sort((a,b)=>new Date(a.startDate).getTime()-new Date(b.startDate).getTime()),last=clientPlans.at(-1),active=clientPlans.find(p=>p.status==='active'&&p.endDate>=today);Object.assign(row,{programStart:clientPlans[0]?.startDate||null,programEnd:last?.endDate||null,lastDiet:last?.name||null,mealPlanStartDate:active?.startDate||null,mealPlanEndDate:active?.endDate||null,activePlanName:active?.name||null});}
 const tags=[...new Set<string>(rows.flatMap(d=>d.tags||[]))],tagMap=new Map<string,DocumentData>();if(tags.length)for(let i=0;i<tags.length;i+=100)for(const t of await db.getAll(...tags.slice(i,i+100).map(id=>db.collection('tags').doc(id)),{fieldMask:['name','color','icon']}))if(t.exists)tagMap.set(t.id,{_id:t.id,...t.data()});for(const row of rows)row.tags=(row.tags||[]).map((id:string)=>tagMap.get(id)).filter(Boolean);
 return {clients:await populateNativeDirectory(db,rows),pagination:{page,limit,total,pages:Math.ceil(total/limit)}};
}
