import {randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {NativePlanEditor} from './native-plan-editor';
import {nativeClientAccess} from './native-admin-client-profile';
import {NativeDirectoryError,nativeDirectoryProfile,populateNativeDirectory} from './native-client-directory';
const id=z.string().regex(/^[a-f0-9]{24}$/i),optionalId=z.union([id,z.literal(''),z.null()]).optional(),ids=z.array(id).max(100).optional();
const schema=z.object({action:z.enum(['primary_secondary','add','remove','transfer','replace']).optional(),mode:z.enum(['primary_secondary','add','remove','transfer','replace']).optional(),dietitianId:optionalId,dietitianIds:ids,healthCounselorId:z.union([id,z.literal(''),z.null(),z.object({id,action:z.enum(['add','remove'])})]).optional(),healthCounselorIds:ids,primaryDietitianId:optionalId,secondaryDietitianIds:ids,primaryHealthCounselorId:optionalId,secondaryHealthCounselorIds:ids});
export async function assignNativeClient(db:MongoDatabase,actorId:string,clientId:string,input:unknown,permissionBased=false){
 const parsed=schema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid assignment');const b=parsed.data,action=b.action||b.mode||'replace';
 for(let attempt=0;attempt<5;attempt++){
  const editor=new NativePlanEditor(db);const {client,actor}=await nativeClientAccess(editor,actorId,clientId,!permissionBased);
  const hasDt=['dietitianId','dietitianIds','primaryDietitianId','secondaryDietitianIds'].some(key=>Object.hasOwn(b,key)),hasHc=['healthCounselorId','healthCounselorIds','primaryHealthCounselorId','secondaryHealthCounselorIds'].some(key=>Object.hasOwn(b,key));
  if(actor.role!=='admin'){for(const [needed,key] of [[hasDt,'assign_clients_to_dietitians'],[hasHc,'assign_clients_to_health_counselors']] as const){if(!needed)continue;const permissions=await editor.query('permissions',[['key','==',key],['isActive','==',true]]),permission=permissions.length===1?permissions[0]:null;if(!permission||permission.deniedUsers?.includes(actorId)||!permission.allowedUsers?.includes(actorId)&&!permission.allowedRoles?.includes(actor.role))throw new NativeDirectoryError('Assignment permission denied',403);}
   if(actor.role==='health_counselor'&&hasDt){if(action==='remove'||action==='transfer'||action==='add'&&client.assignedDietitian||b.dietitianIds&&b.dietitianIds.length>1||b.secondaryDietitianIds!==undefined)throw new NativeDirectoryError('Only primary dietitian assignment is permitted',403);}}
  const patch:DocumentData={};
  const assign=(primary:string,secondary:string,incoming:string[],mode:string)=>{let p=client[primary]||null,s=[...new Set<string>((client[secondary]||[]).filter((v:unknown)=>typeof v==='string'))];if(mode==='add'){s=[...new Set([...s,...incoming])];p=p||incoming[0]||null;}else if(mode==='remove'){s=s.filter(v=>!incoming.includes(v));if(incoming.includes(p))p=s[0]||null;}else if(mode==='transfer'){s=[...new Set([...s,...(p?[p]:[])])];p=incoming[0]||null;}else{p=incoming[0]||null;s=[...new Set([...s,...incoming.slice(1)])];}patch[primary]=p;patch[secondary]=s.filter(v=>v!==p);};
  if(action==='primary_secondary'){if(hasDt){patch.assignedDietitian=b.primaryDietitianId||null;patch.assignedDietitians=[...new Set(b.secondaryDietitianIds??client.assignedDietitians??[])].filter(v=>v!==patch.assignedDietitian);}if(hasHc){patch.assignedHealthCounselor=b.primaryHealthCounselorId||null;patch.assignedHealthCounselors=[...new Set(b.secondaryHealthCounselorIds??client.assignedHealthCounselors??[])].filter(v=>v!==patch.assignedHealthCounselor);}}
  else{if(b.dietitianId!==undefined||b.dietitianIds!==undefined)assign('assignedDietitian','assignedDietitians',b.dietitianIds||(b.dietitianId?[b.dietitianId]:[]),action);if(b.healthCounselorIds!==undefined||b.healthCounselorId!==undefined){const hc=b.healthCounselorId;assign('assignedHealthCounselor','assignedHealthCounselors',b.healthCounselorIds||(typeof hc==='object'&&hc?[hc.id]:hc?[hc as string]:[]),typeof hc==='object'&&hc?hc.action:action);}}
  if(!Object.keys(patch).length)throw new NativeDirectoryError('No assignment fields supplied');
  for(const [primary,secondary,role] of [['assignedDietitian','assignedDietitians','dietitian'],['assignedHealthCounselor','assignedHealthCounselors','health_counselor']]){for(const id of [...new Set([patch[primary],...(patch[secondary]||[])].filter(Boolean))]){const staff=await editor.document('users',id);if(!staff||staff.role!==role||staff.status!=='active')throw new NativeDirectoryError('Assigned professional must have an active matching staff role');}}
  const mutations:Array<{collection:string;id:string;patch:DocumentData}>=[{collection:'users',id:clientId,patch}];
  if(patch.assignedDietitian!==undefined){const payments=await editor.query('unifiedpayments',[['client','==',clientId]]);for(const p of payments)if(['active','pending','on_hold','paid'].includes(p.status))mutations.push({collection:'unifiedpayments',id:p._id,patch:{dietitian:patch.assignedDietitian}});}
  const eventId=randomBytes(12).toString('hex'),now=new Date();const event={_id:eventId,userId:actorId,userRole:actor.role,action:'Updated Client Assignment',actionType:'assign',category:'client_assignment',targetUserId:clientId,description:action,createdAt:now,updatedAt:now};
  if(await editor.commit(mutations,[{collection:'activitylogs',id:eventId,data:event},{collection:'_nativeOutbox',id:'assignment-'+eventId,data:{type:'assignment-changed',clientId,actorId,before:{assignedDietitian:client.assignedDietitian||null,assignedDietitians:client.assignedDietitians||[],assignedHealthCounselor:client.assignedHealthCounselor||null,assignedHealthCounselors:client.assignedHealthCounselors||[]},after:patch,status:'pending',createdAt:now}}]))return {success:true,message:'Assignment updated successfully',client:(await populateNativeDirectory(db,[nativeDirectoryProfile(clientId,{...client,...patch})]))[0]};
 }
 throw new NativeDirectoryError('Client changed while saving. Please retry.',409);
}
export async function nativeAssignmentOptions(db:MongoDatabase,actorId:string,clientId:string){const editor=new NativePlanEditor(db),{actor,client}=await nativeClientAccess(editor,actorId,clientId);const allows=async(key:string)=>{if(actor.role==='admin')return true;const rows=await editor.query('permissions',[['key','==',key],['isActive','==',true]]);if(rows.length!==1)return false;const permission=rows[0];return !permission.deniedUsers?.includes(actorId)&&(permission.allowedUsers?.includes(actorId)||permission.allowedRoles?.includes(actor.role))===true;};const [canAssignDietitians,canAssignHealthCounselors]=await Promise.all([allows('assign_clients_to_dietitians'),allows('assign_clients_to_health_counselors')]);if(!canAssignDietitians&&!canAssignHealthCounselors)throw new NativeDirectoryError('Permission denied',403);const result:DocumentData={permissions:{canAssignDietitians,canAssignHealthCounselors}};for(const [enabled,role,key] of [[canAssignDietitians,'dietitian','dietitians'],[canAssignHealthCounselors,'health_counselor','healthCounselors']] as const){if(!enabled)continue;const rows=await db.collection('users').where('role','==',role).where('status','==','active').select('firstName','lastName','email','avatar','phone').get();result[key]=rows.docs.map(doc=>({_id:doc.id,...doc.data(),...(actor.role==='health_counselor'&&role==='dietitian'?{isPrimary:doc.id===client.assignedDietitian,isSecondary:(client.assignedDietitians||[]).includes(doc.id)}:{})}));}if(actor.role==='health_counselor'){result.primaryDietitianOnly=true;result.assignmentMessage='Health Counselors can only assign to Primary Dietitian';}return result;}
