import type * as MongoTypes from '@/lib/db/mongo-types';
import {Filter,type MongoDatabase,type DocumentData} from '@/lib/db/mongo-types';
import {NativeDirectoryError} from './native-client-directory';
export async function nativeUserChatPicker(db:MongoDatabase,actorId:string,p:URLSearchParams){const actor=await db.collection('users').doc(actorId).get(),role=actor.get('role');if(actor.get('status')!=='active')throw new NativeDirectoryError('Access denied',403);const bulk=p.get('forBulkMessage')==='true',requested=Number(p.get('limit')||100),limit=Math.min(500,requested),search=(p.get('search')||'').trim().toLowerCase();if(!Number.isSafeInteger(limit)||limit<1)throw new NativeDirectoryError('Invalid limit');let q:MongoTypes.Query=db.collection('users');
 if(bulk&&role==='client')throw new NativeDirectoryError('Staff access required',403);if(role==='client'){const id=actor.get('assignedDietitian');if(!id)return {users:[],total:0};q=q.where('__name__','==',id);}else if(role==='dietitian'||role==='health_counselor'){const primary=role==='dietitian'?'assignedDietitian':'assignedHealthCounselor',secondary=role==='dietitian'?'assignedDietitians':'assignedHealthCounselors',assigned=Filter.or(Filter.where(primary,'==',actorId),Filter.where(secondary,'array-contains',actorId));q=q.where(bulk?assigned:Filter.or(assigned,Filter.where('role','in',['admin','dietitian','health_counselor'])));}else if(role!=='admin')throw new NativeDirectoryError('Access denied',403);
 if(bulk)q=q.where('role','==','client');else if(p.get('role'))q=q.where('role','==',p.get('role'));
 // Literal substring search needs a minimal directory projection; no medical or credential fields are read.
 if(!search)q=q.orderBy('firstName').limit(limit+1);const docs=await q.select('firstName','lastName','email','avatar','role','clientStatus').get();let users:DocumentData[]=docs.docs.filter(d=>d.id!==actorId).map(d=>({_id:d.id,...d.data()}));if(search)users=users.filter(d=>[d.firstName,d.lastName,d.email,`${d.firstName||''} ${d.lastName||''}`].some(v=>String(v||'').toLowerCase().includes(search)));users.sort((a,b)=>`${a.firstName||''} ${a.lastName||''}`.localeCompare(`${b.firstName||''} ${b.lastName||''}`));users=users.slice(0,limit);
 if(!bulk){const existing=new Set<string>(),ids=users.map(d=>d._id);for(let i=0;i<ids.length;i+=30){const part=ids.slice(i,i+30);const [sent,received]=await Promise.all([db.collection('messages').where('sender','==',actorId).where('receiver','in',part).select('receiver').get(),db.collection('messages').where('receiver','==',actorId).where('sender','in',part).select('sender').get()]);for(const d of sent.docs)existing.add(d.get('receiver'));for(const d of received.docs)existing.add(d.get('sender'));}users=users.map(d=>({...d,hasExistingConversation:existing.has(d._id)}));}
 return {users,total:users.length};}
