import {randomBytes} from 'node:crypto';
import {Filter,type Firestore,type Query,type DocumentData} from 'firebase-admin/firestore';
import {z} from 'zod';
import {NativeDirectoryError} from './native-client-directory';
import {NativePlanEditor,nativeDates} from './native-plan-editor';
import {nativeUserRecordAccess} from './native-user-documents';
import {startOfTodayIST} from '@/lib/utils/ist';
export async function readNativeActivities(db:Firestore,actorId:string,params:URLSearchParams){
 const actor=await db.collection('users').doc(actorId).get();if(actor.get('status')!=='active')throw new NativeDirectoryError('Access denied',403);const admin=actor.get('role')==='admin',userId=params.get('userId'),role=actor.get('role');let scopes:string[]|null=admin?null:[actorId];
 if(userId){await nativeUserRecordAccess(new NativePlanEditor(db),actorId,userId);scopes=[userId];}else if(['dietitian','health_counselor'].includes(role)){const key=role==='dietitian'?'assignedDietitian':'assignedHealthCounselor',clients=await db.collection('users').where('role','==','client').where(Filter.or(Filter.where(key,'==',actorId),Filter.where(key+'s','array-contains',actorId))).select().get();scopes=[actorId,...clients.docs.map(d=>d.id)];}else if(!admin&&role!=='client')throw new NativeDirectoryError('Access denied',403);
 const limit=Math.min(200,Math.max(1,Math.floor(Number(params.get('limit'))||50))),page=Math.max(1,Math.floor(Number(params.get('page'))||1));let query:Query=db.collection('activitylogs');for(const key of ['category','actionType',...(admin?['userRole']:[])])if(params.get(key))query=query.where(key,'==',params.get(key));for(const [key,op] of [['startDate','>='],['endDate','<=']] as const)if(params.get(key)){const date=new Date(params.get(key)!);if(!Number.isFinite(date.getTime()))throw new NativeDirectoryError('Invalid date');query=query.where('createdAt',op,date);}
 const fields=['category','actionType','userRole','createdAt','action','description','userName','targetUserName','resourceName'];const found=new Map<string,DocumentData>();if(scopes){for(let i=0;i<scopes.length;i+=90)await Promise.all(Array.from({length:Math.min(6,Math.ceil((scopes.length-i)/15))},async(_,slot)=>{const ids=scopes!.slice(i+slot*15,i+(slot+1)*15),rows=await query.where(Filter.or(Filter.where('userId','in',ids),Filter.where('targetUserId','in',ids))).select(...fields).get();rows.docs.forEach(doc=>found.set(doc.id,{...nativeDates(doc.data()),_id:doc.id}));}));}else{const rows=await query.select(...fields).get();rows.docs.forEach(doc=>found.set(doc.id,{...nativeDates(doc.data()),_id:doc.id}));}
 const term=params.get('search')?.trim().toLowerCase(),rows=[...found.values()].filter(row=>!term||['action','description','userName','targetUserName','resourceName'].some(k=>String(row[k]||'').toLowerCase().includes(term))).sort((a,b)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()),ids=rows.slice((page-1)*limit,page*limit).map(row=>row._id);
 const docs=ids.length?await db.getAll(...ids.map(id=>db.collection('activitylogs').doc(id))):[],activities=docs.map(doc=>{const {_nativeExternalFields,_nativeSource,...data}=nativeDates(doc.data());return {...data,_id:doc.id};});
 const statRows=admin?(await db.collection('activitylogs').select('category','actionType','userRole','createdAt').get()).docs.map(doc=>nativeDates(doc.data())):rows;const groups=(field:string)=>{const counts=new Map<string|null,number>();statRows.forEach(row=>counts.set(row[field]??null,(counts.get(row[field]??null)||0)+1));return [...counts].map(([_id,count])=>({_id,count}));};return {activities,pagination:{page,limit,total:rows.length,totalPages:Math.ceil(rows.length/limit)},stats:{byCategory:groups('category'),byActionType:groups('actionType'),byUserRole:groups('userRole'),todayCount:statRows.filter(row=>new Date(row.createdAt)>=startOfTodayIST()).length}};
}
const schema=z.object({action:z.string().trim().min(1).max(500),actionType:z.string().max(100),category:z.string().max(100),description:z.string().max(4000).optional(),targetUserId:z.string().regex(/^[a-f0-9]{24}$/i).optional(),resourceId:z.string().max(100).optional(),resourceName:z.string().max(500).optional()});
export async function createNativeActivity(db:Firestore,actorId:string,input:unknown){const parsed=schema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid activity');for(let i=0;i<5;i++){const editor=new NativePlanEditor(db),{actor,user}=await nativeUserRecordAccess(editor,actorId,parsed.data.targetUserId||actorId),id=randomBytes(12).toString('hex'),now=new Date(),activity={...parsed.data,_id:id,userId:actorId,userRole:actor.role,userName:[actor.firstName,actor.lastName].filter(Boolean).join(' '),userEmail:actor.email||'',...(parsed.data.targetUserId?{targetUserName:[user.firstName,user.lastName].filter(Boolean).join(' ')}:{}),isRead:false,createdAt:now,updatedAt:now};if(await editor.commit([],[{collection:'activitylogs',id,data:activity}]))return {activity};}throw new NativeDirectoryError('Activity changed; retry',409);}
export async function pruneNativeActivities(db:Firestore,actorId:string,daysOld:number){if(!Number.isInteger(daysOld)||daysOld<1||daysOld>36500)throw new NativeDirectoryError('Invalid retention days');const cutoff=new Date(Date.now()-daysOld*86400000);let deleted=0;for(;;){const count=await db.runTransaction(async tx=>{const actor=await tx.get(db.collection('users').doc(actorId));if(actor.get('role')!=='admin'||actor.get('status')!=='active')throw new NativeDirectoryError('Forbidden',403);const rows=await tx.get(db.collection('activitylogs').where('createdAt','<',cutoff).limit(100));for(const doc of rows.docs){tx.set(db.collection('_nativeArchivedActivities').doc(doc.id),{...doc.data(),archivedAt:new Date(),archivedBy:actorId});tx.delete(doc.ref);}return rows.size;});deleted+=count;if(count<100)break;}return {message:`Deleted ${deleted} activity logs older than ${daysOld} days`};}
