import type * as MongoTypes from '@/lib/db/mongo-types';
import {createHash,randomBytes} from 'node:crypto';
import bcrypt from 'bcryptjs';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {nativeAdminCatalog,normalizeCatalogRow} from './native-admin-data';
import {modelRegistry} from '@/lib/import/modelRegistry';
import {NativeDirectoryError} from './native-client-directory';
import {prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {validatePhoneNumber} from '@/lib/validations/contact';
import {nativePhoneVariations} from './native-registration';
/** The complete submitted import is committed atomically; oversized imports are rejected before writing. */
export async function saveNativeAdminImport(db:MongoDatabase,actorId:string,operationId:string,groups:Array<{modelName:string;rows:DocumentData[]}>){
 const entries=groups.flatMap(group=>group.rows.map(input=>({model:nativeAdminCatalog(group.modelName),input})));if(!entries.length||entries.length>100)throw new NativeDirectoryError('Submit between 1 and 100 records per atomic import');
 const prepared=await Promise.all(entries.map(async({model,input})=>{if(!model.importable)throw new NativeDirectoryError('This collection is not importable');const data=normalizeCatalogRow(model,input,true);if(model.name==='User'){data.password=await bcrypt.hash(randomBytes(32).toString('base64url'),12);data.role=data.role||'client';data.status=data.status||'active';if(data.email)data.email=String(data.email).trim().toLowerCase();if(data.phone){const phone=validatePhoneNumber(String(data.phone),'+91');if(!phone.isValid||!phone.normalized)throw new NativeDirectoryError('Invalid imported phone');data.phone=phone.normalized;}if(!data.phone&&!data.email)throw new NativeDirectoryError('Imported users need phone or email');}
 const validation=await modelRegistry.validateRow(model.name,data,0);if(!validation.isValid)throw new NativeDirectoryError(validation.errors.map(e=>`${e.field}: ${e.message}`).join('; '));return {model,data,id:randomBytes(12).toString('hex')};}));
 const opRef=db.collection('_nativeImportOperations').doc(createHash('sha256').update(actorId+'\0'+operationId).digest('hex')),fingerprint=createHash('sha256').update(JSON.stringify(groups)).digest('hex');
 return db.runTransaction(async tx=>{const [actor,operation]=await tx.getAll(db.collection('users').doc(actorId),opRef);if(actor.get('role')!=='admin'||actor.get('status')!=='active')throw new NativeDirectoryError('Forbidden',403);if(operation.exists){if(operation.get('fingerprint')!==fingerprint)throw new NativeDirectoryError('Import ID already used for different data',409);return operation.get('result');}
 const counterRef=db.collection('_nativeCounters').doc('clientIds'),needCounter=prepared.some(p=>p.model.name==='User'&&p.data.role==='client'),counter=needCounter?await tx.get(counterRef):null;let sequence=counter?.get('seq');if(needCounter&&(!Number.isSafeInteger(sequence)||sequence<0))throw new NativeDirectoryError('Client counter requires reconciliation',503);
 const writes:Array<{ref:MongoTypes.DocumentReference;data:DocumentData;update:boolean}>=[],claims:Array<{ref:MongoTypes.DocumentReference;data:DocumentData}>=[],seen=new Set<string>(),savedCounts:Record<string,number>={};const now=new Date();
 for(const entry of prepared){const {model}=entry;const data:DocumentData={...entry.data,createdAt:now,updatedAt:now};let id=entry.id,existing:MongoTypes.DocumentSnapshot|undefined;if(['MedicalInfo','LifestyleInfo'].includes(model.name)){const found=await tx.get(db.collection(model.collection).where('userId','==',data.userId).limit(2));if(found.size>1)throw new NativeDirectoryError('Duplicate existing form requires reconciliation',409);existing=found.docs[0];if(existing)id=existing.id;}
 if(model.name==='User'&&data.role==='client')data.clientId='C-'+(++sequence);
 const rowKey=model.collection+'/'+id;if(seen.has(rowKey))throw new NativeDirectoryError('Duplicate record in import');seen.add(rowKey);
 for(const index of model.uniqueIndexes||[]){const values=index.fields.map(k=>k.split('.').reduce((o:any,part)=>o?.[part],data));if(values.some(v=>v==null||v==='')&&(index.sparse||index.partial))continue;const signature=model.collection+'\0'+index.fields.join(',')+'\0'+JSON.stringify(values);if(seen.has(signature))throw new NativeDirectoryError('Duplicate unique value within import',409);seen.add(signature);let query:MongoTypes.Query=db.collection(model.collection);index.fields.forEach((field,i)=>query=query.where(field,'==',values[i]??null));const matches=await tx.get(query.limit(2));if(matches.docs.some(doc=>doc.id!==id))throw new NativeDirectoryError('Duplicate existing record',409);
 const contact=model.name==='User'&&index.fields.length===1&&['email','phone'].includes(index.fields[0]),ref=contact?db.collection('_nativeUserKeys').doc(createHash('sha256').update(index.fields[0]+'\0'+values[0]).digest('hex')):db.collection('_nativeImportUniqueKeys').doc(createHash('sha256').update(signature).digest('hex'));const claim=await tx.get(ref);if(claim.exists&&(claim.get('userId')||claim.get('recordId'))!==id)throw new NativeDirectoryError('Unique value is already reserved',409);if(!claim.exists)claims.push({ref,data:contact?{userId:id,createdAt:now}:{recordId:id,collection:model.collection,createdAt:now}});
 }
 if(model.name==='User'&&data.phone){const duplicates=await tx.get(db.collection('users').where('phone','in',nativePhoneVariations(data.phone)));if(!duplicates.empty)throw new NativeDirectoryError('Phone is already registered',409);}
 for(const field of model.fields.filter(f=>f.ref&&!f.path.includes('.'))){const target=modelRegistry.get(field.ref!);if(!target)continue;const values=Array.isArray(data[field.path])?data[field.path]:[data[field.path]];for(const value of values.filter(Boolean)){if(typeof value!=='string'||value.includes('/'))throw new NativeDirectoryError('Invalid reference');const found=await tx.get(db.collection(target.collection).doc(value));if(!found.exists)throw new NativeDirectoryError(`Referenced ${field.ref} does not exist`);}}
 const ref=db.collection(model.collection).doc(id);if(!existing){const found=await tx.get(ref);if(found.exists)throw new NativeDirectoryError('Record already exists',409);}writes.push({ref,data:existing?await prepareNativePatch(existing.data()!,{...data,createdAt:existing.get('createdAt')||now}):await prepareNativeDocument({...data,_id:id}),update:!!existing});savedCounts[model.name]=(savedCounts[model.name]||0)+1;
 }
 if(writes.length+claims.length+3>450)throw new NativeDirectoryError('Import exceeds atomic write limit; use a smaller file');if(needCounter)tx.update(counterRef,{seq:sequence});writes.forEach(w=>w.update?tx.update(w.ref,w.data):tx.create(w.ref,w.data));claims.forEach(c=>tx.create(c.ref,c.data));const result={savedCounts,totalSaved:prepared.length};tx.create(opRef,{actorId,fingerprint,result,createdAt:now});return result;});
}
