import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {Firestore,DocumentData} from 'firebase-admin/firestore';
import {NativePlanEditor} from './native-plan-editor';
import {nativeUserRecordAccess} from './native-user-documents';
import {NativeDirectoryError} from './native-client-directory';
import {NOTE_TOPIC_TYPES} from '@/lib/constants/notes';
const schema=z.object({topicType:z.enum(NOTE_TOPIC_TYPES).optional(),date:z.string().optional(),content:z.string().trim().min(1).max(100000).optional(),showToClient:z.boolean().optional(),attachments:z.array(z.object({type:z.enum(['image','video','audio']),url:z.string().max(3000),filename:z.string().max(255).optional(),mimeType:z.string().max(100).optional(),size:z.number().min(0).max(100000000).optional()})).max(50).optional()});
async function populated(editor:NativePlanEditor,note:DocumentData){const creator=typeof note.createdBy==='string'?await editor.document('users',note.createdBy):null;return {_id:note._id,topicType:note.topicType||'General',date:note.date,content:note.content,showToClient:!!note.showToClient,attachments:note.attachments||[],createdAt:note.createdAt,createdBy:creator?{_id:creator._id,firstName:creator.firstName,lastName:creator.lastName}:null};}
export async function listNativeUserNotes(db:Firestore,actorId:string,userId:string){const editor=new NativePlanEditor(db);const {actor}=await nativeUserRecordAccess(editor,actorId,userId);const rows=await editor.query('clientnotes',[['client','==',userId]]);const notes=await Promise.all(rows.filter(n=>actor.role!=='client'||n.showToClient===true).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).map(async n=>populated(editor,await editor.hydrate(n))));return {success:true,notes,topicTypes:NOTE_TOPIC_TYPES};}
export async function saveNativeUserNote(db:Firestore,actorId:string,userId:string,input:unknown,noteId?:string,operationId?:string){
 const parsed=schema.safeParse(input);if(!parsed.success||!noteId&&!parsed.data.content)throw new NativeDirectoryError('Invalid note');if(operationId&&!/^[a-zA-Z0-9._:-]{8,128}$/.test(operationId))throw new NativeDirectoryError('Invalid idempotency key');const patch:DocumentData={...parsed.data};if(patch.date){patch.date=new Date(patch.date);if(!Number.isFinite(patch.date.getTime()))throw new NativeDirectoryError('Invalid note date');}const id=noteId||(operationId?createHash('sha256').update('note\0'+actorId+'\0'+userId+'\0'+operationId).digest('hex').slice(0,24):randomBytes(12).toString('hex')),fingerprint=createHash('sha256').update(JSON.stringify(parsed.data)).digest('hex');
 for(let attempt=0;attempt<5;attempt++){const editor=new NativePlanEditor(db);const {actor}=await nativeUserRecordAccess(editor,actorId,userId);if(!['admin','dietitian','health_counselor'].includes(actor.role))throw new NativeDirectoryError('Staff access required',403);const raw=await editor.document('clientnotes',id),current=raw?await editor.hydrate(raw):null;if(noteId&&(!current||current.client!==userId))throw new NativeDirectoryError('Note not found',404);if(current&&!noteId){if(current._nativeOperationHash!==fingerprint)throw new NativeDirectoryError('Idempotency key already used for another note',409);return {success:true,note:await populated(editor,current),replayed:true};}if(current&&actor.role==='health_counselor'&&current.createdBy!==actorId)throw new NativeDirectoryError('Only the author can update this note',403);
 for(const attachment of patch.attachments||[]){if((current?.attachments||[]).some((old:DocumentData)=>old.url===attachment.url))continue;const m=/^\/api\/files\/([a-f0-9]{24})$/i.exec(attachment.url);if(m){const file=await editor.document('files',m[1]);if(!file||file.deletedAt||![actorId,userId].includes(file.uploadedBy))throw new NativeDirectoryError('Attachment is not owned by this account',403);}else{let url:URL;try{url=new URL(attachment.url);}catch{throw new NativeDirectoryError('Invalid attachment URL');}if(url.protocol!=='https:'||!url.hostname.endsWith('.public.blob.vercel-storage.com'))throw new NativeDirectoryError('Attachments must use an uploaded Blob file');}}
 const now=new Date(),data={_id:id,client:userId,createdBy:actorId,topicType:'General',date:now,showToClient:false,attachments:[],createdAt:now,...patch,updatedAt:now,...(operationId?{operationId,_nativeOperationHash:fingerprint}:{})};if(await editor.commit(current?[{collection:'clientnotes',id,patch:{...patch,updatedAt:now}}]:[],current?[]:[{collection:'clientnotes',id,data}]))return {success:true,note:await populated(editor,current?{...current,...patch,updatedAt:now}:data)};
 }throw new NativeDirectoryError('Note changed while saving. Please retry.',409);
}
