import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {NativePlanEditor} from './native-plan-editor';
import {nativeUserRecordAccess} from './native-user-documents';
import {NativeDirectoryError} from './native-client-directory';
import {TASK_TYPES} from '@/lib/constants/tasks';
import {scheduledTaskTime,taskScheduleError,TASK_TIME_ZONE} from '@/lib/task-schedule';
import {formatInTimeZone} from 'date-fns-tz';
const schema=z.object({taskType:z.enum(TASK_TYPES).optional(),title:z.string().trim().max(500).optional(),description:z.string().max(2000).optional(),startDate:z.string().optional(),endDate:z.string().optional(),allottedTime:z.string().max(20).optional(),repeatFrequency:z.number().int().min(0).max(365).optional(),notifyClientOnChat:z.boolean().optional(),notifyDieticianOnCompletion:z.string().max(320).optional(),status:z.enum(['pending','in-progress','completed','cancelled']).optional(),tags:z.array(z.string().regex(/^[a-f0-9]{24}$/i)).max(1).optional()});
async function populate(editor:NativePlanEditor,task:DocumentData):Promise<DocumentData>{const dt=typeof task.dietitian==='string'?await editor.document('users',task.dietitian):null;const tags=await Promise.all((task.tags||[]).map(async(id:string)=>{const t=await editor.document('tags',id);return t?{_id:t._id,name:t.name,color:t.color,icon:t.icon}:null;}));const {_nativeOperationHash,_nativeExternalFields,_nativeSource,...safe}=task;return {...safe,dietitian:dt?{_id:dt._id,firstName:dt.firstName,lastName:dt.lastName,email:dt.email}:null,tags:tags.filter(Boolean)};}
export async function readNativeUserTasks(db:MongoDatabase,actorId:string,userId:string,taskId?:string){const editor=new NativePlanEditor(db);await nativeUserRecordAccess(editor,actorId,userId);if(taskId){const task=await editor.document('tasks',taskId);if(!task||task.client!==userId)throw new NativeDirectoryError('Task not found',404);return {task:await populate(editor,await editor.hydrate(task))};}const rows=await editor.query('tasks',[['client','==',userId]]);rows.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());const tasks=await Promise.all(rows.map(async row=>populate(editor,await editor.hydrate(row))));return {tasks,count:tasks.length};}
export async function saveNativeUserTask(db:MongoDatabase,actorId:string,userId:string,input:unknown,taskId?:string,operationId?:string){
 const parsed=schema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid task');if(operationId&&!/^[a-zA-Z0-9._:-]{8,128}$/.test(operationId))throw new NativeDirectoryError('Invalid idempotency key');const patch:DocumentData={...parsed.data};for(const k of ['startDate','endDate'])if(patch[k]){patch[k]=new Date(patch[k]);if(!Number.isFinite(patch[k].getTime()))throw new NativeDirectoryError('Invalid task date');}const id=taskId||(operationId?createHash('sha256').update('task\0'+actorId+'\0'+userId+'\0'+operationId).digest('hex').slice(0,24):randomBytes(12).toString('hex')),fingerprint=createHash('sha256').update(JSON.stringify(parsed.data)).digest('hex');
 for(let attempt=0;attempt<5;attempt++){const editor=new NativePlanEditor(db);const {actor}=await nativeUserRecordAccess(editor,actorId,userId);const raw=await editor.document('tasks',id),current=raw?await editor.hydrate(raw):null;if(taskId&&(!current||current.client!==userId))throw new NativeDirectoryError('Task not found',404);if(current&&!taskId){if(current._nativeOperationHash!==fingerprint)throw new NativeDirectoryError('Idempotency key already used for another task',409);return {task:await populate(editor,current),replayed:true,message:'Task already created'};}
 if(actor.role==='client'){if(!current||actorId!==userId||Object.keys(input as object).some(k=>k!=='status')||patch.status!=='completed')throw new NativeDirectoryError('Clients can only complete their own tasks',403);const error=taskScheduleError(formatInTimeZone(current.startDate,TASK_TIME_ZONE,'yyyy-MM-dd'),current.allottedTime||'00:00');if(error)throw new NativeDirectoryError(error.replace(/meal/g,'task'));}else if(!['admin','dietitian','health_counselor'].includes(actor.role))throw new NativeDirectoryError('Staff access required',403);
 const now=new Date(),data:DocumentData=current?{...current,...patch,updatedAt:now}:{_id:id,client:userId,dietitian:actorId,creatorRole:actor.role,description:'',allottedTime:'12:00 AM',repeatFrequency:0,notifyClientOnChat:false,notifyDieticianOnCompletion:'',tags:[],status:'pending',createdAt:now,...patch,title:patch.title||patch.taskType,updatedAt:now,...(operationId?{operationId,_nativeOperationHash:fingerprint}:{})};if(!data.taskType||!data.startDate||!data.endDate||data.startDate>data.endDate||scheduledTaskTime(formatInTimeZone(data.startDate,TASK_TIME_ZONE,'yyyy-MM-dd'),data.allottedTime)===null)throw new NativeDirectoryError('Valid task type, dates and time are required');for(const tag of data.tags||[]){if(!await editor.document('tags',tag))throw new NativeDirectoryError('Invalid task tag');}
 if(await editor.commit(current?[{collection:'tasks',id,patch:{...patch,updatedAt:now}}]:[],current?[]:[{collection:'tasks',id,data}]))return {task:await populate(editor,data),message:current?'Task updated successfully':'Task created successfully'};
 }throw new NativeDirectoryError('Task changed while saving. Please retry.',409);
}
