import type * as MongoTypes from '@/lib/db/mongo-types';
import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {nativeJson} from './native-history';
import {nativeAppointmentActor} from './native-staff-appointments';
import {NativeStaffClientError} from './native-staff-client';
const schema=z.object({name:z.string().trim().min(1).max(100),description:z.string().max(500).optional(),duration:z.coerce.number().int().min(15).max(180).optional(),color:z.string().max(100).optional(),icon:z.string().max(100).optional(),requiresMeetingLink:z.boolean().optional(),requiresLocation:z.boolean().optional(),isActive:z.boolean().optional(),order:z.number().int().optional()});
export async function listNativeAppointmentConfig(db:MongoDatabase,actorId:string,params:URLSearchParams){await nativeAppointmentActor(db,actorId);const output:DocumentData={types:[],modes:[]};for(const [key,collection] of [['types','appointmenttypes'],['modes','appointmentmodes']])if(!params.get('resource')||['all',key].includes(params.get('resource')!)){let q:MongoTypes.Query=db.collection(collection);if(params.get('activeOnly')==='true')q=q.where('isActive','==',true);const rows=await q.get();output[key]=nativeJson(rows.docs.map(d=>({_id:d.id,...d.data()})).sort((a:any,b:any)=>(a.order||0)-(b.order||0)||String(a.name).localeCompare(String(b.name))));}return output;}
export async function saveNativeAppointmentConfig(db:MongoDatabase,actorId:string,input:any,update=false,remove=false){if(!input||!['type','mode'].includes(input.resource))throw new NativeStaffClientError('Invalid resource type');if((update||remove)&&!/^[a-f0-9]{24}$/.test(input.id||''))throw new NativeStaffClientError('Valid ID required');const collection=input.resource==='type'?'appointmenttypes':'appointmentmodes',patch:DocumentData=remove?{}:update?schema.partial().parse(input):schema.parse(input),ref=db.collection(collection).doc(input.id||randomBytes(12).toString('hex'));
 await db.runTransaction(async tx=>{const [actor,current]=await tx.getAll(db.collection('users').doc(actorId),ref);if(actor.get('role')!=='admin'||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false))throw new NativeStaffClientError('Admin access required',403);if((update||remove)&&!current.exists)throw new NativeStaffClientError('Configuration not found',404);const slug=String(patch.name||current.get('name')||'').toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/[\s-]+/g,'_');if(!slug)throw new NativeStaffClientError('Invalid name');const key=db.collection('_nativeAppointmentConfigNames').doc(createHash('sha256').update(collection+'\0'+slug).digest('hex')),lock=await tx.get(key),matches=await tx.get(db.collection(collection).where('slug','==',slug));if(!remove&&((lock.exists&&lock.get('id')!==ref.id)||matches.docs.some(d=>d.id!==ref.id)))throw new NativeStaffClientError('Configuration name already exists',409);let oldKey;if(current.exists&&current.get('slug')!==slug){oldKey=db.collection('_nativeAppointmentConfigNames').doc(createHash('sha256').update(collection+'\0'+current.get('slug')).digest('hex'));const old=await tx.get(oldKey);if(old.get('id')!==ref.id)oldKey=undefined;}const now=new Date();if(remove){tx.delete(ref);if(lock.get('id')===ref.id)tx.delete(key);}else{if(current.exists)tx.update(ref,{...patch,slug,updatedAt:now});else tx.create(ref,{isActive:true,order:0,...(collection==='appointmenttypes'?{duration:60,color:'#3B82F6',icon:'calendar'}:{requiresMeetingLink:false,requiresLocation:false}),...patch,_id:ref.id,slug,createdAt:now,updatedAt:now});tx.set(key,{id:ref.id});if(oldKey)tx.delete(oldKey);}});
 return remove?{message:'Appointment configuration deleted successfully'}:{[input.resource]:nativeJson({_id:ref.id,...(await ref.get()).data()}),message:`Appointment configuration ${update?'updated':'created'} successfully`};
}
