import {Filter,FieldPath,type MongoDatabase,type DocumentData,type Query} from '@/lib/db/mongo-types';
import {requireNativeAuditAdmin} from './native-admin-audit';
import {nativeDirectoryProfile,nativeDirectoryStatuses,directoryFields,NativeDirectoryError} from './native-client-directory';
import {nativeDates} from './native-plan-editor';
import {readNativeUser} from './native-user-admin';
export async function resolveNativeProfessional(db:MongoDatabase,actorId:string,identifier:string,counselorOnly=false){
 await requireNativeAuditAdmin(db,actorId);let id=decodeURIComponent(identifier).trim();let doc;
 if(/^[a-f0-9]{24}$/i.test(id))doc=await db.collection('users').doc(id).get();
 else if(id.includes('@')){const rows=await db.collection('users').where('email','==',id.toLowerCase()).limit(2).get();if(rows.size===1)doc=rows.docs[0];}
 else{const match=id.match(/^(Dt|HC)-([a-f0-9]{2,24})$/i);if(match){const prefix=match[2].toLowerCase(),rows=await db.collection('users').where(FieldPath.documentId(),'>=',prefix).where(FieldPath.documentId(),'<=',prefix+'\uf8ff').where('role','==',match[1].toLowerCase()==='hc'?'health_counselor':'dietitian').limit(2).get();if(rows.size>1)throw new NativeDirectoryError('Ambiguous professional identifier; use the full ID',409);doc=rows.docs[0];}}
 if(!doc?.exists||!(counselorOnly?['health_counselor']:['dietitian','health_counselor']).includes(doc.get('role')))throw new NativeDirectoryError('Professional not found',404);return {_id:doc.id,...nativeDates(doc.data())} as DocumentData;
}
const ms=(value:any)=>value?new Date(value).getTime():0;
async function batchClientRecords(db:MongoDatabase,collection:string,key:string,ids:string[],fields:string[]){const result:DocumentData[]=[];for(let i=0;i<ids.length;i+=180)await Promise.all(Array.from({length:Math.min(6,Math.ceil((ids.length-i)/30))},async(_,slot)=>{const batch=ids.slice(i+slot*30,i+(slot+1)*30);const rows=await db.collection(collection).where(key,'in',batch).select(...fields).get();result.push(...rows.docs.map(doc=>({...nativeDates(doc.data()),_id:doc.id})));}));return result;}
async function list(query:Query,order:string,fields:string[]){return (await query.select(...fields).orderBy(order,'desc').limit(50).get()).docs.map(doc=>({...nativeDates(doc.data()),_id:doc.id})) as DocumentData[];}
export async function readNativeProfessionalDetail(db:MongoDatabase,actorId:string,identifier:string,counselorOnly=false){
 const professional=await resolveNativeProfessional(db,actorId,identifier,counselorOnly),id=professional._id,hc=professional.role==='health_counselor',primary=hc?'assignedHealthCounselor':'assignedDietitian',secondary=hc?'assignedHealthCounselors':'assignedDietitians';
 const assigned=await db.collection('users').where('role','==','client').where(Filter.or(Filter.where(primary,'==',id),Filter.where(secondary,'array-contains',id))).select(...directoryFields).get();const base=await nativeDirectoryStatuses(db,assigned.docs.map(doc=>nativeDirectoryProfile(doc.id,doc.data()))),ids=base.map(row=>row._id);
 const [clientAppointments,clientPlans]=await Promise.all([batchClientRecords(db,'appointments','client',ids,['client','dietitian','scheduledAt','type','status']),counselorOnly?Promise.resolve([]):batchClientRecords(db,'clientmealplans','clientId',ids,['clientId','assignedBy','templateId','name','startDate','status','createdAt','isDeleted'])]);
 const appointmentMap=new Map<string,DocumentData[]>(),planMap=new Map<string,DocumentData[]>();clientAppointments.forEach(row=>{if(counselorOnly||row.dietitian===id)appointmentMap.set(row.client,[...(appointmentMap.get(row.client)||[]),row]);});clientPlans.filter(row=>!row.isDeleted).forEach(row=>planMap.set(row.clientId,[...(planMap.get(row.clientId)||[]),row]));
 const templates=new Map<string,string>(),templateIds=[...new Set(clientPlans.map(row=>row.templateId).filter((v):v is string=>typeof v==='string'&&!v.includes('/')))];for(let i=0;i<templateIds.length;i+=100){const docs=await db.getAll(...templateIds.slice(i,i+100).map(v=>db.collection('diettemplates').doc(v)),{fieldMask:['name']});docs.forEach(doc=>templates.set(doc.id,doc.get('name')));}
 const now=Date.now(),clients:DocumentData[]=base.map(client=>{const appointments=appointmentMap.get(client._id)||[],plans=(planMap.get(client._id)||[]).sort((a,b)=>ms(b.createdAt)-ms(a.createdAt)),upcoming=appointments.filter(a=>a.status==='scheduled'&&ms(a.scheduledAt)>=now).sort((a,b)=>ms(a.scheduledAt)-ms(b.scheduledAt))[0],last=appointments.filter(a=>ms(a.scheduledAt)<now).sort((a,b)=>ms(b.scheduledAt)-ms(a.scheduledAt))[0];return {...client,progress:{appointmentCount:appointments.length,upcomingAppointment:upcoming?{dateTime:upcoming.scheduledAt,type:upcoming.type}:null,...(counselorOnly?{lastAppointment:last?{dateTime:last.scheduledAt,type:last.type}:null}:{mealPlanCount:plans.filter(p=>p.assignedBy===id).length,latestMealPlan:plans[0]?{name:templates.get(plans[0].templateId)||'Custom Plan',startDate:plans[0].startDate,status:plans[0].status}:null})}};});
 const profile=await readNativeUser(db,actorId,id),stats:DocumentData={totalClients:clients.length,activeClients:clients.filter(c=>c.clientStatus==='active').length};if(counselorOnly)return {counselor:profile,clients,stats:{...stats,totalAppointments:clientAppointments.length,completedAppointments:clientAppointments.filter(a=>a.status==='completed').length}};
 const appointmentQuery=db.collection('appointments').where('dietitian','==',id),planQuery=db.collection('clientmealplans').where('assignedBy','==',id);
 const [appointments,payments,notes,tasks,mealPlans,totalAppointments,completedAppointments,totalMealPlans]=await Promise.all([
 list(appointmentQuery,'scheduledAt',['client','dietitian','scheduledAt','type','status','duration','notes','createdAt']),list(db.collection('unifiedpayments').where('dietitian','==',id),'createdAt',['client','dietitian','amount','status','paymentStatus','type','planName','createdAt','transactionId','paymentMethod']),list(db.collection('clientnotes').where('createdBy','==',id),'createdAt',['client','userId','createdBy','topic','content','showToClient','createdAt']),list(db.collection('tasks').where(Filter.or(Filter.where('dietitian','==',id),Filter.where('assignedBy','==',id))),'startDate',['client','dietitian','assignedBy','title','description','taskType','startDate','endDate','status','allottedTime','createdAt']),list(planQuery,'createdAt',['clientId','templateId','name','startDate','endDate','status','createdAt','isDeleted','assignedBy']),appointmentQuery.count().get(),appointmentQuery.where('status','==','completed').count().get(),planQuery.select('isDeleted').get()]);
 const all=[...appointments,...payments,...notes,...tasks,...mealPlans],people=new Map<string,DocumentData>(),personIds=[...new Set(all.flatMap(row=>[row.client,row.clientId,row.userId]).filter((v):v is string=>typeof v==='string'&&!v.includes('/')))];for(let i=0;i<personIds.length;i+=100){for(const doc of await db.getAll(...personIds.slice(i,i+100).map(v=>db.collection('users').doc(v)),{fieldMask:['firstName','lastName','email','avatar']}))if(doc.exists)people.set(doc.id,{...doc.data(),_id:doc.id});}
 all.forEach(row=>{for(const key of ['client','clientId','userId'])if(typeof row[key]==='string')row[key]=people.get(row[key])||null;if(typeof row.templateId==='string')row.templateId={_id:row.templateId,name:templates.get(row.templateId)||null};});
 return {dietitian:profile,clients,appointments,payments,notes,tasks,mealPlans:mealPlans.filter(row=>!row.isDeleted),stats:{...stats,totalAppointments:totalAppointments.data().count,completedAppointments:completedAppointments.data().count,totalMealPlans:totalMealPlans.docs.filter(doc=>!doc.get('isDeleted')).length,totalPayments:payments.length,completedPayments:payments.filter(p=>p.status==='completed').length,pendingPayments:payments.filter(p=>p.status==='pending').length,totalRevenue:payments.filter(p=>p.status==='completed').reduce((sum,p)=>sum+Number(p.amount||0),0),totalTasks:tasks.length,completedTasks:tasks.filter(t=>t.status==='completed').length,pendingTasks:tasks.filter(t=>t.status==='pending').length,overdueTasks:tasks.filter(t=>t.status!=='completed'&&t.endDate&&ms(t.endDate)<now).length}};
}
