import {randomBytes,createHash} from 'node:crypto';
import {z} from 'zod';
import {Filter,type Firestore,type DocumentData,type Query,type Transaction} from 'firebase-admin/firestore';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeJson} from './native-history';
import {nativeDates} from './native-plan-editor';
import {NativeStaffClientError} from './native-staff-client';
import {taskClientAccess} from './native-staff-tasks';
const activeStatuses=['scheduled','confirmed','rescheduled','in-progress'];
const id=z.string().regex(/^[a-f0-9]{24}$/),schema=z.object({dietitianId:id.optional(),clientId:id.optional(),scheduledAt:z.coerce.date().optional(),duration:z.coerce.number().int().min(15).max(180).optional(),type:z.string().max(100).optional(),notes:z.string().max(10000).optional(),appointmentTypeId:id.optional(),appointmentModeId:id.optional(),modeName:z.string().max(100).optional(),location:z.string().max(1000).optional(),status:z.enum(['scheduled','confirmed','rescheduled','completed','cancelled','no_show','in-progress']).optional(),reason:z.string().max(2000).optional(),cancellationReason:z.string().max(2000).optional()});
export async function nativeAppointmentActor(db:Firestore,actorId:string){const actor=await db.collection('users').doc(actorId).get();if(!actor.exists||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false)||!['admin','dietitian','health_counselor','client'].includes(actor.get('role')))throw new NativeStaffClientError('Unauthorized',401);return actor;}
async function viewAppointments(db:Firestore,rows:FirebaseFirestore.DocumentSnapshot[]){const data:DocumentData[]=await Promise.all(rows.map(async r=>({...await hydrateNativeDocument(r.data()!),_id:r.id}))),refs=new Map<string,FirebaseFirestore.DocumentReference>();for(const a of data)for(const [field,collection] of [['client','users'],['dietitian','users'],['createdBy','users'],['appointmentTypeId','appointmenttypes'],['appointmentModeId','appointmentmodes']])if(typeof a[field]==='string'&&/^[a-f0-9]{24}$/.test(a[field]))refs.set(`${collection}/${a[field]}`,db.collection(collection).doc(a[field]));const map=new Map();const all=[...refs.values()];for(let i=0;i<all.length;i+=100)for(const r of await db.getAll(...all.slice(i,i+100),{fieldMask:['firstName','lastName','email','avatar','role','name','slug','color','icon']}))if(r.exists)map.set(r.ref.path,{_id:r.id,...r.data()});for(const a of data){for(const [f,c] of [['client','users'],['dietitian','users'],['createdBy','users'],['appointmentTypeId','appointmenttypes'],['appointmentModeId','appointmentmodes']])if(a[f])a[f]=map.get(`${c}/${a[f]}`)||a[f];delete a._nativeExternalFields;delete a._nativeSource;delete a._nativeOperationHash;}return nativeJson(data) as DocumentData[];}
function assigned(client:DocumentData,actorId:string){return [client.assignedDietitian,...(client.assignedDietitians||[]),client.assignedHealthCounselor,...(client.assignedHealthCounselors||[])].includes(actorId);}
export async function listStaffAppointments(db:Firestore,actorId:string,params:URLSearchParams,appointmentId?:string){const actor=await nativeAppointmentActor(db,actorId),role=actor.get('role');if(appointmentId){if(!/^[a-f0-9]{24}$/.test(appointmentId))throw new NativeStaffClientError('Invalid appointment ID');const doc=await db.collection('appointments').doc(appointmentId).get();if(!doc.exists)throw new NativeStaffClientError('Appointment not found',404);if(role!=='admin'&&![doc.get('client'),doc.get('dietitian'),doc.get('createdBy')].includes(actorId))await taskClientAccess(db,actorId,doc.get('client'));return (await viewAppointments(db,[doc]))[0];}
 let query:Query=db.collection('appointments');const client=params.get('clientId'),provider=params.get('dietitianId');if(client){await taskClientAccess(db,actorId,client);query=query.where('client','==',client);}else if(role==='client')query=query.where('client','==',actorId);else if(role!=='admin')query=query.where(Filter.or(Filter.where('dietitian','==',actorId),Filter.where('createdBy','==',actorId)));if(provider)query=query.where('dietitian','==',provider);if(params.get('status'))query=query.where('status','==',params.get('status'));if(params.get('date')){const date=params.get('date')!;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new NativeStaffClientError('Invalid date');const start=new Date(date+'T00:00:00+05:30');query=query.where('scheduledAt','>=',start).where('scheduledAt','<',new Date(start.getTime()+86400000));}
 const page=Math.max(1,Math.floor(Number(params.get('page'))||1)),limit=Math.max(1,Math.min(100,Math.floor(Number(params.get('limit'))||10))),search=params.get('search')?.trim().toLowerCase();
 if(search){const candidates=await query.select('client','dietitian','createdBy','type','notes','scheduledAt').get(),views=await viewAppointments(db,candidates.docs);const found=views.filter(a=>[a.type,a.notes,a.client?.firstName,a.client?.lastName,a.client?.email,a.dietitian?.firstName,a.dietitian?.lastName].some(v=>String(v||'').toLowerCase().includes(search))).sort((a,b)=>Date.parse(a.scheduledAt)-Date.parse(b.scheduledAt)),selected=found.slice((page-1)*limit,page*limit),full=selected.length?await db.getAll(...selected.map(a=>db.collection('appointments').doc(a._id))):[];return {appointments:await viewAppointments(db,full),pagination:{page,limit,total:found.length,pages:Math.ceil(found.length/limit)}};}
 const [rows,count]=await Promise.all([query.orderBy('scheduledAt','asc').offset((page-1)*limit).limit(limit).get(),query.count().get()]);return {appointments:await viewAppointments(db,rows.docs),pagination:{page,limit,total:count.data().count,pages:Math.ceil(count.data().count/limit)}};
}
export async function mutateStaffAppointment(db:Firestore,actorId:string,input:unknown,appointmentId?:string,action:'save'|'cancel'|'reschedule'='save',operationKey?:string|null){
 if(appointmentId&&!/^[a-f0-9]{24}$/.test(appointmentId))throw new NativeStaffClientError('Invalid appointment ID');const parsed=schema.parse(input),patch:DocumentData={...parsed};if(action==='cancel')patch.status='cancelled';if(action==='reschedule'&&!patch.scheduledAt)throw new NativeStaffClientError('New scheduled date/time is required');
 if(!appointmentId&&(!patch.clientId||!patch.dietitianId||!patch.scheduledAt))throw new NativeStaffClientError('Client, provider and date are required');
 const key=operationKey&&/^[\w.:-]{8,128}$/.test(operationKey)?operationKey:randomBytes(16).toString('hex'),aid=appointmentId||createHash('sha256').update(actorId+'\0'+key).digest('hex').slice(0,24),ref=db.collection('appointments').doc(aid),requestHash=createHash('sha256').update(JSON.stringify(parsed)).digest('hex');
 await db.runTransaction(async tx=>{
  const [actor,current]=await tx.getAll(db.collection('users').doc(actorId),ref);if(!actor.exists||(['inactive','suspended'].includes(actor.get('status'))||actor.get('isActive')===false)||!['admin','dietitian','health_counselor','client'].includes(actor.get('role')))throw new NativeStaffClientError('Unauthorized',401);const role=actor.get('role');if(appointmentId&&!current.exists)throw new NativeStaffClientError('Appointment not found',404);if(!appointmentId&&current.exists){if(current.get('_nativeOperationHash')!==requestHash)throw new NativeStaffClientError('Appointment retry conflict',409);return;}
  const old=current.exists?nativeDates(await hydrateNativeDocument(current.data()!)):null,clientId=old?.client||patch.clientId,providerId=old?.dietitian||patch.dietitianId;if(old&&((patch.clientId&&patch.clientId!==clientId)||(patch.dietitianId&&patch.dietitianId!==providerId)))throw new NativeStaffClientError('Client/provider cannot be reassigned through this endpoint');const [client,provider]=await tx.getAll(db.collection('users').doc(clientId),db.collection('users').doc(providerId));if(!client.exists||client.get('role')!=='client'||!provider.exists||!['dietitian','health_counselor'].includes(provider.get('role')))throw new NativeStaffClientError('Client or provider not found',404);
  if((!old||patch.scheduledAt)&&(['inactive','suspended'].includes(provider.get('status'))||provider.get('isActive')===false))throw new NativeStaffClientError('Provider is inactive',409);
  let assignHC=false;
  if(!old){if(role==='client')throw new NativeStaffClientError('Clients cannot create appointments through the staff endpoint',403);if(role!=='admin'&&providerId!==actorId)throw new NativeStaffClientError('You can only book as yourself',403);if(role!=='admin'&&!assigned(client.data()!,actorId)){assignHC=role==='health_counselor'&&!client.get('assignedHealthCounselor')&&!(client.get('assignedHealthCounselors')||[]).length;if(!assignHC)throw new NativeStaffClientError('Client is not assigned to you',403);}}
  else if(role==='client'){if(clientId!==actorId||(action!=='reschedule'&&patch.status!=='cancelled')||Object.keys(patch).some(k=>!['status','reason','cancellationReason',...(action==='reschedule'?['scheduledAt','duration']:[])].includes(k)))throw new NativeStaffClientError('Clients can only cancel or reschedule their own appointments',403);}
  else if(role!=='admin'&&old.createdBy!==actorId&&providerId!==actorId&&!assigned(client.data()!,actorId))throw new NativeStaffClientError('Appointment access denied',403);
  if(action==='reschedule'&&old&&['completed','cancelled'].includes(old.status))throw new NativeStaffClientError('Cannot reschedule a completed or cancelled appointment');
  const update:DocumentData={...patch};delete update.clientId;delete update.dietitianId;delete update.reason;
  if(patch.appointmentTypeId){const type=await tx.get(db.collection('appointmenttypes').doc(patch.appointmentTypeId));if(!type.exists||type.get('isActive')===false)throw new NativeStaffClientError('Appointment type unavailable');update.duration=Number(type.get('duration')||patch.duration||60);}
  if(patch.appointmentModeId){const mode=await tx.get(db.collection('appointmentmodes').doc(patch.appointmentModeId));if(!mode.exists||mode.get('isActive')===false)throw new NativeStaffClientError('Appointment mode unavailable');update.modeName=mode.get('name');if(mode.get('requiresLocation')&&!patch.location&&!old?.location)throw new NativeStaffClientError('Location required');}
  const when=update.scheduledAt||old?.scheduledAt,duration=Number(update.duration||old?.duration||60);if(!when||!Number.isFinite(when.getTime())||duration<15||duration>180)throw new NativeStaffClientError('Invalid appointment schedule');if((!old||update.scheduledAt)&&when.getTime()<=Date.now())throw new NativeStaffClientError('Select a future appointment time');
  if((!old||update.scheduledAt||update.duration||update.status==='scheduled'||update.status==='confirmed')&&update.status!=='cancelled'){const conflicts=await tx.get(db.collection('appointments').where('dietitian','==',providerId).where('status','in',activeStatuses).where('scheduledAt','>=',new Date(when.getTime()-180*60000)).where('scheduledAt','<',new Date(when.getTime()+duration*60000)));if(conflicts.docs.some(d=>d.id!==aid&&nativeDates(d.data()).scheduledAt.getTime()+Number(d.get('duration')||60)*60000>when.getTime()))throw new NativeStaffClientError('Time slot conflicts with another appointment',409);}
  const now=new Date(),name=[actor.get('firstName'),actor.get('lastName')].filter(Boolean).join(' '),eventAction=!old?'created':update.status==='cancelled'&&old.status!=='cancelled'?'cancelled':action==='reschedule'||(update.scheduledAt&&update.scheduledAt.getTime()!==old.scheduledAt.getTime())?'rescheduled':update.status==='completed'&&old.status!=='completed'?'completed':null;
  if(eventAction){update.lifecycleHistory=[...(old?.lifecycleHistory||[]),{action:eventAction,performedBy:actorId,performedByRole:role,performedByName:name,timestamp:now,...(eventAction==='rescheduled'?{previousScheduledAt:old.scheduledAt,newScheduledAt:when}:{}),details:{...(patch.reason?{reason:patch.reason}:{}),duration}}];if(eventAction==='cancelled')update.cancelledBy={userId:actorId,role,name,timestamp:now,...(patch.reason||patch.cancellationReason?{reason:patch.reason||patch.cancellationReason}:{})};if(eventAction==='rescheduled')update.rescheduledBy={userId:actorId,role,name,timestamp:now,previousScheduledAt:old.scheduledAt};}
  const types:Record<string,string>={'video':'video_consultation','phone':'consultation','in-person':'consultation','follow-up':'follow_up','followup':'follow_up','initial-consultation':'initial_consultation','nutrition-assessment':'nutrition_assessment','group-session':'group_session','video-consultation':'video_consultation'};if(update.type)update.type=types[update.type]||update.type;if(!old)Object.assign(update,{_id:aid,client:clientId,dietitian:providerId,createdBy:actorId,createdAt:now,status:'scheduled',type:update.type||'consultation',duration,_nativeOperationHash:requestHash});update.updatedAt=now;
  if(assignHC)tx.update(client.ref,{assignedHealthCounselor:actorId,updatedAt:now});if(old)tx.update(ref,await prepareNativePatch(current.data()!,update));else tx.create(ref,await prepareNativeDocument(update));
  if(eventAction){const eventId=randomBytes(12).toString('hex');tx.create(db.collection('_nativeOutbox').doc('appointment-'+eventId),{type:'appointment-'+eventAction,appointmentId:aid,clientId,providerId,actorId,status:'pending',createdAt:now});tx.set(db.collection('_nativeRealtime').doc(clientId),{appointmentsUpdatedAt:now},{merge:true});}
 });return (await viewAppointments(db,[await ref.get()]))[0];
}
