import {randomBytes,timingSafeEqual} from 'node:crypto';
import bcrypt from 'bcryptjs';
import type {Firestore} from 'firebase-admin/firestore';
import {NativeDirectoryError} from './native-client-directory';
/** Revokes access atomically and retains an explicit erasure job so related data cannot be silently skipped. */
export async function requestNativeClientErasure(db:Firestore,userId:string,password:unknown){if(typeof password!=='string'||!password||Buffer.byteLength(password)>256)throw new NativeDirectoryError('Password is required to confirm account deletion');const ref=db.collection('users').doc(userId),snapshot=await ref.get();if(!snapshot.exists)throw new NativeDirectoryError('User not found',404);if(snapshot.get('role')!=='client'||snapshot.get('status')!=='active')throw new NativeDirectoryError('Only active client accounts can use this endpoint',403);const stored=snapshot.get('password');let valid=false;if(typeof stored==='string'){if(/^\$2[aby]\$/.test(stored))valid=await bcrypt.compare(password,stored);else{const a=Buffer.from(password),b=Buffer.from(stored);valid=a.length===b.length&&timingSafeEqual(a,b);}}if(!valid)throw new NativeDirectoryError('Incorrect password',401);
 return db.runTransaction(async tx=>{const current=await tx.get(ref);if(!current.exists||current.get('role')!=='client'||current.get('status')!=='active'||current.get('password')!==stored)throw new NativeDirectoryError('Account changed; sign in again',409);const now=new Date(),id=randomBytes(12).toString('hex');tx.create(db.collection('_nativeDeletedUsers').doc(id),{sourceId:userId,deletedBy:userId,deletedAt:now,reason:'client-request',original:current.data()});tx.create(db.collection('_nativeErasureJobs').doc(userId),{userId,status:'pending',requestedAt:now,archiveId:id,scope:'account-related-records-and-unshared-media'});tx.delete(ref);return {success:true,message:'Your account access has been removed. Associated data deletion is queued.',deletionStatus:'pending'};});
}

const ERASURE_COLLECTIONS=[
 ['clientmealplans',['clientId']],['mealplans',['client']],['appointments',['client']],['messages',['sender','receiver']],['clientnotes',['client','userId']],['progressentries',['client','userId']],['foodlogs',['client']],['dietaryrecalls',['userId']],['notifications',['userId']],['tasks',['client']],['medicalinfos',['userId']],['lifestyleinfos',['userId']],['journaltrackings',['client','userId']],['dailytrackings',['client','userId']],['hydrationlogs',['userId']],['sleeplogs',['userId']],['steplogs',['userId']],['watchconnections',['userId']],['watchhealthdatas',['userId']],['files',['uploadedBy']],
] as const;
/** Financial records, audit logs and immutable migration archives require a separate retention decision. */
export const CLIENT_ERASURE_RETENTION=['unifiedpayments','payments','otherplatformpayments','clientpurchases','clientsubscriptions','subscriptions','adminauditlogs','activitylogs','_nativeDeletedUsers','_mediaAssets'];
export async function processNativeClientErasure(db:Firestore,adminId:string,userId:string){
 if(!process.env.FIRESTORE_EMULATOR_HOST&&process.env.DTPS_NATIVE_ERASURE_ENABLED!=='true')throw new NativeDirectoryError('Native erasure worker is disabled pending local acceptance',503);
 if(!/^[a-f0-9]{24}$/i.test(userId))throw new NativeDirectoryError('Invalid account ID');
 const {Filter}=await import('firebase-admin/firestore');const jobRef=db.collection('_nativeErasureJobs').doc(userId);
 return db.runTransaction(async tx=>{const [actor,job,account]=await tx.getAll(db.collection('users').doc(adminId),jobRef,db.collection('users').doc(userId));if(actor.get('role')!=='admin'||actor.get('status')!=='active')throw new NativeDirectoryError('Forbidden',403);if(!job.exists)throw new NativeDirectoryError('Erasure job not found',404);if(account.exists)throw new NativeDirectoryError('Account must be revoked before erasure',409);if(job.get('status')==='media_review_required')return {status:'media_review_required',recordsRemoved:job.get('recordsRemoved')||0,retainedCollections:CLIENT_ERASURE_RETENTION};
 const index=Number(job.get('collectionIndex')||0);if(!Number.isSafeInteger(index)||index<0||index>ERASURE_COLLECTIONS.length)throw new NativeDirectoryError('Invalid erasure checkpoint',409);if(index===ERASURE_COLLECTIONS.length){tx.update(jobRef,{status:'media_review_required',recordsCompletedAt:new Date(),retainedCollections:CLIENT_ERASURE_RETENTION,mediaPolicy:'Physical Blob removal requires verified reverse-reference ownership; no shared archive objects removed.'});return {status:'media_review_required',recordsRemoved:job.get('recordsRemoved')||0,retainedCollections:CLIENT_ERASURE_RETENTION};}
 const [collection,fields]=ERASURE_COLLECTIONS[index],query=db.collection(collection).where(Filter.or(...fields.map(field=>Filter.where(field,'==',userId)))).limit(50),rows=await tx.get(query);
 for(const row of rows.docs){const candidate={sourceCollection:collection,sourceId:row.id,externalFields:row.get('_nativeExternalFields')||[],status:'reference-review-required',createdAt:new Date()};if(collection==='files'||candidate.externalFields.length)tx.set(jobRef.collection('mediaCandidates').doc(collection+'-'+row.id),candidate);tx.delete(row.ref);}
 const removed=Number(job.get('recordsRemoved')||0)+rows.size,nextIndex=rows.size<50?index+1:index;tx.update(jobRef,{status:'processing',recordsRemoved:removed,collectionIndex:nextIndex,currentCollection:collection,updatedAt:new Date()});return {status:'processing',recordsRemoved:removed,nextCollectionIndex:nextIndex,remainingCollections:ERASURE_COLLECTIONS.length-nextIndex};});
}
