import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import {Filter,type Firestore,type DocumentData} from 'firebase-admin/firestore';
import {hydrateNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeDates} from './native-plan-editor';
import {NativeDirectoryError,nativeDirectoryProfile,populateNativeDirectory} from './native-client-directory';
import {nativePhoneVariations} from './native-registration';
import {validatePhoneNumber} from '@/lib/validations/contact';
const text=z.string().max(10000).optional(),texts=z.array(z.string().max(1000)).max(200).optional(),number=z.preprocess(value=>value===''||value===null?undefined:value,z.coerce.number().finite().min(0).max(10000000).optional()),id=z.string().regex(/^[a-f0-9]{24}$/i);
const schema=z.object({
 ...Object.fromEntries('firstName lastName avatar bio gender alternativePhone alternativeEmail source referralSource maritalStatus occupation targetWeightBucket generalGoal dietType activityLevel activityRate bmiCategory timezone address city state pincode'.split(' ').map(k=>[k,text])),
 ...Object.fromEntries('height weight heightFeet heightInch heightCm weightKg targetWeightKg bmr bodyFat idealWeight targetBmi experience consultationFee'.split(' ').map(k=>[k,number])),
 ...Object.fromEntries('goals healthGoals medicalConditions allergies dietaryRestrictions credentials specializations tags'.split(' ').map(k=>[k,texts])),
 dateOfBirth:z.string().nullable().optional(),anniversary:z.string().nullable().optional(),sharePhotoConsent:z.boolean().optional(),email:z.preprocess(value=>typeof value==='string'?(value.trim()||undefined):value,z.string().email().max(320).optional()),phone:z.string().max(30).optional(),role:z.enum(['admin','dietitian','health_counselor','client']).optional(),status:z.enum(['active','inactive','suspended']).optional(),clientStatus:z.enum(['lead','active','inactive','hold','leading','onboarding','paused']).optional(),expectedStartDate:z.string().nullable().optional(),expectedEndDate:z.string().nullable().optional(),assignedDietitian:id.nullable().optional(),assignedDietitians:z.array(id).max(100).optional(),assignedHealthCounselor:id.nullable().optional(),assignedHealthCounselors:z.array(id).max(100).optional(),
 dailyGoals:z.object({calories:z.number().min(0).max(30000).optional(),protein:z.number().min(0).max(2000).optional(),carbs:z.number().min(0).max(5000).optional(),fat:z.number().min(0).max(2000).optional(),water:z.number().min(0).max(20000).optional(),steps:z.number().min(0).max(100000).optional()}).optional(),
 availability:z.array(z.object({day:z.string().max(20),startTime:z.string().max(20),endTime:z.string().max(20),isAvailable:z.boolean().optional()})).max(100).optional()
});
const extraFields='bio address city state pincode firstWeight height weight targetWeightKg heightFeet heightInch activityLevel activityRate generalGoal healthGoals goals dailyGoals dietType allergies dietaryRestrictions medicalConditions alternativeEmail alternativePhone anniversary source referralSource maritalStatus occupation targetWeightBucket sharePhotoConsent bmi bmiCategory bmr bodyFat idealWeight targetBmi credentials specializations experience consultationFee availability timezone documents expectedStartDate expectedEndDate'.split(' ');
function safeUser(id:string,data:DocumentData){return {...nativeDirectoryProfile(id,data),...nativeDates(Object.fromEntries(extraFields.filter(k=>data[k]!==undefined).map(k=>[k,data[k]])))};}
function authorize(actor:DocumentData|undefined,user:DocumentData|undefined,actorId:string,userId:string){if(!actor||actor.status!=='active')throw new NativeDirectoryError('Access denied',403);if(!user)throw new NativeDirectoryError('User not found',404);const dt=actor.role==='dietitian'&&[user.assignedDietitian,...(user.assignedDietitians||[])].includes(actorId),hc=actor.role==='health_counselor'&&[user.assignedHealthCounselor,...(user.assignedHealthCounselors||[])].includes(actorId);if(actor.role!=='admin'&&actorId!==userId&&!(user.role==='client'&&(dt||hc)))throw new NativeDirectoryError('Access denied',403);return {admin:actor.role==='admin',dietitian:dt,self:actorId===userId};}
export async function readNativeUser(db:Firestore,actorId:string,userId:string){const [actor,user]=await db.getAll(db.collection('users').doc(actorId),db.collection('users').doc(userId));authorize(actor.data(),user.data(),actorId,userId);return (await populateNativeDirectory(db,[safeUser(userId,await hydrateNativeDocument(user.data()!))]))[0];}
export async function updateNativeUser(db:Firestore,actorId:string,userId:string,input:unknown,requirements:{adminOnly?:boolean;role?:string}={}){const parsed=schema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid user fields: '+parsed.error.issues.map(issue=>issue.path.join('.')).join(', '));const incoming=Object.fromEntries(Object.entries(parsed.data).filter(([,value])=>value!==undefined)) as DocumentData;
 return db.runTransaction(async tx=>{
  const [actorDoc,userDoc]=await tx.getAll(db.collection('users').doc(actorId),db.collection('users').doc(userId));const actor=actorDoc.data(),stored=userDoc.data(),access=authorize(actor,stored,actorId,userId),user=nativeDates(await hydrateNativeDocument(stored!)),patch:DocumentData={...incoming},now=new Date();
  if(requirements.adminOnly&&!access.admin)throw new NativeDirectoryError('Admin access required',403);if(requirements.role&&user.role!==requirements.role)throw new NativeDirectoryError('User not found',404);
  for(const k of ['role','status','clientStatus','expectedStartDate','expectedEndDate','assignedDietitian','assignedDietitians','assignedHealthCounselor','assignedHealthCounselors'])if(k in patch&&!access.admin)throw new NativeDirectoryError('Only administrators can change '+k,403);
  if(('email'in patch||'phone'in patch)&&!access.admin&&!access.dietitian&&!access.self)throw new NativeDirectoryError('Contact changes are not permitted',403);
  for(const field of ['dateOfBirth','anniversary','expectedStartDate','expectedEndDate'])if(patch[field]){const d=new Date(patch[field]);if(!Number.isFinite(d.getTime())||d.getUTCFullYear()<1900||d.getUTCFullYear()>9999||field==='dateOfBirth'&&d>now)throw new NativeDirectoryError('Invalid date');patch[field]=d;}
  if(patch.timezone){try{new Intl.DateTimeFormat('en',{timeZone:patch.timezone}).format(now);}catch{throw new NativeDirectoryError('Invalid timezone');}}
  if(patch.phone){const normalized=validatePhoneNumber(patch.phone,'+91');if(!normalized.isValid||!normalized.normalized)throw new NativeDirectoryError('Invalid phone number');patch.phone=normalized.normalized;}
  if(patch.email)patch.email=patch.email.trim().toLowerCase();
  const contacts:Array<{key:FirebaseFirestore.DocumentReference;old?:FirebaseFirestore.DocumentReference;existing:FirebaseFirestore.DocumentSnapshot}>=[];
  for(const kind of ['email','phone'])if(patch[kind]&&patch[kind]!==user[kind]){const key=db.collection('_nativeUserKeys').doc(createHash('sha256').update(kind+'\0'+patch[kind]).digest('hex')),existing=await tx.get(key),found=await tx.get(kind==='phone'?db.collection('users').where(kind,'in',nativePhoneVariations(patch[kind])):db.collection('users').where(kind,'==',patch[kind]));if(existing.exists&&existing.get('userId')!==userId||found.docs.some(d=>d.id!==userId))throw new NativeDirectoryError('Phone number or email is already registered',409);let old:FirebaseFirestore.DocumentReference|undefined;if(user[kind]){const oldRef=db.collection('_nativeUserKeys').doc(createHash('sha256').update(kind+'\0'+user[kind]).digest('hex'));const claim=await tx.get(oldRef);if(claim.get('userId')===userId)old=oldRef;}contacts.push({key,old,existing});}
  if((patch.role&&patch.role!=='admin'||patch.status&&patch.status!=='active')&&user.role==='admin'){const admins=await tx.get(db.collection('users').where('role','==','admin').where('status','==','active'));if(admins.size<=1)throw new NativeDirectoryError('At least one active administrator is required',409);}
  for(const [p,s,r] of [['assignedDietitian','assignedDietitians','dietitian'],['assignedHealthCounselor','assignedHealthCounselors','health_counselor']])if(p in patch||s in patch){const primary=patch[p]===undefined?user[p]:patch[p],secondaries=patch[s]===undefined?user[s]||[]:patch[s];for(const id of [...new Set([primary,...secondaries].filter(Boolean))]){const staff=await tx.get(db.collection('users').doc(id as string));if(staff.get('role')!==r||staff.get('status')!=='active')throw new NativeDirectoryError('Invalid assigned professional');}patch[p]=primary||null;patch[s]=[...new Set(secondaries)].filter(v=>v!==primary);}
  const linked='assignedDietitian'in patch?await tx.get(db.collection('unifiedpayments').where('client','==',userId)):null;
  if(patch.weight!==undefined&&patch.weightKg===undefined)patch.weightKg=patch.weight;
  // Staff forms resend the baseline even when only another assessment changed.
  if(!access.admin&&!access.dietitian&&!access.self&&patch.weightKg!==undefined&&Number(patch.weightKg)===Number(user.firstWeight?.value||user.weightKg||user.weight||0)){delete patch.weightKg;delete patch.weight;}
  if(patch.weightKg!==undefined){const weight=Number(patch.weightKg);if(weight<=0||weight>1000)throw new NativeDirectoryError('Invalid weight');const baseline=Number(user.firstWeight?.value||user.weightKg||user.weight||0);if(!access.admin&&!access.dietitian){if(!access.self||actor!.role!=='client')throw new NativeDirectoryError('Only your dietitian can update starting weight',403);if(baseline>0&&Math.abs(weight-baseline)>0.0001)throw new NativeDirectoryError('Starting weight is locked; contact your dietitian',403);}patch.weightKg=String(weight);patch.weight=weight;patch.firstWeight={value:weight,setBy:user.firstWeight?.setBy||actor!.role,setDate:user.firstWeight?.setDate||now,isLocked:true,lastUpdatedBy:actor!.role,lastUpdateDate:now};}
  const weight=Number(patch.weightKg??user.weightKg),height=Number(patch.heightCm??user.heightCm);if(patch.heightCm!==undefined&&(height<=0||height>300))throw new NativeDirectoryError('Invalid height');if((patch.weightKg!==undefined||patch.heightCm!==undefined)&&weight>0&&height>0){const bmi=weight/(height/100)**2;patch.bmi=bmi.toFixed(1);patch.bmiCategory=bmi<18.5?'Underweight':bmi<25?'Normal':bmi<30?'Overweight':'Obese';}
  if(patch.status&&patch.status!=='active'||patch.role&&patch.role!==user.role){patch.logoutOtherSessionsAt=now;patch.keepCurrentSessionId='';}
  for(const c of contacts){if(!c.existing.exists)tx.create(c.key,{userId,createdAt:now});if(c.old)tx.delete(c.old);}tx.update(userDoc.ref,await prepareNativePatch(stored!,{...patch,updatedAt:now}));for(const p of linked?.docs||[])if(['active','pending','on_hold','paid'].includes(p.get('status')))tx.update(p.ref,{dietitian:patch.assignedDietitian,updatedAt:now});
  const audit=randomBytes(12).toString('hex');tx.create(db.collection('activitylogs').doc(audit),{_id:audit,userId:actorId,userRole:actor!.role,targetUserId:userId,action:'Updated User',actionType:'update',category:'profile',description:'Updated fields: '+Object.keys(incoming).join(', '),createdAt:now,updatedAt:now});return safeUser(userId,{...user,...patch});
 });
}
export async function deleteNativeUser(db:Firestore,actorId:string,userId:string,requiredRole?:string){return db.runTransaction(async tx=>{const [actor,user]=await tx.getAll(db.collection('users').doc(actorId),db.collection('users').doc(userId));if(actor.get('role')!=='admin'||actor.get('status')!=='active')throw new NativeDirectoryError('Admin access required',403);if(!user.exists)throw new NativeDirectoryError('User not found',404);if(requiredRole&&user.get('role')!==requiredRole)throw new NativeDirectoryError('Professional not found',404);if(['dietitian','health_counselor'].includes(user.get('role'))){const key=user.get('role')==='dietitian'?'assignedDietitian':'assignedHealthCounselor';const assigned=await tx.get(db.collection('users').where('role','==','client').where(Filter.or(Filter.where(key,'==',userId),Filter.where(key+'s','array-contains',userId))).limit(1));if(!assigned.empty)throw new NativeDirectoryError('Reassign clients before deleting their professional',409);}if(actorId===userId)throw new NativeDirectoryError('You cannot delete your own account',409);if(user.get('role')==='admin'){const admins=await tx.get(db.collection('users').where('role','==','admin').where('status','==','active'));if(admins.size<=1)throw new NativeDirectoryError('At least one active administrator is required',409);}const id=randomBytes(12).toString('hex'),now=new Date();tx.create(db.collection('_nativeDeletedUsers').doc(id),{sourceId:userId,deletedBy:actorId,deletedAt:now,original:user.data()});tx.delete(user.ref);tx.create(db.collection('activitylogs').doc(id),{_id:id,userId:actorId,userRole:'admin',targetUserId:userId,action:'Deleted User',actionType:'delete',category:'profile',description:'Account deleted; related records retained for reconciliation',createdAt:now,updatedAt:now});return {success:true,message:'User deleted successfully'};});}
