import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import type {Firestore,DocumentData} from 'firebase-admin/firestore';
import {nativeDates,NativePlanEditor} from './native-plan-editor';
import {nativeClientAccess} from './native-admin-client-profile';
import {NativeDirectoryError} from './native-client-directory';
import {nativeHabitDay} from './native-habits';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {formatInTimeZone} from 'date-fns-tz';
const mapping:Record<string,string>={arms:'arm',waist:'waist',abdomen:'abd',chest:'chest',hips:'hips',thighs:'thigh'};
const key=(v:Date|string)=>formatInTimeZone(new Date(v),'Asia/Kolkata','yyyy-MM-dd');
const schema=z.object(Object.fromEntries(Object.values(mapping).map(k=>[k,z.coerce.number().min(0).max(500).optional()])));
export async function readNativeStaffMeasurements(db:Firestore,actorId:string,clientId:string){
 await nativeClientAccess(new NativePlanEditor(db),actorId,clientId);const [journals,progress]=await Promise.all([db.collection('journaltrackings').where('client','==',clientId).select('date','measurements','_nativeExternalFields').get(),db.collection('progressentries').where('user','==',clientId).where('type','in',Object.keys(mapping)).get()]);
 const grouped=new Map<string,DocumentData>();
 for(const doc of journals.docs){const j=nativeDates(await hydrateNativeDocument(doc.data()));for(const m of j.measurements||[]){const date=m.date||j.date,k=key(date),existing=grouped.get(k);if(!existing||new Date(date)>new Date(existing.date))grouped.set(k,{_id:m._id||doc.id,date,addedBy:m.addedBy||'client',...Object.fromEntries(Object.values(mapping).map(k=>[k,m[k]||0]))});}}
 // Journal rows have coherent grouped measurements. Use old individual entries only when no journal group exists.
 for(const doc of progress.docs.sort((a,b)=>b.get('recordedAt').toMillis()-a.get('recordedAt').toMillis())){const e=nativeDates(doc.data()),k=key(e.recordedAt);if(!grouped.has(k))grouped.set(k,{_id:doc.id,date:e.recordedAt,addedBy:e.metadata?.addedBy||'client',...Object.fromEntries(Object.values(mapping).map(k=>[k,0])),_legacy:true});const row=grouped.get(k)!;if(row._legacy&&!row[mapping[e.type]])row[mapping[e.type]]=Number(e.value)||0;}
 const measurements=[...grouped.values()].map(({_legacy,...d})=>d).sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());return {measurements,latest:measurements[0]||null};
}
async function txAccess(tx:FirebaseFirestore.Transaction,db:Firestore,actorId:string,clientId:string){const [a,c]=await tx.getAll(db.collection('users').doc(actorId),db.collection('users').doc(clientId));if(!a.exists||a.get('status')!=='active'||!['admin','dietitian','health_counselor'].includes(a.get('role')))throw new NativeDirectoryError('Access denied',403);if(!c.exists||c.get('role')!=='client')throw new NativeDirectoryError('Client not found',404);if(a.get('role')!=='admin'&&![c.get('assignedDietitian'),c.get('assignedHealthCounselor'),...(c.get('assignedDietitians')||[]),...(c.get('assignedHealthCounselors')||[])].includes(actorId))throw new NativeDirectoryError('Access denied',403);return a.get('role') as string;}
export async function addNativeStaffMeasurements(db:Firestore,actorId:string,clientId:string,input:unknown){const parsed=schema.safeParse(input);if(!parsed.success||!Object.values(parsed.data).some(v=>Number(v)>0))throw new NativeDirectoryError('Provide at least one positive measurement');const values=parsed.data,now=new Date(),day=nativeHabitDay(undefined),id=randomBytes(12).toString('hex');
 return db.runTransaction(async tx=>{const role=await txAccess(tx,db,actorId,clientId);const rows=await tx.get(db.collection('journaltrackings').where('client','==',clientId).where('date','>=',day.start).where('date','<',day.end).limit(2));if(rows.size>1)throw new NativeDirectoryError('Duplicate journal dates require reconciliation',409);const current=rows.docs[0],journal=current?nativeDates(await hydrateNativeDocument(current.data())):null;const ref=current?.ref||db.collection('journaltrackings').doc(createHash('sha256').update(clientId+'\0'+day.key).digest('hex').slice(0,24));if(!current&&(await tx.get(ref)).exists)throw new NativeDirectoryError('Journal identity conflict',409);
 const entry={_id:id,...Object.fromEntries(Object.values(mapping).map(k=>[k,values[k]||0])),date:now,addedBy:role,createdAt:now};const entries=Object.entries(mapping).filter(([,k])=>Number(values[k])>0).map(([type,k])=>({_id:randomBytes(12).toString('hex'),user:clientId,type,value:values[k],unit:'cm',recordedAt:now,metadata:{addedBy:role,addedById:actorId,measurementId:id},createdAt:now,updatedAt:now}));
 if(current)tx.update(ref,await prepareNativePatch(current.data(),{measurements:[...(journal.measurements||[]),entry],updatedAt:now}));else tx.create(ref,await prepareNativeDocument({_id:ref.id,client:clientId,date:day.start,water:[],activities:[],steps:[],sleep:[],meals:[],progress:[],bca:[],measurements:[entry],createdAt:now,updatedAt:now}));for(const e of entries)tx.create(db.collection('progressentries').doc(e._id),e);return {success:true,entries,journalMeasurement:entry,message:'Measurements added successfully'};});
}
export async function deleteNativeStaffMeasurements(db:Firestore,actorId:string,clientId:string,id:string){return db.runTransaction(async tx=>{await txAccess(tx,db,actorId,clientId);const [journals,entries]=await Promise.all([tx.get(db.collection('journaltrackings').where('client','==',clientId)),tx.get(db.collection('progressentries').where('user','==',clientId).where('type','in',Object.keys(mapping)))]);const hydrated=await Promise.all(journals.docs.map(async doc=>({doc,data:nativeDates(await hydrateNativeDocument(doc.data()))})));let selectedDay:string|undefined;const selected=entries.docs.find(d=>d.id===id);if(selected)selectedDay=key(nativeDates(selected.get('recordedAt')));for(const {doc,data} of hydrated){const match=(data.measurements||[]).find((m:DocumentData)=>m._id===id||doc.id===id);if(match)selectedDay=key(match.date||data.date);}if(!selectedDay)throw new NativeDirectoryError('Measurement not found',404);
 for(const {doc,data} of hydrated){const remaining=(data.measurements||[]).filter((m:DocumentData)=>key(m.date||data.date)!==selectedDay);if(remaining.length!==(data.measurements||[]).length)tx.update(doc.ref,await prepareNativePatch(doc.data(),{measurements:remaining,updatedAt:new Date()}));}for(const doc of entries.docs)if(key(nativeDates(doc.get('recordedAt')))===selectedDay)tx.delete(doc.ref);return {success:true};});}
