import {createHash} from 'node:crypto';
import {z} from 'zod';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {formatInTimeZone,fromZonedTime} from 'date-fns-tz';
import {NativePlanEditor} from './native-plan-editor';
import {NativeDirectoryError} from './native-client-directory';
const providers=z.enum(['apple_watch','google_fit','fitbit','samsung','garmin','noisefit','other']);
const preference=z.object(Object.fromEntries(['syncSteps','syncHeartRate','syncSleep','syncOxygen','syncStress','syncBreathing','syncActivity','syncCalories'].map(k=>[k,z.boolean().optional()])));
const connectionSchema=z.object({watchProvider:providers.optional(),watchIsConnected:z.boolean().optional(),watchSyncEnabled:z.boolean().optional(),watchDeviceName:z.string().max(200).optional(),watchDeviceModel:z.string().max(200).optional(),watchDeviceId:z.string().max(200).optional(),watchSyncPreferences:preference.optional(),watchAutoSyncInterval:z.number().int().min(5).max(1440).optional(),watchLastSync:z.coerce.date().optional(),watchAccessToken:z.string().max(16000).nullable().optional(),watchRefreshToken:z.string().max(16000).nullable().optional(),watchTokenExpiry:z.coerce.date().nullable().optional()});
const n=z.number().finite().min(0).max(1000000),date=z.coerce.date(),reading=z.array(z.object({value:n,timestamp:date})).max(5000),numeric=(keys:string[])=>Object.fromEntries(keys.map(k=>[k,n.optional()]));
const healthSchema=z.object({watchSteps:z.object({count:n,goal:n.optional(),distance:n.optional(),timestamp:date.optional()}).optional(),watchHeartRate:z.object({...numeric(['current','min','max','average','restingHr']),readings:reading.optional()}).optional(),watchOxygen:z.object({...numeric(['current','min','max','average']),readings:reading.optional()}).optional(),watchStress:z.object({...numeric(['current','average']),level:z.enum(['low','moderate','high','very_high']).optional(),readings:reading.optional()}).optional(),watchBreathing:z.object(numeric(['current','average','min','max'])).optional(),watchCalories:z.object(numeric(['total','active','resting','goal'])).optional(),watchSleep:z.object({...numeric(['totalHours','deepSleepHours','lightSleepHours','remSleepHours','awakeDuration']),sleepStart:date.optional(),sleepEnd:date.optional(),sleepQuality:z.enum(['poor','fair','good','excellent']).optional()}).optional(),watchActivity:z.object({...numeric(['activeMinutes','sedentaryMinutes','standingHours']),workouts:z.array(z.object({type:z.string().max(100),duration:n,caloriesBurned:n,startTime:date,endTime:date})).max(1000).optional()}).optional(),watchDevice:z.object({name:z.string().max(200),type:providers,model:z.string().max(200).optional(),lastSyncTime:date}).optional()});
async function owner(editor:NativePlanEditor,userId:string){const user=await editor.document('users',userId);if(!user||user.status!=='active')throw new NativeDirectoryError('Active account required',403);return user;}
export async function nativeWatchConnection(db:MongoDatabase,userId:string,patch?:unknown,tokens=false){const parsed=patch===undefined?null:connectionSchema.safeParse(patch);if(parsed&&!parsed.success)throw new NativeDirectoryError('Invalid watch settings');for(let attempt=0;attempt<5;attempt++){const editor=new NativePlanEditor(db);await owner(editor,userId);const rows=await editor.query('watchconnections',[['userId','==',userId]]);if(rows.length>1)throw new NativeDirectoryError('Duplicate watch connection requires reconciliation',409);const current=rows[0]?await editor.hydrate(rows[0]):null;if(!parsed){if(!current)return null;const {watchAccessToken,watchRefreshToken,...safe}=current;return tokens?current:safe;}const now=new Date(),id=current?._id||createHash('sha256').update('watch\0'+userId).digest('hex').slice(0,24),data:DocumentData={...(current||{_id:id,userId,createdAt:now,watchIsConnected:false,watchSyncEnabled:true,watchSyncPreferences:Object.fromEntries(Object.keys(preference.shape).map(k=>[k,true])),watchAutoSyncInterval:60}),...parsed.data,updatedAt:now};if(!data.watchProvider)throw new NativeDirectoryError('Watch provider required');if(parsed.data.watchSyncPreferences)data.watchSyncPreferences={...(current?.watchSyncPreferences||{}),...parsed.data.watchSyncPreferences};if(await editor.commit(current?[{collection:'watchconnections',id,patch:data}]:[],current?[]:[{collection:'watchconnections',id,data}])){const {watchAccessToken,watchRefreshToken,...safe}=data;return tokens?data:safe;}}throw new NativeDirectoryError('Watch connection changed; retry',409);}
export async function nativeWatchHealth(db:MongoDatabase,userId:string,start?:Date,end?:Date,input?:unknown){const editor=new NativePlanEditor(db),user=await owner(editor,userId),zone=typeof user.timezone==='string'?user.timezone:'Asia/Kolkata';try{new Intl.DateTimeFormat('en',{timeZone:zone});}catch{throw new NativeDirectoryError('Invalid account timezone');}if(start&&!Number.isFinite(start.getTime())||end&&!Number.isFinite(end.getTime()))throw new NativeDirectoryError('Invalid watch data range');const day=formatInTimeZone(start||new Date(),zone,'yyyy-MM-dd'),from=fromZonedTime(day+'T00:00:00',zone),next=new Date(day+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+1);const until=end||new Date(fromZonedTime(next.toISOString().slice(0,10)+'T00:00:00',zone).getTime()-1);if(!Number.isFinite(from.getTime())||!Number.isFinite(until.getTime())||from>until||until.getTime()-from.getTime()>366*86400000)throw new NativeDirectoryError('Invalid watch data range');if(input===undefined){const rows=await editor.query('watchhealthdatas',[['userId','==',userId],['date','>=',from],['date','<=',until]]);return Promise.all(rows.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).map(row=>editor.hydrate(row)));}
 const parsed=healthSchema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid watch health data');for(let attempt=0;attempt<5;attempt++){const txEditor=new NativePlanEditor(db);await owner(txEditor,userId);const rows=await txEditor.query('watchhealthdatas',[['userId','==',userId],['date','>=',from],['date','<=',until]]);if(rows.length>1)throw new NativeDirectoryError('Duplicate daily watch records require reconciliation',409);const current=rows[0]?await txEditor.hydrate(rows[0]):null,id=current?._id||createHash('sha256').update(userId+'\0'+day).digest('hex').slice(0,24),now=new Date(),data:DocumentData={...(current||{_id:id,userId,date:from,createdAt:now}),...parsed.data,updatedAt:now};if(await txEditor.commit(current?[{collection:'watchhealthdatas',id,patch:data}]:[],current?[]:[{collection:'watchhealthdatas',id,data}]))return [data];}throw new NativeDirectoryError('Watch health record changed; retry',409);
}
export async function saveNativeWatchOAuthState(db:MongoDatabase,userId:string,hash:string){await db.runTransaction(async tx=>{const actor=await tx.get(db.collection('users').doc(userId));if(actor.get('status')!=='active')throw new NativeDirectoryError('Active account required',403);tx.create(db.collection('_nativeWatchOAuthStates').doc(hash),{userId,provider:'google_fit',expiresAt:new Date(Date.now()+600000),createdAt:new Date()});});}
export async function consumeNativeWatchOAuthState(db:MongoDatabase,userId:string,hash:string){return db.runTransaction(async tx=>{const ref=db.collection('_nativeWatchOAuthStates').doc(hash),[actor,state]=await tx.getAll(db.collection('users').doc(userId),ref);if(actor.get('status')!=='active'||state.get('userId')!==userId||state.get('provider')!=='google_fit'||!state.get('expiresAt')?.toMillis||state.get('expiresAt').toMillis()<Date.now())throw new NativeDirectoryError('Invalid OAuth state',403);tx.delete(ref);return 'google_fit';});}
