import {nativeMigrationIssues} from './native-migration-issues';
import {MEAL_TYPE_KEYS,MEAL_TYPES} from '@/lib/mealConfig';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {FieldPath,type Firestore,type DocumentData} from 'firebase-admin/firestore';
import {modelRegistry,type RegisteredModel,type SchemaFieldInfo} from '@/lib/import/modelRegistry';
import {requireNativeAuditAdmin} from './native-admin-audit';
import {NativeDirectoryError} from './native-client-directory';
import {hydrateNativeDocument,prepareNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
import {nativeDates} from './native-plan-editor';
import {updateNativeUser} from './native-user-admin';
const blocked=/(?:password|token|secret|credential|logoutAllSessions|keepSession|otp|resetCode)/i;
export const allowedCatalogField=(path:string)=>!path.split('.').some(key=>key.startsWith('_')||key.startsWith('$')||['__proto__','constructor','prototype'].includes(key)||blocked.test(key));
export function nativeAdminCatalog(name:string){const model=modelRegistry.get(name);if(!model)throw new NativeDirectoryError('Model not found',404);return model;}
export function nativeCatalogFields(model:RegisteredModel){return model.fields.filter(f=>allowedCatalogField(f.path));}
export function safeNativeCatalogDocument(model:RegisteredModel,input:DocumentData):DocumentData {const allowed=new Set(nativeCatalogFields(model).map(f=>f.path.split('.')[0]));const clean=(value:any):any=>Array.isArray(value)?value.map(clean):value&&typeof value==='object'&&!(value instanceof Date)?Object.fromEntries(Object.entries(value).filter(([key])=>allowedCatalogField(key)||key==='_id').map(([key,v])=>[key,clean(v)])):value;return {...(nativeMigrationIssues(input._nativeMigrationIssues).length?{_nativeMigrationIssues:nativeMigrationIssues(input._nativeMigrationIssues)}:{}),...Object.fromEntries(Object.entries(nativeDates(input)).filter(([key])=>key==='_id'||allowed.has(key)).map(([k,v])=>[k,clean(v)]))};}
const modelNameIsPayment=(model:RegisteredModel)=>model.name==='UnifiedPayment';
function assignPath(target:DocumentData,path:string,value:unknown){const keys=path.split('.');let obj=target;for(const key of keys.slice(0,-1)){if(!obj[key]||typeof obj[key]!=='object')obj[key]={};obj=obj[key];}obj[keys.at(-1)!]=value;}
const valueAt=(row:DocumentData,path:string)=>Object.hasOwn(row,path)?row[path]:path.split('.').reduce((o,k)=>o?.[k],row);
export function normalizeCatalogRow(model:RegisteredModel,input:DocumentData,defaults=false){const row:DocumentData={};for(const field of nativeCatalogFields(model)){if(['createdAt','updatedAt'].includes(field.path))continue;let value=valueAt(input,field.path);if(value===undefined&&defaults){if(field.default!==undefined)value=structuredClone(field.default);else if(field.defaultKind==='now')value=new Date();else if(field.defaultKind==='factory'){if(field.path==='uuid')value=randomUUID();else if(model.name==='DietTemplate'&&field.path==='mealTypes')value=MEAL_TYPE_KEYS.map(key=>({name:MEAL_TYPES[key].label,time:MEAL_TYPES[key].time12h}));else if(field.type==='Mixed')value={};}else if(field.isArray)value=[];}if(value===undefined)continue;const cast=(f:SchemaFieldInfo,v:any):any=>{if(v===null)return v;if(f.isArray&&Array.isArray(v)){const inner=f.type.match(/^Array<(.+)>$/)?.[1];return v.map(entry=>f.nestedFields?Object.fromEntries(f.nestedFields.filter(n=>allowedCatalogField(n.path)).map(n=>{const key=n.path.slice(f.path.length+1);return [key,cast(n,valueAt(entry,key))];}).filter(([,item])=>item!==undefined)):inner?cast({...f,isArray:false,type:inner},entry):entry);}if(f.type==='Date')return new Date(v);if(f.type==='Number')return Number(v);if(f.type==='Boolean')return typeof v==='boolean'?v:['true','1'].includes(String(v).toLowerCase());return v;};assignPath(row,field.path,cast(field,value));}return row;}
export async function readNativeDataRecords(db:Firestore,actorId:string,params:URLSearchParams){await requireNativeAuditAdmin(db,actorId);const model=nativeAdminCatalog(params.get('model')||''),id=params.get('id'),fields=nativeCatalogFields(model).map(({path,type,required,enum:values})=>({path,type,required,enum:values}));if(id){if(!/^[a-f0-9]{24}$/i.test(id))throw new NativeDirectoryError('Invalid record ID');const doc=await db.collection(model.collection).doc(id).get();if(!doc.exists)throw new NativeDirectoryError('Record not found',404);const record=safeNativeCatalogDocument(model,{...await hydrateNativeDocument(doc.data()!),_id:id}),relatedData:DocumentData={};if(model.name==='User'){for(const [key,collection,field,count] of [['lifestyleInfo','lifestyleinfos','userId',1],['medicalInfo','medicalinfos','userId',1],['dietaryRecall','dietaryrecalls','userId',1],['recentMealPlans','clientmealplans','clientId',5],['recentTasks','tasks','client',10],['recentPayments','unifiedpayments','client',10],['recentAppointments','appointments','client',10]] as const){const relatedModel=modelRegistry.getAll().find(m=>m.collection===collection);const rows=await db.collection(collection).where(field,'==',id).limit(count).get();const data=await Promise.all(rows.docs.map(async d=>safeNativeCatalogDocument(relatedModel!,{...await hydrateNativeDocument(d.data()),_id:d.id})));relatedData[key]=count===1?data[0]||null:data;}}return {success:true,record,relatedData,fields};}
 const page=Math.max(1,Math.floor(Number(params.get('page'))||1)),limit=Math.min(200,Math.max(1,Math.floor(Number(params.get('limit'))||20))),search=params.get('search')?.trim().toLowerCase(),requestedSort=params.get('sortBy')||'createdAt',sort=requestedSort==='_id'?FieldPath.documentId():nativeCatalogFields(model).some(f=>f.path===requestedSort)?requestedSort:FieldPath.documentId(),direction=params.get('sortOrder')==='asc'?'asc':'desc';let rows:FirebaseFirestore.DocumentSnapshot[],total:number;
 if(search){const searchable=nativeCatalogFields(model).filter(f=>['String','Number','ObjectId'].includes(f.type)&&!f.isNested).map(f=>f.path);const matchedClients=new Set<string>();if(modelNameIsPayment(model)){const users=await db.collection('users').select('clientId','dtps_id','firstName','lastName','email').get();users.docs.forEach(doc=>{if(['clientId','dtps_id','firstName','lastName','email'].some(k=>String(doc.get(k)||'').toLowerCase().includes(search)))matchedClients.add(doc.id);});}const candidates=await db.collection(model.collection).select(...searchable).orderBy(sort,direction).get();const matches=candidates.docs.filter(doc=>matchedClients.has(doc.get('client'))||doc.id.includes(search)||searchable.some(key=>String(doc.get(key)||'').toLowerCase().includes(search)));total=matches.length;const ids=matches.slice((page-1)*limit,page*limit).map(d=>d.id);rows=ids.length?await db.getAll(...ids.map(v=>db.collection(model.collection).doc(v))):[];}else{const [count,result]=await Promise.all([db.collection(model.collection).count().get(),db.collection(model.collection).orderBy(sort,direction).offset((page-1)*limit).limit(limit).get()]);total=count.data().count;rows=result.docs;}
 const records=await Promise.all(rows.map(async doc=>safeNativeCatalogDocument(model,{...await hydrateNativeDocument(doc.data()!),_id:doc.id})));if(modelNameIsPayment(model)){const ids=[...new Set(records.map(r=>r.client).filter((id):id is string=>typeof id==='string'&&!id.includes('/')))];const people=new Map<string,DocumentData>();for(let i=0;i<ids.length;i+=100){for(const doc of await db.getAll(...ids.slice(i,i+100).map(id=>db.collection('users').doc(id)),{fieldMask:['firstName','lastName','clientId','dtps_id']}))if(doc.exists)people.set(doc.id,doc.data()!);}records.forEach(record=>{const user=people.get(record.client);record.clientName=[user?.firstName,user?.lastName].filter(Boolean).join(' ');record.clientDisplayId=user?.clientId||user?.dtps_id||'';record.cId=record.clientDisplayId;});if(['clientName','clientDisplayId','cId'].includes(requestedSort))records.sort((a,b)=>String(a[requestedSort]).localeCompare(String(b[requestedSort]))*(direction==='asc'?1:-1));}return {success:true,modelName:model.name,displayName:model.displayName,records,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)},fields};
}
export function reconcileNativeAllocation(current:DocumentData,patch:DocumentData){if(!['durationDays','daysUsed','remainingDays'].some(k=>k in patch))return;const duration=Number(patch.durationDays??current.durationDays),used=Number(patch.daysUsed??current.daysUsed??0),remaining=Number(patch.remainingDays??current.remainingDays??duration-used);if(![duration,used,remaining].every(v=>Number.isInteger(v)&&v>=0))throw new NativeDirectoryError('Program days must be nonnegative integers');const remainingChanged='remainingDays'in patch&&remaining!==Number(current.remainingDays),usedChanged='daysUsed'in patch&&used!==Number(current.daysUsed);const nextUsed=remainingChanged&&!usedChanged?duration-remaining:used;if(nextUsed<0||nextUsed>duration)throw new NativeDirectoryError('Used days cannot exceed the program duration');patch.durationDays=duration;patch.daysUsed=nextUsed;patch.remainingDays=duration-nextUsed;}
export async function updateNativeDataRecord(db:Firestore,actorId:string,modelName:string,id:string,input:DocumentData){const model=nativeAdminCatalog(modelName);if(!/^[a-f0-9]{24}$/i.test(id)||!input||typeof input!=='object'||Array.isArray(input))throw new NativeDirectoryError('Invalid record');if(modelName==='User')return updateNativeUser(db,actorId,id,input,{adminOnly:true});const patch=normalizeCatalogRow(model,input);if(modelName==='ClientMealPlan'&&Object.keys(patch).some(key=>!['name','description','notes','goal'].includes(key)))throw new NativeDirectoryError('Use the plan editor to change schedule, publication, meals or allocation');
 return db.runTransaction(async tx=>{const [actor,doc]=await tx.getAll(db.collection('users').doc(actorId),db.collection(model.collection).doc(id));if(actor.get('role')!=='admin'||actor.get('status')!=='active')throw new NativeDirectoryError('Forbidden',403);if(!doc.exists)throw new NativeDirectoryError('Record not found',404);const current=nativeDates(await hydrateNativeDocument(doc.data()!));if(modelName==='UnifiedPayment')reconcileNativeAllocation(current,patch);const check=await modelRegistry.validateRow(modelName,{...current,...patch},0);if(!check.isValid)throw new NativeDirectoryError(check.errors.map(e=>e.field+': '+e.message).join('; '));
 for(const field of model.fields.filter(f=>f.ref&&!f.path.includes('.')&&f.path in patch)){const target=modelRegistry.get(field.ref!);if(!target)continue;const values=Array.isArray(patch[field.path])?patch[field.path]:[patch[field.path]];for(const value of values.filter(Boolean)){if(typeof value!=='string'||value.includes('/'))throw new NativeDirectoryError('Invalid reference');if(!(await tx.get(db.collection(target.collection).doc(value))).exists)throw new NativeDirectoryError(`Referenced ${field.ref} does not exist`);}}
 for(const index of model.uniqueIndexes||[]){if(!index.fields.some(field=>field in patch))continue;const values=index.fields.map(field=>valueAt({...current,...patch},field));if(values.some(v=>v==null||v==='')&&(index.sparse||index.partial))continue;let query:FirebaseFirestore.Query=db.collection(model.collection);index.fields.forEach((field,i)=>query=query.where(field,'==',values[i]??null));const matches=await tx.get(query.limit(2));if(matches.docs.some(d=>d.id!==id))throw new NativeDirectoryError('A record already uses this unique value',409);}
 const now=new Date(),auditId=randomBytes(12).toString('hex');if(modelName==='Recipe')patch.updates=[...(current.updates||[]),{updateId:auditId,updatedAt:now,updatedBy:actorId,reason:'Administrative data update',changes:Object.keys(patch).map(field=>({field,oldValue:current[field]??null,newValue:patch[field]}))}];tx.update(doc.ref,await prepareNativePatch(doc.data()!,{...patch,updatedAt:now}));tx.create(db.collection('adminauditlogs').doc(auditId),{_id:auditId,adminId:actorId,action:'data_update',targetModel:modelName,targetId:id,changedFields:Object.keys(patch),createdAt:now});return safeNativeCatalogDocument(model,{...current,...patch,_id:id});});
}
