import {createHash,randomBytes} from 'node:crypto';
import bcrypt from 'bcryptjs';
import {z} from 'zod';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {NativeDirectoryError,nativeDirectoryProfile} from './native-client-directory';
import {nativePhoneVariations} from './native-registration';
import {validatePhoneNumber,validateOptionalEmail} from '@/lib/validations/contact';
const text=z.string().max(10000).optional();
const schema=z.object({firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),phone:z.string().min(6).max(30),email:z.string().max(320).optional(),password:z.string().min(4).max(72).optional(),role:z.enum(['client','admin','dietitian','health_counselor']).optional(),bio:text,experience:z.coerce.number().min(0).max(100).optional(),consultationFee:z.coerce.number().min(0).max(10000000).optional(),specializations:z.array(z.string().max(500)).max(100).optional(),credentials:z.array(z.string().max(500)).max(100).optional(),gender:z.enum(['male','female','other']).optional(),dateOfBirth:z.string().optional(),assignedDietitian:z.string().regex(/^[a-f0-9]{24}$/i).optional(),assignedHealthCounselor:z.string().regex(/^[a-f0-9]{24}$/i).optional()});
export async function createNativeStaffUser(db:MongoDatabase,actorId:string,input:unknown){
 const parsed=schema.safeParse(input);if(!parsed.success)throw new NativeDirectoryError('Invalid user details');const b=parsed.data,role=b.role||'client',phone=validatePhoneNumber(b.phone,'+91'),emailCheck=validateOptionalEmail(b.email);if(!phone.isValid||!phone.normalized)throw new NativeDirectoryError('Invalid phone number');if(!emailCheck.isValid)throw new NativeDirectoryError('Invalid email address');if(role!=='client'&&(!b.email||!b.password))throw new NativeDirectoryError('Email and password are required for staff accounts');if(b.password&&Buffer.byteLength(b.password)>72)throw new NativeDirectoryError('Password is too long');
 const email=b.email?.trim().toLowerCase(),password=await bcrypt.hash(b.password||randomBytes(24).toString('hex'),12),id=randomBytes(12).toString('hex');
 const keys=[['phone',phone.normalized],...(email?[['email',email]]:[])].map(([kind,value])=>db.collection('_nativeUserKeys').doc(createHash('sha256').update(kind+'\0'+value).digest('hex')));
 return db.runTransaction(async tx=>{
  const actor=await tx.get(db.collection('users').doc(actorId));if(actor.get('status')!=='active'||!['admin','dietitian','health_counselor'].includes(actor.get('role')))throw new NativeDirectoryError('Staff access required',403);if(role!=='client'&&actor.get('role')!=='admin')throw new NativeDirectoryError('Only administrators can create staff accounts',403);
  const dt=role==='client'?(actor.get('role')==='dietitian'?actorId:b.assignedDietitian):undefined,hc=role==='client'?(actor.get('role')==='health_counselor'?actorId:b.assignedHealthCounselor):undefined;
  for(const [staffId,staffRole] of [[dt,'dietitian'],[hc,'health_counselor']])if(staffId){const staff=await tx.get(db.collection('users').doc(staffId));if(staff.get('role')!==staffRole||staff.get('status')!=='active')throw new NativeDirectoryError('Invalid assigned professional');}
  const claims=await tx.getAll(...keys),phones=await tx.get(db.collection('users').where('phone','in',nativePhoneVariations(phone.normalized!)).limit(1)),emails=email?await tx.get(db.collection('users').where('email','==',email).limit(1)):null;if(claims.some(d=>d.exists)||!phones.empty||emails&&!emails.empty)throw new NativeDirectoryError('Phone number or email is already registered',409);
  let clientId:string|undefined;const counter=db.collection('_nativeCounters').doc('clientIds');let seq:number|undefined;if(role==='client'){const c=await tx.get(counter);seq=c.get('seq');if(!Number.isSafeInteger(seq)||seq!<0)throw new NativeDirectoryError('Client counter requires reconciliation',503);clientId='C-'+(seq!+1);}
  const now=new Date(),{assignedDietitian,assignedHealthCounselor,dateOfBirth,...rest}=b;let dob:Date|undefined;if(dateOfBirth){dob=new Date(dateOfBirth);if(!Number.isFinite(dob.getTime())||dob>now||dob.getUTCFullYear()<1900)throw new NativeDirectoryError('Invalid date of birth');}
  const data:DocumentData=Object.fromEntries(Object.entries({...rest,role,status:'active',phone:phone.normalized,email,password,_id:id,clientId,...(dob?{dateOfBirth:dob}:{}),...(dt?{assignedDietitian:dt,assignedDietitians:[]}:{}),...(hc?{assignedHealthCounselor:hc,assignedHealthCounselors:[]}:{}),createdBy:{userId:actorId,role:actor.get('role')},clientStatus:'lead',emailVerified:false,onboardingCompleted:false,holdStatus:{isOnHold:false,totalHoldDurationMs:0,holdCount:0},createdAt:now,updatedAt:now}).filter(([,v])=>v!==undefined));
  if(seq!==undefined)tx.update(counter,{seq:seq+1});tx.create(db.collection('users').doc(id),data);for(const key of keys)tx.create(key,{userId:id,createdAt:now});tx.create(db.collection('activitylogs').doc(id),{_id:id,userId:actorId,userRole:actor.get('role'),action:'Created User',actionType:'create',category:'profile',targetUserId:id,description:'Created '+role+' account',createdAt:now,updatedAt:now});return nativeDirectoryProfile(id,data);
 });
}
