import {getApplicableHoldExtensionMs as applicable} from '@/lib/status/holdExtension';
import {randomBytes} from 'node:crypto';
import type {MongoDatabase,DocumentData} from '@/lib/db/mongo-types';
import {NativePlanEditor} from './native-plan-editor';
import {nativeClientAccess} from './native-admin-client-profile';
import {NativeDirectoryError} from './native-client-directory';
import {computeClientStatusFromDocs} from '@/lib/status/computeClientStatus';
export function nativeHoldDuration(ms:number){const minutes=Math.floor(Math.max(0,ms)/60000),days=Math.floor(minutes/1440),hours=Math.floor(minutes/60)%24;return [days?`${days} day${days===1?'':'s'}`:'',hours?`${hours} hour${hours===1?'':'s'}`:'',minutes%60?`${minutes%60} minute${minutes%60===1?'':'s'}`:''].filter(Boolean).join(', ')||'0 minutes';}
export async function changeNativeClientHold(db:MongoDatabase,actorId:string,clientId:string,onHold:boolean,reason='',now=new Date()){
 if(typeof reason!=='string'||reason.length>5000)throw new NativeDirectoryError('Invalid reason');
 for(let attempt=0;attempt<5;attempt++){
  const editor=new NativePlanEditor(db);const access=await nativeClientAccess(editor,actorId,clientId);if(!['admin','dietitian'].includes(access.actor.role))throw new NativeDirectoryError('Admin or assigned dietitian access required',403);const client=await editor.hydrate(access.client),actor=access.actor;
  if(!!client.holdStatus?.isOnHold===onHold)throw new NativeDirectoryError(onHold?'Client is already on hold':'Client is not on hold',409);
  const old=client.holdStatus||{},holdStart=old.holdDate?new Date(old.holdDate):null,duration=!onHold&&holdStart?Math.max(0,now.getTime()-holdStart.getTime()):0;
  if(!onHold&&(!holdStart||!Number.isFinite(holdStart.getTime())))throw new NativeDirectoryError('Hold start date requires reconciliation',409);
  const payments=await editor.query('unifiedpayments',[['client','==',clientId]]);const legacy=!onHold?await editor.query('clientpurchases',[['client','==',clientId]]):[];
  const mutations:Array<{collection:string;id:string;patch:DocumentData}>=[];let totalAddedMs=0;
  if(!onHold)for(const [collection,rows] of [['unifiedpayments',payments],['clientpurchases',legacy]] as const){for(const raw of rows){if(raw.paymentStatus!=='paid'||!(collection==='unifiedpayments'?['paid','active','completed']:['active','pending']).includes(raw.status))continue;const p=await editor.hydrate(raw),addedMs=applicable(p,holdStart!,now);if(!addedMs)continue;const previousExpectedEndDate=new Date(p.expectedEndDate||p.endDate),newExpectedEndDate=new Date(previousExpectedEndDate.getTime()+addedMs);const patch={expectedEndDate:newExpectedEndDate,endDate:newExpectedEndDate,originalExpectedEndDate:p.originalExpectedEndDate||previousExpectedEndDate,holdExtensionMs:Number(p.holdExtensionMs||0)+addedMs,holdExtensionHistory:[...(p.holdExtensionHistory||[]),{holdStart,holdEnd:now,addedMs,previousExpectedEndDate,newExpectedEndDate,appliedBy:actorId,appliedAt:now}]};mutations.push({collection,id:p._id,patch});if(collection==='unifiedpayments')Object.assign(raw,patch);totalAddedMs+=addedMs;}}
  const status=onHold?'hold':computeClientStatusFromDocs(payments,false),time=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);
  const holdStatus=onHold?{...old,isOnHold:true,holdDate:now,holdTime:time,heldBy:actorId,holdCount:Number(old.holdCount||0)+1}:{...old,isOnHold:false,activatedDate:now,activatedTime:time,activatedBy:actorId,totalHoldDurationMs:Number(old.totalHoldDurationMs||0)+duration};
  const history=[...(client.holdStatusHistory||[]),{action:onHold?'hold':'activate',performedBy:actorId,performedByName:[actor.firstName,actor.lastName].filter(Boolean).join(' '),performedByRole:actor.role,timestamp:now,reason,...(!onHold?{holdDurationMs:duration}:{})}];
  const extendedCount=mutations.length;mutations.push({collection:'users',id:clientId,patch:{holdStatus,holdStatusHistory:history,clientStatus:status,clientStatusHistory:[...(client.clientStatusHistory||[]),{previousStatus:client.clientStatus||null,newStatus:status,changedBy:actorId,isManual:true,trigger:onHold?'hold':'resume',relatedEvent:reason||null,timestamp:now}]}});
  const id=randomBytes(12).toString('hex');if(await editor.commit(mutations,[{collection:'activitylogs',id,data:{_id:id,userId:actorId,userRole:actor.role,action:onHold?'Put Client on Hold':'Activated Client',actionType:'update',category:'profile',targetUserId:clientId,description:reason,createdAt:now,updatedAt:now}}]))return {success:true,message:onHold?'Client has been put on hold':'Client has been activated',clientStatus:status,holdStatus,holdStatusHistory:history,holdDuration:nativeHoldDuration(duration),totalHoldDuration:nativeHoldDuration(holdStatus.totalHoldDurationMs||0),endDateExtension:{extendedPurchasesCount:extendedCount,addedMs:totalAddedMs,addedFormatted:nativeHoldDuration(totalAddedMs)}};
 }
 throw new NativeDirectoryError('Client changed while saving. Please retry.',409);
}
export async function readNativeClientHold(db:MongoDatabase,actorId:string,clientId:string){const editor=new NativePlanEditor(db);const {client}=await nativeClientAccess(editor,actorId,clientId);const data=await editor.hydrate(client),h=data.holdStatus||{},current=h.isOnHold&&h.holdDate?Math.max(0,Date.now()-new Date(h.holdDate).getTime()):0;return {...h,isOnHold:!!h.isOnHold,totalHoldDurationMs:h.totalHoldDurationMs||0,totalHoldDuration:nativeHoldDuration(h.totalHoldDurationMs||0),currentHoldDurationMs:current,currentHoldDuration:nativeHoldDuration(current),holdCount:h.holdCount||0,history:(data.holdStatusHistory||[]).map((e:DocumentData)=>({...e,...(e.holdDurationMs?{holdDuration:nativeHoldDuration(e.holdDurationMs)}:{})}))};}
