import {z} from 'zod';
import type {Firestore,DocumentData} from 'firebase-admin/firestore';
import {NativeDirectoryError} from './native-client-directory';
import {hydrateNativeDocument,prepareNativePatch} from '@/lib/storage/native-document';
const time=z.string().trim().transform(value=>{const match=value.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);if(!match)return value;const hour=Number(match[1]);if(hour<1||hour>12)return value;return `${String(hour%12+(match[3].toUpperCase()==='PM'?12:0)).padStart(2,'0')}:${match[2]}`;}).pipe(z.string().regex(/^([01]?\d|2[0-3]):[0-5]\d$/)),timezone=z.string().max(100).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}},'Invalid timezone');
const settings={timezone,consultationDuration:z.number().min(15).max(180),bufferTime:z.number().min(0).max(60),maxAdvanceBooking:z.number().min(1).max(365),minAdvanceBooking:z.number().min(0).max(7)};
const complex=z.object({schedule:z.array(z.object({dayOfWeek:z.number().int().min(0).max(6),timeSlots:z.array(z.object({startTime:time,endTime:time,isAvailable:z.boolean().default(true)})).max(50)})).max(7),...settings});
const simple=z.array(z.object({day:z.string().transform(s=>s.toLowerCase()).pipe(z.enum(['sunday','monday','tuesday','wednesday','thursday','friday','saturday'])),startTime:time,endTime:time})).max(100);
function minutes(t:string){const [h,m]=t.split(':').map(Number);return h*60+m;}
function validateSlots(data:DocumentData){const days=Array.isArray(data)?data.map(d=>({day:String(d.day),slots:[d]})):data.schedule.map((d:DocumentData)=>({day:String(d.dayOfWeek),slots:d.timeSlots}));const groups=new Map<string,DocumentData[]>();for(const day of days)groups.set(day.day,[...(groups.get(day.day)||[]),...day.slots]);for(const slots of groups.values()){slots.sort((a,b)=>minutes(a.startTime)-minutes(b.startTime));for(let i=0;i<slots.length;i++)if(minutes(slots[i].startTime)>=minutes(slots[i].endTime)||i>0&&minutes(slots[i-1].endTime)>minutes(slots[i].startTime))throw new NativeDirectoryError('Time slots must have a positive duration and must not overlap');}}
export async function nativeUserAvailability(db:Firestore,actorId:string,targetId:string,input?:unknown,replace=false){
 if(!/^[a-f0-9]{24}$/i.test(targetId))throw new NativeDirectoryError('Invalid professional ID');
 return db.runTransaction(async tx=>{const [actor,target]=await tx.getAll(db.collection('users').doc(actorId),db.collection('users').doc(targetId));if(actor.get('status')!=='active')throw new NativeDirectoryError('Access denied',403);if(!target.exists||!['dietitian','health_counselor'].includes(target.get('role')))throw new NativeDirectoryError('Professional not found',404);if(input===undefined){if(actorId!==targetId&&!['admin','client'].includes(actor.get('role')))throw new NativeDirectoryError('Access denied',403);const data=await hydrateNativeDocument(target.data()!);return {availability:data.availability||[]};}if(actorId!==targetId||!['dietitian','health_counselor'].includes(actor.get('role')))throw new NativeDirectoryError('Only professionals can change their own availability',403);if(!input||typeof input!=='object'||Array.isArray(input))throw new NativeDirectoryError('Invalid availability');const b=input as DocumentData,current=await hydrateNativeDocument(target.data()!);let availability:DocumentData;
 if(Array.isArray(b.availability)){const parsed=simple.safeParse(b.availability);if(!parsed.success)throw new NativeDirectoryError('Invalid availability slots');availability=parsed.data;}else if(replace||b.schedule){const parsed=complex.safeParse({consultationDuration:60,bufferTime:15,maxAdvanceBooking:30,minAdvanceBooking:1,...b});if(!parsed.success)throw new NativeDirectoryError('Invalid availability schedule');availability=parsed.data;}else{const parsed=z.object(settings).partial().safeParse(b);if(!parsed.success)throw new NativeDirectoryError('Invalid availability settings');if(Array.isArray(current.availability))throw new NativeDirectoryError('Send a full schedule when changing to advanced availability');availability={...(current.availability||{schedule:[]}),...parsed.data};}
 validateSlots(availability);if(!Array.isArray(availability)&&availability.minAdvanceBooking>availability.maxAdvanceBooking)throw new NativeDirectoryError('Minimum booking notice cannot exceed maximum');tx.update(target.ref,await prepareNativePatch(target.data()!,{availability,updatedAt:new Date()}));return {message:'Availability updated successfully',availability};
 });
}
