import {FieldPath,Filter,type Firestore,type DocumentData} from 'firebase-admin/firestore';
import {nativeFinanceActor,nativeFinancePeople} from './native-finance-access';
import {NativeCheckoutError,settleNativeCapturedPayment} from './native-checkout';
import {verifyNativePaymentLink} from './native-payment-link';
import {nativeDates} from './native-plan-editor';
export async function requireNativeFinanceAdmin(db:Firestore,id:string){if((await nativeFinanceActor(db,id)).role!=='admin')throw new NativeCheckoutError('Admin required',403);}
export async function nativeAdminPayments(db:Firestore,actor:string,params:URLSearchParams){
 await requireNativeFinanceAdmin(db,actor);const col=db.collection('unifiedpayments');let query:FirebaseFirestore.Query=col;const status=params.get('status'),type=params.get('type');if(status&&status!=='all')query=query.where('status','==',status);if(type&&type!=='all')query=query.where('paymentType','==',type);const limit=Math.max(1,Math.min(200,Number(params.get('limit'))||100)),skip=Math.max(0,Math.min(100000,Number(params.get('skip'))||0));
 const paid=col.where(Filter.or(Filter.where('paymentStatus','==','paid'),Filter.where('status','in',['paid','completed'])));
 const [rows,total,completed,pending,failed,revenue]=await Promise.all([query.orderBy('createdAt','desc').offset(skip).limit(limit).get(),col.count().get(),paid.count().get(),col.where('status','==','pending').count().get(),col.where('status','==','failed').count().get(),paid.select('finalAmount','baseAmount','amount','currency').get()]);
 const totals:Record<string,number>={};for(const row of revenue.docs){const amount=Number(row.get('finalAmount')??row.get('baseAmount')??row.get('amount')??0),currency=row.get('currency')||'INR';if(Number.isFinite(amount))totals[currency]=(totals[currency]||0)+amount;}
 const payments=await nativeFinancePeople(db,rows.docs.map(row=>{const data=nativeDates(row.data()!);return Object.fromEntries(Object.entries({...data,_id:row.id,type:data.paymentType||'service_plan'}).filter(([key])=>!key.startsWith('_native')&&!/signature|secret/i.test(key)));}));
 return {payments,stats:{totalPayments:total.data().count,completedPayments:completed.data().count,pendingPayments:pending.data().count,failedPayments:failed.data().count,totalRevenue:totals.INR||0,revenueByCurrency:totals}};
}
export async function nativeNormalizePaymentStatuses(db:Firestore,actor:string,cursor?:string){await requireNativeFinanceAdmin(db,actor);let query=db.collection('unifiedpayments').orderBy(FieldPath.documentId()).limit(200);if(cursor)query=query.startAfter(cursor);const rows=await query.get();let updated=0;for(const row of rows.docs){await db.runTransaction(async tx=>{const [current,user]=await tx.getAll(row.ref,db.collection('users').doc(actor));if(user.get('role')!=='admin'||user.get('status')!=='active')throw new NativeCheckoutError('Forbidden',403);if(!current.exists)return;const paid=['paid','completed'].includes(current.get('paymentStatus'))||current.get('status')==='paid';if(paid&&(current.get('paymentStatus')!=='paid'||!['paid','completed'].includes(current.get('status')))){tx.update(row.ref,{paymentStatus:'paid',status:'paid',updatedAt:new Date()});updated++;}});}return {processed:rows.size,updated,failed:0,errors:[],nextCursor:rows.size===200?rows.docs.at(-1)!.id:null};}
export interface NativeFinanceSyncProvider{fetchLink(id:string):Promise<DocumentData>;orderPayments(id:string):Promise<DocumentData[]>}
export async function nativeSyncPayments(db:Firestore,actor:string,input:DocumentData,provider:NativeFinanceSyncProvider){
 await requireNativeFinanceAdmin(db,actor);const phase=input.phase==='payments'?'payments':'links',collection=phase==='links'?'paymentlinks':'unifiedpayments';let query=db.collection(collection).orderBy(FieldPath.documentId()).limit(15);if(typeof input.cursor==='string'&&/^[a-f0-9]{24}$/.test(input.cursor))query=query.startAfter(input.cursor);const rows=await query.get();let synced=0;const errors:{paymentId:string;error:string}[]=[];
 const authorize=async(tx:FirebaseFirestore.Transaction)=>{const user=await tx.get(db.collection('users').doc(actor));if(user.get('role')!=='admin'||user.get('status')!=='active')throw new NativeCheckoutError('Forbidden',403);};
 for(const row of rows.docs){try{if(row.get('razorpayPaymentLinkId')){const proof=await provider.fetchLink(row.get('razorpayPaymentLinkId'));if(proof.status==='paid'){await verifyNativePaymentLink(db,row.get('client'),proof.id,async()=>proof,authorize);synced++;}}else if(phase==='payments'&&row.get('razorpayOrderId')&&row.get('paymentStatus')!=='paid'){const payments=await provider.orderPayments(row.get('razorpayOrderId')),captured=payments.filter(payment=>payment.status==='captured');if(captured.length===1){await requireNativeFinanceAdmin(db,actor);await settleNativeCapturedPayment(db,row.get('client'),captured[0],authorize);synced++;}else if(captured.length>1)throw new NativeCheckoutError('Multiple captured payments require reconciliation',409);}}catch(error){errors.push({paymentId:row.id,error:error instanceof NativeCheckoutError?error.message:'Provider verification unavailable'});}}
 const next=rows.size===15?{phase,cursor:rows.docs.at(-1)!.id}:phase==='links'?{phase:'payments',cursor:null}:null;return {success:errors.length===0,synced,paymentsCreated:0,errors,next,message:`Verified ${synced} payments in this batch`};
}
