import {MongoNativeDatabase,mongoWhere,mongoCommitTime} from '@/lib/db/mongo-native';
import {encodeMongoData,decodeMongoData} from '@/lib/db/mongo-codec.mjs';
import {Timestamp,WriteResult,Filter,FieldPath,FieldValue,AggregateField,GeoPoint} from 'firebase-admin/firestore';

describe('MongoDB lossless codec and query compiler',()=>{
 test('preserves timestamp nanoseconds, nested arrays, geo and bytes',()=>{const input={date:new Timestamp(1777777777,123456789),nested:[{date:new Timestamp(-1,999999999)}],point:new GeoPoint(1,2),bytes:Buffer.from('abc')};const encoded=encodeMongoData(input),decoded=decodeMongoData(encoded.data,encoded.types);expect(decoded.date.isEqual(input.date)).toBe(true);expect(decoded.nested[0].date.isEqual(input.nested[0].date)).toBe(true);expect(decoded.point.isEqual(input.point)).toBe(true);expect(decoded.bytes.equals(input.bytes)).toBe(true);expect(encoded.data.date).toBeInstanceOf(Date);});
 test('preserves dotted and reserved fields, negative zero and full reference resources',()=>{const data=JSON.parse('{"__proto__":{"safe":true},"a.b":1,"$x":2}');data.zero=-0;data.ref={_firestoreReference:'projects/original/databases/main/documents/users/a'};const e=encodeMongoData(data),d=decodeMongoData(e.data,e.types);expect(Object.hasOwn(d,'__proto__')).toBe(true);expect(d['a.b']).toBe(1);expect(d['$x']).toBe(2);expect(Object.is(d.zero,-0)).toBe(true);expect(d.ref._firestoreReference).toBe(data.ref._firestoreReference);});
 test('excludes absent fields from inequality and null equality',()=>{expect(mongoWhere('status','!=','active')).toEqual({'data.status':{$ne:'active',$exists:true}});expect(mongoWhere('x','==',null)).toEqual({'data.x':{$eq:null,$exists:true}});});
 test('compiles nested OR and array filters without client scans',()=>{expect(mongoWhere(Filter.or(Filter.where('a','==',1),Filter.where('b','array-contains','u')))).toEqual({$or:[{'data.a':{$eq:1}},{'data.b':{$elemMatch:{$eq:'u'}}}]});});
 test('rejects unknown query operators',()=>{expect(()=>mongoWhere('a','like','x')).toThrow('Unsupported');});
 test('commit versions stay valid and monotonic across the last millisecond and clock rollback',()=>{const previous=new Timestamp(100,999999999),next=mongoCommitTime(new Timestamp(100,999000000),[previous]);expect(next.seconds).toBe(101);expect(next.nanoseconds).toBe(0);expect(mongoCommitTime(new Timestamp(99,0),[next]).isEqual(new Timestamp(101,1))).toBe(true);});
});
const run=process.env.MONGODB_TEST_URI?describe:describe.skip;
run('MongoDB replica set runtime',()=>{
 let db:MongoNativeDatabase;
 beforeAll(()=>{db=new MongoNativeDatabase(process.env.MONGODB_TEST_URI!,'dtps_mongo_test_'+Date.now());});
 afterAll(async()=>{try{await (await db.database()).dropDatabase();}finally{await db.close();}});
 test('CRUD, full paths, nested groups and getAll projected ordering',async()=>{const a=db.doc('users/a'),b=db.doc('users/b');await a.create({name:'A',secret:'private',createdAt:new Timestamp(1777777777,123456789)});await b.create({name:'B'});await db.doc('users/a/logs/one').create({v:1});await db.doc('users/b/logs/one').create({v:2});const rows=await db.getAll(b,a,db.doc('users/missing'),{fieldMask:['name']});expect(rows.map(r=>r.id)).toEqual(['b','a','missing']);expect(rows[2].exists).toBe(false);expect(rows[1].get('secret')).toBeUndefined();expect((await a.get()).get('createdAt').nanoseconds).toBe(123456789);expect((await db.collection('users/a/logs').get()).size).toBe(1);expect((await db.collectionGroup('logs').get()).size).toBe(2);await expect(a.create({name:'duplicate'})).rejects.toMatchObject({code:6});await expect(db.doc('users/absent').update({name:'bad'})).rejects.toMatchObject({code:5});});
 test('transforms, dotted updates, merges and transaction rollback',async()=>{const ref=db.doc('items/transforms');await ref.set({keep:true,nested:{a:1,b:2},tags:['x']});await ref.update({'nested.a':3,tags:FieldValue.arrayUnion('x','y'),keep:FieldValue.delete(),at:FieldValue.serverTimestamp()});await ref.set({nested:{c:4}},{merge:true});let row=await ref.get();expect(row.data().nested).toEqual({a:3,b:2,c:4});expect(row.get('tags')).toEqual(['x','y']);expect(row.get('keep')).toBeUndefined();expect(row.get('at')).toBeInstanceOf(Timestamp);await expect(db.runTransaction(async tx=>{await tx.get(ref);tx.update(ref,{v:1});throw new Error('stop');})).rejects.toThrow('stop');expect((await ref.get()).get('v')).toBeUndefined();});
 test('mergeFields updates only masked values and transforms, with parent-map replacement and literal FieldPath support',async()=>{const ref=db.doc('masks/one');await ref.set({nested:{a:1,b:2},keep:true,'a.b':1,count:1,remove:'old'});
  await ref.set({nested:{a:9,b:99},ignored:'no',count:FieldValue.increment(2),remove:FieldValue.delete(),'a.b':5},{mergeFields:['nested.a','count','remove',new FieldPath('a.b')]});
  expect((await ref.get()).data()).toEqual({nested:{a:9,b:2},keep:true,'a.b':5,count:3});
  await ref.set({nested:{c:3}},{mergeFields:['nested']});expect((await ref.get()).get('nested')).toEqual({c:3});
  const before=(await ref.get()).updateTime;await expect(ref.set({nested:{a:1}},{mergeFields:['missing']})).rejects.toThrow('missing');await expect(ref.set({nested:{a:1}},{mergeFields:['nested','nested.a']})).rejects.toThrow('Overlapping');expect((await ref.get()).updateTime!.isEqual(before!)).toBe(true);
  await db.runTransaction(async tx=>{tx.set(ref,{nested:{a:4},skip:99},{mergeFields:['nested.a']});});expect((await ref.get()).get('nested')).toEqual({c:3,a:4});
 });
 test('single and batch receipts equal persisted versions and server timestamps, including repeated same-clock writes',async()=>{const ref=db.doc('receipts/one'),other=db.doc('receipts/two');const fixed=new Timestamp(2_000_000_000,999000000),clock=jest.spyOn(Timestamp,'now').mockReturnValue(fixed);
  try{const first=await ref.create({at:FieldValue.serverTimestamp()});expect(first).toBeInstanceOf(WriteResult);let row=await ref.get();expect(row.updateTime!.isEqual(first.writeTime)).toBe(true);expect(row.createTime!.isEqual(first.writeTime)).toBe(true);expect(row.get('at').isEqual(first.writeTime)).toBe(true);
   const second=await ref.update({at:FieldValue.serverTimestamp()});expect(second.writeTime.nanoseconds).toBe(999000001);expect((await ref.get()).updateTime!.isEqual(second.writeTime)).toBe(true);
   const batch=db.batch().set(ref,{at:FieldValue.serverTimestamp()}).create(other,{at:FieldValue.serverTimestamp()});const receipts=await batch.commit();expect(receipts[0].isEqual(receipts[1])).toBe(true);for(const doc of [ref,other]){row=await doc.get();expect(row.updateTime!.isEqual(receipts[0].writeTime)).toBe(true);expect(row.get('at').isEqual(receipts[0].writeTime)).toBe(true);}
   await expect(batch.commit()).rejects.toThrow('already committed');expect(()=>batch.set(ref,{v:1})).toThrow('committed');await expect(ref.update({v:99},{lastUpdateTime:first.writeTime})).rejects.toMatchObject({code:9});await expect(ref.delete({lastUpdateTime:first.writeTime})).rejects.toMatchObject({code:9});expect((await ref.get()).get('v')).toBeUndefined();
   const deleted=await ref.delete({lastUpdateTime:receipts[0].writeTime});expect(deleted.writeTime.nanoseconds).toBe(receipts[0].writeTime.nanoseconds+1);expect((await ref.get()).exists).toBe(false);
  }finally{clock.mockRestore();}
 });
 test('all writes in a transaction share one commit version and read-only callbacks cannot write',async()=>{const a=db.doc('txstamp/a'),b=db.doc('txstamp/b');await db.runTransaction(async tx=>{tx.create(a,{at:FieldValue.serverTimestamp()});tx.create(b,{at:FieldValue.serverTimestamp()});});const first=await a.get(),second=await b.get();expect(first.updateTime!.isEqual(second.updateTime!)).toBe(true);expect(first.get('at').isEqual(first.updateTime!)).toBe(true);await expect(db.runTransaction(async tx=>{tx.update(a,{v:99});},{readOnly:true})).rejects.toThrow('Read-only');expect((await a.get()).get('v')).toBeUndefined();});
 test('bounded server queries, missing fields, aggregates and snapshot cursors',async()=>{const batch=db.batch();for(const [id,price]of [['one',1],['two',2],['three',3]]as const)batch.create(db.doc('products/'+id),{price,status:'active',tags:['a']});batch.create(db.doc('products/missing'),{other:true});await batch.commit();const q=db.collection('products').where('status','==','active').orderBy('price');expect((await q.count().get()).data().count).toBe(3);expect((await q.aggregate({total:AggregateField.sum('price')}).get()).data().total).toBe(6);const first=await q.limit(1).get();expect(first.docs[0].id).toBe('one');expect((await q.startAfter(first.docs[0]).get()).docs.map(d=>d.id)).toEqual(['two','three']);expect((await db.collection('products').where('status','!=','inactive').get()).size).toBe(3);expect((await db.collection('products').where('tags','array-contains','a').get()).size).toBe(3);expect((await db.collection('products').where(FieldPath.documentId(),'==','two').get()).docs[0].id).toBe('two');expect((await q.offset(1).limit(1).get()).docs[0].id).toBe('two');});
 test('ordered limited aggregates sum the selected rows',async()=>{const batch=db.batch();batch.create(db.doc('sumlimited/a'),{price:1});batch.create(db.doc('sumlimited/b'),{price:2});batch.create(db.doc('sumlimited/c'),{price:3});await batch.commit();const result=await db.collection('sumlimited').orderBy('price','desc').limit(2).aggregate({total:AggregateField.sum('price')}).get();expect(result.data().total).toBe(5);});
 test('imported source metadata timestamps retain exact nanoseconds',async()=>{const store=(await db.database()).collection<any>('metatest');await store.insertOne({_id:'metatest/one',_collectionPath:'metatest',_collectionGroup:'metatest',data:{v:1},_types:{},_createTime:new Date('2026-10-10T00:00:00.123Z'),_updateTime:new Date('2026-10-10T00:00:01.234Z'),_sourceCreateTime:'2026-10-10T00:00:00.123456789Z',_sourceUpdateTime:'2026-10-10T00:00:01.234567890Z'});const row=await db.doc('metatest/one').get();expect(row.createTime!.nanoseconds).toBe(123456789);expect(row.updateTime!.nanoseconds).toBe(234567890);const projected=(await db.getAll(row.ref,{fieldMask:['v']}))[0];expect(projected.createTime!.isEqual(row.createTime!)).toBe(true);expect(projected.updateTime!.isEqual(row.updateTime!)).toBe(true);const queryProjected=(await db.collection('metatest').select('v').get()).docs[0];expect(queryProjected.createTime!.isEqual(row.createTime!)).toBe(true);expect(queryProjected.updateTime!.isEqual(row.updateTime!)).toBe(true);await row.ref.update({v:2});const next=await row.ref.get();expect(next.createTime!.nanoseconds).toBe(123456789);expect(next.updateTime!.isEqual(row.updateTime!)).toBe(false);});
 test('timestamp queries and cursors retain sub-millisecond ordering without lost rows',async()=>{const earlier=new Timestamp(1,100),later=new Timestamp(1,900);await db.doc('precision/a').create({at:later,value:9});await db.doc('precision/b').create({at:earlier,value:1});const q=db.collection('precision').orderBy('at');expect((await q.get()).docs.map(d=>d.id)).toEqual(['b','a']);const page=await q.limit(1).get();expect(page.docs[0].id).toBe('b');expect((await q.startAfter(page.docs[0]).get()).docs.map(d=>d.id)).toEqual(['a']);const desc=await db.collection('precision').orderBy('at','desc').limit(1).get();expect(desc.docs[0].id).toBe('a');expect((await db.collection('precision').orderBy('at','desc').startAfter(desc.docs[0]).get()).docs.map(d=>d.id)).toEqual(['b']);expect((await db.collection('precision').where('at','==',earlier).get()).docs.map(d=>d.id)).toEqual(['b']);expect((await db.collection('precision').where('at','>',earlier).get()).docs.map(d=>d.id)).toEqual(['a']);expect((await db.collection('precision').where('at','<',later).get()).docs.map(d=>d.id)).toEqual(['b']);expect((await db.collection('precision').where('at','==',new Date(1000)).count().get()).data().count).toBe(0);expect((await db.collection('precision').where('at','>',new Date(1000)).count().get()).data().count).toBe(2);expect((await db.collection('precision').where('at','in',[later]).count().get()).data().count).toBe(1);expect((await q.limit(1).aggregate({value:AggregateField.sum('value')}).get()).data().value).toBe(1);});
 test('sessions retry contention without lost increments',async()=>{const ref=db.doc('counters/one');await ref.set({v:0});await Promise.all(Array.from({length:6},()=>db.runTransaction(async tx=>{const row=await tx.get(ref);tx.update(ref,{v:row.get('v')+1});})));expect((await ref.get()).get('v')).toBe(6);});
 test('revoked authorization invalidates a transaction before payment writes commit',async()=>{const actor=db.doc('actors/secure'),payment=db.doc('payments/secure');await actor.set({status:'active'});await payment.set({amount:0});let announce!:()=>void,release!:()=>void,first=true;const read=new Promise<void>(r=>{announce=r;}),barrier=new Promise<void>(r=>{release=r;});const pending=db.runTransaction(async tx=>{const who=await tx.get(actor);if(who.get('status')!=='active')throw new Error('Forbidden');if(first){first=false;announce();await barrier;}tx.update(payment,{amount:100});});await read;await actor.update({status:'inactive'});release();await expect(pending).rejects.toThrow('Forbidden');expect((await payment.get()).get('amount')).toBe(0);});
 test('snapshot views cannot mutate later access checks',async()=>{const ref=db.doc('views/one');await ref.set({nested:{status:'active'}});const row=await ref.get();row.data().nested.status='inactive';row.get('nested').status='inactive';expect(row.get('nested.status')).toBe('active');});
 test('parallel application transaction reads are serialized safely',async()=>{const a=db.doc('parallel/a'),b=db.doc('parallel/b');await a.set({v:1});await b.set({v:2});await db.runTransaction(async tx=>{const [first,second]=await Promise.all([tx.get(a),tx.get(b)]);tx.update(a,{v:first.get('v')+second.get('v')});});expect((await a.get()).get('v')).toBe(3);});
 test('change streams deliver scoped additions, modifications and removals',async()=>{const ref=db.doc('events/one');const snapshots:any[]=[];let initialResolve!:()=>void;const initial=new Promise<void>(resolve=>{initialResolve=resolve;});const stop=db.collection('events').where('owner','==','a').onSnapshot(snapshot=>{snapshots.push(snapshot);initialResolve();},e=>{throw e;});await initial;await ref.create({owner:'a',value:1});const waitFor=async(predicate:()=>boolean)=>{for(let i=0;i<100&&!predicate();i++)await new Promise(resolve=>setTimeout(resolve,30));expect(predicate()).toBe(true);};await waitFor(()=>snapshots.some(s=>s.docChanges().some((c:any)=>c.type==='added')));await ref.update({value:2});await waitFor(()=>snapshots.some(s=>s.docChanges().some((c:any)=>c.type==='modified')));await ref.delete();await waitFor(()=>snapshots.some(s=>s.docChanges().some((c:any)=>c.type==='removed')));stop();});
 test('realtime subscribers share one stream and close it after the final unsubscribe',async()=>{let readyA!:()=>void,readyB!:()=>void;const a=new Promise<void>(r=>{readyA=r;}),b=new Promise<void>(r=>{readyB=r;});const stopA=db.collection('sharedwatch').where('owner','==','a').onSnapshot(()=>readyA(),e=>{throw e;}),stopB=db.collection('sharedwatch').where('owner','==','b').onSnapshot(()=>readyB(),e=>{throw e;});await Promise.all([a,b]);expect((db as any).hubs.size).toBe(1);const hub=(db as any).hubs.get('sharedwatch');expect(hub.callbacks.size).toBe(2);stopA();expect((db as any).hubs.size).toBe(1);stopB();expect((db as any).hubs.size).toBe(0);await new Promise(r=>setTimeout(r,20));expect(hub.stream.closed).toBe(true);});
 test('reference values round trip without creating a second data bank',async()=>{await db.doc('refs/one').set({owner:db.doc('users/a')});const owner=(await db.doc('refs/one').get()).get('owner');expect(owner.path).toBe('users/a');expect((await owner.get()).exists).toBe(true);});
});
