import {listNativeUsers} from '@/lib/db/repository/native-user-directory';
import {randomBytes} from 'node:crypto';
import {getNativeDatabase} from '@/lib/db/firestore-native';
import {assignNativeClient,nativeAssignmentOptions} from '@/lib/db/repository/native-client-assignment';
import {nativeUserForm} from '@/lib/db/repository/native-user-forms';
import {readNativeDataRecords} from '@/lib/db/repository/native-admin-data';
import {changeNativeClientHold} from '@/lib/db/repository/native-client-hold';
import {getApplicableHoldExtensionMs} from '@/lib/status/holdExtension';
const suite=process.env.FIRESTORE_EMULATOR_HOST?describe:describe.skip;
suite('ported admin and profile regressions',()=>{let db:ReturnType<typeof getNativeDatabase>;const refs:FirebaseFirestore.DocumentReference[]=[];async function seed(c:string,data:Record<string,unknown>){const ref=db.collection(c).doc(randomBytes(12).toString('hex'));refs.push(ref);await ref.set(data);return ref;}beforeAll(()=>{db=getNativeDatabase();});afterAll(async()=>{for(const ref of refs)await ref.delete();await db.terminate();});
 it('keeps partial lifestyle retries lossless',async()=>{const dt=await seed('users',{role:'dietitian',status:'active'}),client=await seed('users',{role:'client',status:'active',assignedDietitian:dt.id}),form=await seed('lifestyleinfos',{userId:client.id,foodPreference:'non-veg',nonVegExemptDays:['monday','thursday'],foodDislikes:'shakes',sleepPattern:'regular-sleep'});await nativeUserForm(db,dt.id,client.id,'lifestyleinfos',{stressLevel:'high'});expect((await form.get()).data()).toMatchObject({foodPreference:'non-veg',nonVegExemptDays:['monday','thursday'],foodDislikes:'shakes',sleepPattern:'regular-sleep',stressLevel:'frequent-stress'});});
 it('restricts counselors to their own clients and primary assignment, retaining secondaries on replacement',async()=>{const admin=await seed('users',{role:'admin',status:'active'}),hc=await seed('users',{role:'health_counselor',status:'active'}),dt=await seed('users',{role:'dietitian',status:'active'}),second=await seed('users',{role:'dietitian',status:'active'}),next=await seed('users',{role:'dietitian',status:'active'}),client=await seed('users',{role:'client',status:'active',assignedHealthCounselor:hc.id,assignedDietitian:dt.id,assignedDietitians:[second.id]}),other=await seed('users',{role:'client',status:'active'});const permission=await seed('permissions',{key:'assign_clients_to_dietitians',isActive:true,allowedRoles:['health_counselor']});let options=await nativeAssignmentOptions(db,hc.id,client.id);expect(options.primaryDietitianOnly).toBe(true);expect(options.dietitians.find((d:any)=>d._id===dt.id).isPrimary).toBe(true);expect(options.dietitians.find((d:any)=>d._id===second.id).isSecondary).toBe(true);for(const body of [{mode:'add',dietitianId:next.id},{dietitianIds:[dt.id,next.id]},{mode:'primary_secondary',primaryDietitianId:next.id,secondaryDietitianIds:[dt.id]}])await expect(assignNativeClient(db,hc.id,client.id,body,true)).rejects.toMatchObject({status:403});await expect(assignNativeClient(db,hc.id,other.id,{dietitianId:next.id},true)).rejects.toMatchObject({status:403});await assignNativeClient(db,hc.id,client.id,{mode:'replace',dietitianId:next.id},true);expect((await client.get()).get('assignedDietitians')).toEqual([second.id]);await assignNativeClient(db,admin.id,client.id,{mode:'add',dietitianId:dt.id},true);expect((await client.get()).get('assignedDietitians')).toEqual(expect.arrayContaining([second.id,dt.id]));await permission.update({deniedUsers:[hc.id]});await expect(assignNativeClient(db,hc.id,client.id,{dietitianId:dt.id},true)).rejects.toMatchObject({status:403});});
 it('sorts administrative payments numerically in both allocation columns',async()=>{const admin=await seed('users',{role:'admin',status:'active'}),marker='sort-'+randomBytes(6).toString('hex');for(const used of [2,30,11])await seed('unifiedpayments',{planName:marker,daysUsed:used,remainingDays:90-used,createdAt:new Date()});for(const field of ['daysUsed','remainingDays']){const result=await readNativeDataRecords(db,admin.id,new URLSearchParams({model:'UnifiedPayment',search:marker,sortBy:field,sortOrder:'asc'}));const values=result.records!.map((r:any)=>r[field]);expect(values).toEqual([...values].sort((a,b)=>a-b));}});
 it('filters computed directory status before pagination and scopes staff directories without writes',async()=>{const admin=await seed('users',{role:'admin',status:'active'}),dt=await seed('users',{role:'dietitian',status:'active'}),otherDt=await seed('users',{role:'dietitian',status:'active'}),marker='directory-'+randomBytes(6).toString('hex'),clients=[];for(let i=0;i<3;i++){const client=await seed('users',{role:'client',status:'active',firstName:marker,clientStatus:i===2?'active':'lead',assignedDietitian:i===2?otherDt.id:dt.id,createdAt:new Date(),password:'hidden'});clients.push(client);if(i<2)await seed('unifiedpayments',{client:client.id,paymentStatus:'paid',status:'paid',expectedEndDate:new Date('2099-12-01'),durationDays:30});}const found=[];for(const page of [1,2]){const result=await listNativeUsers(db,admin.id,new URLSearchParams({role:'client',search:marker,status:'active',limit:'1',page:String(page)}));expect(result.pagination.total).toBe(2);expect(result.users).toHaveLength(1);found.push(result.users[0]._id);}expect(new Set(found)).toEqual(new Set(clients.slice(0,2).map(c=>c.id)));expect((await clients[0].get()).get('clientStatus')).toBe('lead');for(const actor of [dt,otherDt]){const result=await listNativeUsers(db,actor.id,new URLSearchParams({role:'client'}));expect(result.users.every(u=>u.assignedDietitian?._id===actor.id||u.assignedDietitian===actor.id)).toBe(true);expect(result.users.some(u=>'password'in u)).toBe(false);}for(const limit of ['0','-1','invalid'])await expect(listNativeUsers(db,admin.id,new URLSearchParams({limit}))).rejects.toMatchObject({status:400});});

 it('extends both purchase stores only after the service starts',async()=>{const admin=await seed('users',{role:'admin',status:'active'}),client=await seed('users',{role:'client',status:'active'});const payments=[];for(const col of ['unifiedpayments','clientpurchases'])payments.push(await seed(col,{client:client.id,status:col==='unifiedpayments'?'paid':'active',paymentStatus:'paid',expectedStartDate:new Date('2099-01-06'),expectedEndDate:new Date('2099-02-01'),daysUsed:10}));await changeNativeClientHold(db,admin.id,client.id,true,'',new Date('2099-01-05'));await changeNativeClientHold(db,admin.id,client.id,false,'',new Date('2099-01-07'));for(const p of payments)expect((await p.get()).get('expectedEndDate').toDate()).toEqual(new Date('2099-02-02'));});
});
test('hold calculation does not extend future unused windows',()=>{expect(getApplicableHoldExtensionMs({expectedStartDate:'2099-02-01',expectedEndDate:'2099-03-01'},new Date('2099-01-01'),new Date('2099-01-03'))).toBe(0);});
