import {randomBytes} from 'node:crypto';
import {getNativeDatabase} from '@/lib/db/firestore-native';
import {runMealEngagementNotifications,runNativeMealEngagementNotifications,getPlanMealSchedules} from '@/lib/notifications/mealEngagement';
const suite=process.env.FIRESTORE_EMULATOR_HOST?describe:describe.skip;
suite('native meal engagement scheduling',()=>{
 let db:ReturnType<typeof getNativeDatabase>;let user:FirebaseFirestore.DocumentReference,plan:FirebaseFirestore.DocumentReference;
 beforeAll(()=>{db=getNativeDatabase();});beforeEach(async()=>{user=db.collection('users').doc(randomBytes(12).toString('hex'));plan=db.collection('clientmealplans').doc(randomBytes(12).toString('hex'));await user.set({role:'client',notificationTimeZone:'Australia/Sydney'});await plan.set({clientId:user.id,status:'active',startDate:new Date('2026-09-30T00:00:00+05:30'),endDate:new Date('2026-09-30T23:59:59+05:30'),meals:[{date:new Date('2026-09-30T00:00:00+05:30'),meals:{DINNER:{time:'07:00 PM',foods:[{name:'Synthetic meal'}]}}}]});});
 afterEach(async()=>{await user.delete();await plan.delete();for(const row of(await db.collection('mealengagementdispatches').where('mealPlanId','==',plan.id).get()).docs)await row.ref.delete();});afterAll(async()=>{await db.terminate();});
 it('uses the client timezone and claims one delivery under concurrent cron runs',async()=>{const deliver=jest.fn(async()=>({successCount:1,failureCount:0,invalidTokens:[],responses:[]}));const now=new Date('2026-09-30T09:00:00Z');const results=await Promise.all([runNativeMealEngagementNotifications(db,now,deliver),runNativeMealEngagementNotifications(db,now,deliver)]);expect(results.reduce((n,row)=>n+row.sent,0)).toBe(1);expect(deliver).toHaveBeenCalledTimes(1);expect((await runNativeMealEngagementNotifications(db,new Date('2026-09-30T13:30:00Z'),deliver)).due).toBe(0);});
 it('keeps provider failures redacted and honors held/disabled reminders',async()=>{const deliver=jest.fn(async()=>({successCount:0,failureCount:1,invalidTokens:[],responses:[{token:'synthetic-private-token',success:false,error:'messaging/mismatched-credential'}]}));const result=await runNativeMealEngagementNotifications(db,new Date('2026-09-30T09:00:00Z'),deliver);expect(result.failed).toBe(1);const row=(await db.collection('mealengagementdispatches').where('mealPlanId','==',plan.id).get()).docs[0];expect(row.get('status')).toBe('failed');expect(JSON.stringify(row.data())).not.toContain('synthetic-private-token');await user.update({'holdStatus.isOnHold':true});expect((await runNativeMealEngagementNotifications(db,new Date('2026-09-30T09:00:00Z'),deliver)).due).toBe(0);await user.update({'holdStatus.isOnHold':false,'settings.mealReminders':false});expect((await runNativeMealEngagementNotifications(db,new Date('2026-09-30T09:00:00Z'),deliver)).due).toBe(0);});
 it('does not repeat sparse plan days and disables the live provider wrapper locally',async()=>{const raw=(await plan.get()).data()!;raw.startDate=new Date('2026-09-29T00:00:00+05:30');raw.endDate=new Date('2026-10-01T23:59:59+05:30');raw.meals[0].date=raw.meals[0].date.toDate();expect(getPlanMealSchedules(raw,'2026-09-30')).toHaveLength(1);expect(getPlanMealSchedules(raw,'2026-10-01')).toHaveLength(0);expect(await runMealEngagementNotifications()).toMatchObject({skipped:'local_delivery_disabled'});});
});
