import {randomBytes} from 'node:crypto';
import {getNativeDatabase} from '@/lib/db/database';
import {getUserDirectorySummary} from '@/lib/services/user-directory-summary';
import {listStaffRecipes,saveStaffRecipe} from '@/lib/db/repository/native-staff-recipes';
const suite=process.env.DTPS_MONGODB_LOCAL_TEST?describe:describe.skip;
suite('native read freshness after actual writes',()=>{let db:ReturnType<typeof getNativeDatabase>;const refs:FirebaseFirestore.DocumentReference[]=[];async function seed(c:string,data:Record<string,unknown>){const ref=db.collection(c).doc(randomBytes(12).toString('hex'));refs.push(ref);await ref.set(data);return ref;}beforeAll(()=>{db=getNativeDatabase();});afterAll(async()=>{for(const ref of refs)await ref.delete();await db.terminate();});
 it('coalesces current directory summaries and sees new and deleted native users',async()=>{const first=await getUserDirectorySummary(),client=await seed('users',{role:'client',status:'active'});const summaries=await Promise.all(Array.from({length:20},()=>getUserDirectorySummary()));expect(summaries.every(s=>s.clientsCount===first.clientsCount+1)).toBe(true);await client.delete();expect((await getUserDirectorySummary()).clientsCount).toBe(first.clientsCount);});
 it('isolates recipe visibility and observes publish and deletion without stale cache',async()=>{const dt=await seed('users',{role:'dietitian',status:'active'}),client=await seed('users',{role:'client',status:'active'}),name='Synthetic Soup '+randomBytes(6).toString('hex'),recipe=await seed('recipes',{name,description:'Soup',ingredients:[{name:'Carrot',quantity:100,unit:'g'}],instructions:['Boil and serve'],prepTime:5,cookTime:10,servings:1,calories:50,protein:2,carbs:10,fat:1,createdBy:dt.id,isActive:false});const read=(id:string,inactive:boolean)=>listStaffRecipes(db,id,new URLSearchParams({exactName:name,limit:'10',includeInactive:String(inactive)}));expect((await read(dt.id,true)).recipes).toHaveLength(1);expect((await read(dt.id,false)).recipes).toHaveLength(0);expect((await read(client.id,true)).recipes).toHaveLength(0);await saveStaffRecipe(db,dt.id,{isActive:true},recipe.id);expect((await read(client.id,false)).recipes).toHaveLength(1);await saveStaffRecipe(db,dt.id,{},recipe.id,true);expect((await read(client.id,false)).recipes).toHaveLength(0);});
});
