import {nativePurchaseEligibility} from '@/lib/db/repository/native-purchase-eligibility';
import {randomBytes} from 'node:crypto';
import {getNativeDatabase} from '@/lib/db/database';
import {updateStaffPurchase,repairStaffPurchases,readStaffPurchases,createStaffPurchase} from '@/lib/db/repository/native-staff-purchases';
const suite=process.env.DTPS_MONGODB_LOCAL_TEST?describe:describe.skip;
suite('native purchase allocation reconciliation',()=>{let db:ReturnType<typeof getNativeDatabase>;beforeAll(()=>{db=getNativeDatabase();});afterAll(async()=>{await db.terminate();});const id=()=>randomBytes(12).toString('hex');
 it('repairs only linked published plans and serializes repeated allocation',async()=>{const staff=id(),client=id(),purchase=id(),plan=id(),other=id();await db.collection('users').doc(staff).set({role:'dietitian',status:'active'});await db.collection('users').doc(client).set({role:'client',status:'active',assignedDietitian:staff});await db.collection('unifiedpayments').doc(purchase).set({client,status:'paid',paymentStatus:'paid',durationDays:90,daysUsed:30,remainingDays:60});await db.collection('clientmealplans').doc(plan).set({clientId:client,purchaseId:purchase,status:'active',duration:10});await db.collection('clientmealplans').doc(id()).set({clientId:client,purchaseId:purchase,status:'active',duration:20,isDeleted:true});await db.collection('clientmealplans').doc(id()).set({clientId:client,purchaseId:other,status:'active',duration:40});const repaired=await repairStaffPurchases(db,staff,{purchaseId:purchase,action:'repair'});expect(repaired.newDaysUsed).toBe(10);expect(repaired.remainingDays).toBe(80);await Promise.all([1,2].map(()=>updateStaffPurchase(db,staff,{purchaseId:purchase,mealPlanId:plan,addDaysUsed:10})));expect((await db.collection('unifiedpayments').doc(purchase).get()).get('daysUsed')).toBe(10);await expect(updateStaffPurchase(db,staff,{purchaseId:purchase,addDaysUsed:10})).rejects.toMatchObject({status:400});await db.collection('users').doc(client).update({assignedDietitian:other});await expect(repairStaffPurchases(db,staff,{purchaseId:purchase,action:'repair'})).rejects.toMatchObject({status:403});await expect(readStaffPurchases(db,staff,new URLSearchParams({clientId:client}))).rejects.toMatchObject({status:403});}); it('rejects payment activation if staff access is revoked during provider verification',async()=>{const staff=id(),client=id(),link=id(),providerId='plink_'+id();await db.collection('users').doc(staff).set({role:'dietitian',status:'active'});await db.collection('users').doc(client).set({role:'client',status:'active',assignedDietitian:staff});await db.collection('paymentlinks').doc(link).set({client:client,razorpayPaymentLinkId:providerId,amount:100,finalAmount:100,currency:'INR',durationDays:30,status:'pending'});await expect(createStaffPurchase(db,staff,{clientId:client,paymentLinkId:link},async()=>{await db.collection('users').doc(client).update({assignedDietitian:id()});return {id:providerId,status:'paid',amount:10000,amount_paid:10000,currency:'INR'};})).rejects.toMatchObject({status:403});expect((await db.collection('unifiedpayments').where('client','==',client).get()).empty).toBe(true);});
 it('preserves inferred day counters, clamps impossible remaining days and reschedules an unused purchase',async()=>{
  const staff=id(),client=id();await db.collection('users').doc(staff).set({role:'dietitian',status:'active'});await db.collection('users').doc(client).set({role:'client',status:'active',assignedDietitian:staff});
  const inferred=id(),unused=id();await db.collection('unifiedpayments').doc(inferred).set({client,status:'paid',paymentStatus:'paid',daysUsed:64,remainingDays:26,mealPlanCreated:false,createdAt:new Date()});
  await db.collection('unifiedpayments').doc(unused).set({client,status:'paid',paymentStatus:'paid',durationDays:10,daysUsed:0,remainingDays:10,mealPlanCreated:false,expectedStartDate:new Date('2026-01-01'),expectedEndDate:new Date('2026-01-10'),createdAt:new Date()});
  const list:any=await readStaffPurchases(db,staff,new URLSearchParams({clientId:client}));expect(list.purchases.find((p:any)=>p._id===inferred)).toMatchObject({durationDays:90,daysUsed:64,remainingDays:26});
  await updateStaffPurchase(db,staff,{purchaseId:unused,expectedStartDate:'2099-09-05',expectedEndDate:'2099-09-14'});const changed=(await db.collection('unifiedpayments').doc(unused).get()).data()!;expect(changed.expectedStartDate.toDate().toISOString().slice(0,10)).toBe('2099-09-05');expect(changed.daysUsed).toBe(0);expect(changed.mealPlanCreated).toBe(false);
  await db.collection('unifiedpayments').doc(inferred).update({durationDays:90,daysUsed:60,remainingDays:90});const clamped:any=await readStaffPurchases(db,staff,new URLSearchParams({clientId:client}));const row=clamped.purchases.find((p:any)=>p._id===inferred);expect(row.daysUsed+row.remainingDays).toBeLessThanOrEqual(90);
 });
 it('ignores stale used days on an explicitly sized future purchase without a plan',async()=>{
  const staff=id(),client=id(),purchase=id();await db.collection('users').doc(staff).set({role:'dietitian',status:'active'});await db.collection('users').doc(client).set({role:'client',status:'active',assignedDietitian:staff});await db.collection('unifiedpayments').doc(purchase).set({client,status:'paid',paymentStatus:'paid',durationDays:90,durationLabel:'90 Days',daysUsed:90,mealPlanCreated:false,expectedStartDate:new Date('2099-01-01'),expectedEndDate:new Date('2099-03-31'),createdAt:new Date()});
  const result:any=await nativePurchaseEligibility(db,staff,client,1,true);expect(result.purchase._id).toBe(purchase);expect(result.purchase.daysUsed).toBe(0);expect(result.remainingDays).toBe(90);
 });

});
