import {randomBytes} from 'node:crypto';
import {NextRequest} from 'next/server';
import {getServerSession} from 'next-auth';
import {getNativeDatabase} from '@/lib/db/database';
import {sendNotificationToUser} from '@/lib/firebase/firebaseNotification';
import {POST,GET} from '@/app/api/admin/notifications/send/route';
jest.mock('next-auth',()=>({getServerSession:jest.fn()}));
jest.mock('@/lib/auth/config',()=>({authOptions:{}}));
jest.mock('@/lib/db/database',()=>({getNativeDatabase:jest.fn()}));
jest.mock('@/lib/firebase/firebaseNotification',()=>({sendNotificationToUser:jest.fn()}));
const suite=process.env.DTPS_MONGODB_LOCAL_TEST?describe:describe.skip;
suite('native notification dispatch endpoint with mocked delivery',()=>{
 let db:any,admin:string,clients:string[];
 beforeAll(()=>{db=jest.requireActual('@/lib/db/database').getNativeDatabase();jest.mocked(getNativeDatabase).mockReturnValue(db);});
 beforeEach(async()=>{admin=randomBytes(12).toString('hex');clients=Array.from({length:3},()=>randomBytes(12).toString('hex'));await db.collection('users').doc(admin).set({role:'admin',status:'active'});for(const id of clients)await db.collection('users').doc(id).set({role:'client',status:'active'});jest.mocked(getServerSession).mockResolvedValue({user:{id:admin}} as any);jest.mocked(sendNotificationToUser).mockResolvedValue({successCount:1,failureCount:0,invalidTokens:[],responses:[]});});
 afterEach(async()=>{jest.restoreAllMocks();for(const id of[admin,...clients])await db.collection('users').doc(id).delete();});afterAll(async()=>{await db.terminate();});
 const request=(patch:any={})=>new NextRequest('http://localhost/api/admin/notifications/send',{method:'POST',body:JSON.stringify({title:'Synthetic',body:'Synthetic',targetType:'particular',userIds:clients,recipientRoles:['client'],...patch})});
 it('sends exactly to the selected clients using mocked providers',async()=>{jest.replaceProperty(process.env,'NODE_ENV','production');const response=await POST(request());expect(response.status).toBe(200);expect((await response.json()).stats).toMatchObject({total:3,success:3});expect(jest.mocked(sendNotificationToUser).mock.calls.map(call=>call[0]).sort()).toEqual([...clients].sort());});
 it('validates selection and authentication, and blocks local delivery',async()=>{expect((await POST(request({userIds:[]}))).status).toBe(400);expect((await POST(request())).status).toBe(409);expect(sendNotificationToUser).not.toHaveBeenCalled();jest.mocked(getServerSession).mockResolvedValue(null);expect((await POST(request())).status).toBe(401);});
 it('returns matching recipients without exposing registration tokens',async()=>{const result=await GET(new NextRequest('http://localhost/api/admin/notifications/send?roles=client'));expect(result.status).toBe(200);const payload=await result.json();expect(payload.recipients.filter((row:any)=>clients.includes(row.id))).toHaveLength(3);expect(payload.recipients.every((row:any)=>row.fcmTokens===undefined)).toBe(true);});
});
