import {nativeResponseJson} from '@/lib/api/native-response';
import {randomUUID} from 'node:crypto';
import {NextRequest,NextResponse} from 'next/server';
import {getServerSession} from 'next-auth';
import {authOptions} from '@/lib/auth/config';
import {getNativeDatabase} from '@/lib/db/database';
import {journalProgressEntries} from '@/lib/db/repository/native-journal';
import {saveNativeProgress,deleteNativeProgress,NativeProgressError} from '@/lib/db/repository/native-progress';
import {taskClientAccess} from '@/lib/db/repository/native-staff-tasks';
import {nativeMediaJson} from '@/lib/api/native-media-json';
import {nativeJson} from '@/lib/db/repository/native-history';
import {uploadToBlob} from '@/lib/storage/blob-storage';
import {compressImageServer} from '@/lib/imageCompressionServer';
const fail=(e:any)=>nativeResponseJson({error:e?.status?e.message:'Progress photo operation failed'},{status:e?.status||503});
export async function GET(request:NextRequest){try{const session=await getServerSession(authOptions);if(!session?.user?.id)return nativeResponseJson({error:'Unauthorized'},{status:401});const db=getNativeDatabase();await taskClientAccess(db,session.user.id,session.user.id);const type=request.nextUrl.searchParams.get('type'),rows=await journalProgressEntries(db,session.user.id,['photo']);return nativeResponseJson(await nativeMediaJson(db,nativeJson({photos:rows.filter(row=>!type||(row.metadata?.photoType||row.unit||'front')===type).map(row=>({id:row._id,url:row.value,type:row.metadata?.photoType||row.unit||'front',notes:row.metadata?.notes||row.notes,createdAt:row.createdAt,imageKitFileId:row.metadata?.blobPathname||row.metadata?.imageKitFileId}))})));}catch(e){return fail(e);}}
export async function POST(request:NextRequest){try{const session=await getServerSession(authOptions);if(!session?.user?.id)return nativeResponseJson({error:'Unauthorized'},{status:401});const db=getNativeDatabase();await taskClientAccess(db,session.user.id,session.user.id);const form=await request.formData(),file=form.get('file'),photoType=String(form.get('photoType')||'front'),notes=String(form.get('notes')||'');if(!(file instanceof File)||!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>10*1024*1024||!['front','back','left','right','side'].includes(photoType)||notes.length>1000)throw new NativeProgressError('Invalid photo or details',400);const compressed=await compressImageServer(Buffer.from(await file.arrayBuffer()),{quality:85,maxWidth:1600,maxHeight:1600,format:'webp'}),uploaded=await uploadToBlob(compressed,{type:'progress-photo',filename:`${session.user.id}-${randomUUID()}.webp`,contentType:'image/webp',compress:false});if(!uploaded)throw new NativeProgressError('Media service unavailable',503);const result=await saveNativeProgress(db,session.user.id,{type:'photo',photoUrl:uploaded.url,side:photoType,notes}),entry=result.entries[0];await db.collection('progressentries').doc(entry._id).update({metadata:{photoType,notes,blobPathname:uploaded.pathname,storage:'vercel-blob',originalFilename:file.name,fileSize:file.size,mimeType:file.type}});const previous=(await journalProgressEntries(db,session.user.id,['photo'])).find(row=>row._id!==entry._id&&(row.metadata?.photoType||row.unit)===photoType);return nativeResponseJson(await nativeMediaJson(db,nativeJson({success:true,photo:{_id:entry._id,url:entry.value,photoType,notes,imageKitFileId:uploaded.pathname,blobPathname:uploaded.pathname,createdAt:entry.createdAt},previousPhoto:previous?{_id:previous._id,url:previous.value,photoType,createdAt:previous.createdAt}:null,storage:'vercel-blob'})));}catch(e){return fail(e);}}
export async function DELETE(request:NextRequest){try{const session=await getServerSession(authOptions);if(!session?.user?.id)return nativeResponseJson({error:'Unauthorized'},{status:401});const db=getNativeDatabase();await taskClientAccess(db,session.user.id,session.user.id);const id=request.nextUrl.searchParams.get('photoId');if(!id||!/^[a-f0-9]{24}$/.test(id))throw new NativeProgressError('Invalid photo ID',400);const row=await db.collection('progressentries').doc(id).get();if(row.get('type')!=='photo')throw new NativeProgressError('Photo not found',404);await deleteNativeProgress(db,session.user.id,id);return nativeResponseJson({success:true});}catch(e){return fail(e);}}
