import {nativeResponseJson} from '@/lib/api/native-response';
import {NextRequest,NextResponse} from 'next/server';
import {getServerSession} from 'next-auth';
import {authOptions} from '@/lib/auth/config';
import {getNativeDatabase} from '@/lib/db/database';
import {taskClientAccess} from '@/lib/db/repository/native-staff-tasks';
import {NativeStaffClientError} from '@/lib/db/repository/native-staff-client';
import {nativeJson} from '@/lib/db/repository/native-history';
export const dynamic='force-dynamic';
export async function GET(req:NextRequest,{params}:{params:Promise<{clientId:string}>}){try{
 const session=await getServerSession(authOptions);if(!session?.user?.id)throw new NativeStaffClientError('Unauthorized',401);const {clientId}=await params,db=getNativeDatabase(),{actor}=await taskClientAccess(db,session.user.id,clientId);if(actor.get('role')==='client')throw new NativeStaffClientError('Staff access required',403);
 const [planRows,paymentRows]=await Promise.all([db.collection('clientmealplans').where('clientId','==',clientId).where('status','in',['active','completed','draft']).select('name','status','startDate','endDate','duration','phaseNumber','phaseTag','previousPhaseId','purchaseId','dietitianId','createdAt').get(),db.collection('unifiedpayments').where('client','==',clientId).select('amount','paymentType','status','paymentStatus','paidAt','phaseTag','phaseNumber','linkedMealPlanIds','createdAt').get()]);
 const plans=planRows.docs.map(d=>({_id:d.id,...d.data()} as Record<string,any>)),payments=paymentRows.docs.map(d=>({_id:d.id,...d.data()} as Record<string,any>)).filter(d=>['paid','completed'].includes(d.status)||d.paymentStatus==='paid'),time=(d:any)=>d?.toMillis?.()||Date.parse(d)||0;
 plans.sort((a,b)=>(a.phaseNumber||0)-(b.phaseNumber||0)||time(a.startDate)-time(b.startDate)||time(a.createdAt)-time(b.createdAt));payments.sort((a,b)=>time(b.paidAt)-time(a.paidAt)||time(b.createdAt)-time(a.createdAt));
 const ids=[...new Set(plans.map(p=>p.dietitianId).filter(id=>typeof id==='string'&&/^[a-f0-9]{24}$/.test(id)))],staff=new Map();if(ids.length)for(const d of await db.getAll(...ids.map(id=>db.collection('users').doc(id)),{fieldMask:['firstName','lastName']}))if(d.exists)staff.set(d.id,{id:d.id,name:[d.get('firstName'),d.get('lastName')].filter(Boolean).join(' ')});
 const phases=plans.map((p,index)=>{const pay=payments.find(pay=>(pay.linkedMealPlanIds||[]).includes(p._id)||pay._id===p.purchaseId);return {phase:p.phaseNumber||index+1,phaseTag:p.phaseTag||`PHASE-${p.phaseNumber||index+1}`,mealPlan:{id:p._id,name:p.name,status:p.status,startDate:p.startDate,endDate:p.endDate,duration:p.duration,dietitian:staff.get(p.dietitianId)||null,createdAt:p.createdAt},payment:pay?{id:pay._id,amount:pay.amount,paymentType:pay.paymentType,status:pay.status,paidAt:pay.paidAt}:null,previousPhaseId:p.previousPhaseId};});
 return nativeResponseJson(nativeJson({success:true,clientId,summary:{totalPhases:plans.length,completedPhases:plans.filter(p=>p.status==='completed').length,activePhases:plans.filter(p=>p.status==='active').length,draftPhases:plans.filter(p=>p.status==='draft').length,currentPhase:phases.find(p=>p.mealPlan.status==='active')?.phase||null,totalPaymentAmount:payments.reduce((sum,p)=>sum+Number(p.amount||0),0),totalPayments:payments.length},phases,payments:payments.map(p=>({id:p._id,amount:p.amount,paymentType:p.paymentType,status:p.status,paidAt:p.paidAt,phaseTag:p.phaseTag,phaseNumber:p.phaseNumber,linkedMealPlanCount:p.linkedMealPlanIds?.length||0}))}));
 }catch(e){return nativeResponseJson({error:e instanceof NativeStaffClientError?e.message:'Unable to fetch phase history'},{status:e instanceof NativeStaffClientError?e.status:500});}}
